### ISSUE TITLE
Ubuntu 14.04 LTS: OpenShot suddenly won't start after upgrading

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#102]
2.0.6+0+588+97+201602152101~ubuntu14.04.1
```
$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.0.6', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
      logger:ERROR return get_distribution(dist).load_entry_point(group, name)
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
      logger:ERROR return ep.load()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
      logger:ERROR entry = __import__(self.module_name, globals(),globals(), ['__name__'])
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 41, in <module>
      logger:ERROR import openshot
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 28, in <module>
      logger:ERROR _openshot = swig_import_helper()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 24, in swig_import_helper
      logger:ERROR _mod = imp.load_module('_openshot', fp, pathname, description)
      logger:ERROR   File "/usr/lib/python3.4/imp.py", line 243, in load_module
      logger:ERROR return load_dynamic(name, filename, file)
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR libopenshot.so.6: cannot open shared object file: No such file or directory
```

**Comment by jarlarntzen** [comment]
`sudo apt-get remove openshot-qt` and then reinstalling it did help, though! Works again now.
