### ISSUE TITLE
Istallation Problems LinuxMint 18.3

### ISSUE THREAD

**Issue by jo-shi** [OpenShot/openshot-qt#1310]
**System Details:**
* Operating System / Distro: LinuxMint 18.3
* OpenShot Version: 2.4.1

Openshot doesn't start:
```
$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.4.1.dev1', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
      logger:ERROR return get_distribution(dist).load_entry_point(group, name)
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
      logger:ERROR return ep.load()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
      logger:ERROR return self.resolve()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
      logger:ERROR module = __import__(self.module_name, fromlist=['__name__'], level=0)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 41, in <module>
      logger:ERROR from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/logger_libopenshot.py", line 31, in <module>
      logger:ERROR import openshot
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 28, in <module>
      logger:ERROR _openshot = swig_import_helper()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 24, in swig_import_helper
      logger:ERROR _mod = imp.load_module('_openshot', fp, pathname, description)
      logger:ERROR   File "/usr/lib/python3.5/imp.py", line 242, in load_module
      logger:ERROR return load_dynamic(name, filename, file)
      logger:ERROR   File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
      logger:ERROR return _load(spec)
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR libsodium.so.18: cannot open shared object file: No such file or directory
```
Installation with the ppa, described on the Openshot Page

**Comment by peanutbutterandcrackers** [comment]
@jo-shi - For the moment, you could use the [AppImages](https://github.com/OpenShot/openshot-qt/releases) for now. I will try to see if I can recreate this issue on my friend's Linux Mint 18.3 laptop.

**Comment by DylanC** [comment]
@jo-shi - As a workaround for now you could try to install libsodium from the repositories. 

Enter this in the terminal:
`sudo apt-get install libsodium18`

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Is libsodium18 a required dependency on for Linux Mint 18.3 ?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I think so.  This is the solution one of the devs passed onto me.

**Comment by jo-shi** [comment]
libsodium was installed!

I have now removed libsodium18, and than removed openshot-qt. After that, there were many pakages found, which were useless. So I `sudo apt autoremove` 

Than I installed libsodium 18 and openshot-qt again and Openshot now runs flawless.

Thanks for your support @peanutbutterandcrackers and @DylanC!

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Hmm... I see. I just installed OpenShot via PPA on my friend's laptop (running Linux Mint 18.3) and it just worked. I didn't stumble upon this issue. But $ dpkg --status libsodium18 shows that it is "installed ok installed". Perhpas another one of the programs had installed it before...

@jo-shi - You're most welcome! Glad it is working for you! Hope you create awesome videos with OpenShot!

**Comment by peanutbutterandcrackers** [comment]
Hmm... I see.
