### ISSUE TITLE
AppImage 2.0.7 (and 2.0.6) builds fail to launch - "undefined symbol: g_variant_dict_ref"

### ISSUE THREAD

**Issue by publicus** [OpenShot/openshot-qt#163]
I'm not sure whether this is related to Issue #159. I'm unable to launch the AppImage version of OpenShot 2.0.7 (I also tried 2.0.6 and received an identical error). I've never used an AppImage-packaged file; are there additional dependencies that I need to install? If so, I'm wondering whether that could be added to the documentation. If not, what other steps might be needed to resolve this?

I'm running OpenSUSE 13.1, and am happy to provide any other debugging output or other information. Thank you for your work on this project!

```
user@computer:~/Downloads$ ./OpenShot-2.0.7.AppImage 
/tmp/.mount_TiuY9J/usr/bin/openshot-qt.wrapper
Loaded modules from current directory: /tmp/.mount_TiuY9J/usr/bin
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.3-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 53, in <module>
    from classes.app import OpenShotApp
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_TiuY9J/usr/bin/classes/app.py", line 33, in <module>
    from PyQt5.QtWidgets import QApplication, QStyleFactory
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 22, in <module>
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 14, in __bootstrap__
ImportError: /tmp/.mount_TiuY9J/usr/bin/libgobject-2.0.so.0: undefined symbol: g_variant_dict_ref
```

**Comment by probonopd** [comment]
Looks like the version of libglib2 on your host system is too old for this AppImage and the AppImage is not bundling a more recent version of libglib2. Can you try the AppImage on another system with a more recent version of libglib2?

**Comment by jonoomph** [comment]
@probonopd I'm going to give this a try, and see what happens. Fingers crossed. Thx!

**Comment by jonoomph** [comment]
Okay, the latest daily build should contain the glib2 libraries:
- libglib-2.0.so
- libgio-2.0.so
- libgmodule-2.0.so
- libgobject-2.0.so
- libgthread-2.0.so

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

**Comment by probonopd** [comment]
See https://github.com/OpenShot/openshot-qt/issues/298
