### ISSUE TITLE
ImportError: No module named 'PyQt5.QtWebKitWidgets'

### ISSUE THREAD

**Issue by alpinekid** [OpenShot/openshot-qt#2057]
I have tried installing the stable version and the dev version and I get the same error on launch.
You have to invoke it from a command line to see the error. When launch from the desktop nothing is visible.  The process just hangs. You can see the hang by looking a the process list.

I have the QtWebKit package installed but it does not have this file in it. There is a cpython version but that is as close as it comes.
/usr/lib/python3/dist-packages/PyQt5
/usr/lib/python3/dist-packages/PyQt5/QtWebKit.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/PyQt5/QtWebKitWidgets.cpython-35m-x86_64-linux-gnu.so

I running
ubuntu 16.4
openshot 2.4.2.dev1 loaded from the ppa

**To Reproduce**
from command line type:
 openshot-qt

From another command line you can see it hung.

**Expected behavior**
It should startup

Visible on screen:

:~$ openshot-qt
Compiled translation resources missing!
Loading translations from: /usr/lib/python3/dist-packages/openshot_qt/language
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.2-dev1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.2-dev1
         app:INFO libopenshot version: 0.2.0
         app:INFO platform: Linux-4.4.0-134-generic-x86_64-with-Ubuntu-16.04-xenial
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2
         app:INFO qt5 version: 5.10.0
         app:INFO pyqt5 version: 5.10
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 9, in <module>
    load_entry_point('openshot-qt==2.4.2.dev1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 98, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 159, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *duplicate-exception-ignored*

If you need me to run something to test, just let me know. Ive tried both the stable and the dev version.

**Comment by BagelOrb** [comment]
Workaround: download the AppImage and open the program from there.

**Comment by ferdnyc** [comment]
> Hopefully OpenShot will switch to PyQt5.QtWebEngineWidgets soon.

Highly unlikely, see the discussion in #2144. Despite the way it's made to sound, particularly by Qt, moving from QtWebKit to QtWebEngine is _not_ a small undertaking, particularly for a codebase like OpenShot that makes use of QtWebKit facilities that have no equivalent in QtWebEngine.

@DylanC and I, the only ones who've really even discussed this, both agree that getting rid of QtWebKit would be great. But we've also agreed that we'd prefer to replace it with something _completely_ different, rather than making a mostly-lateral (but still arduous) move to QtWebEngine. But even **that** effort, beyond our agreeing it's the best approach, has no timeframe or commitment to execution. In fact, there's no concrete expectation as to when, or if, anyone might ever _start_ working on it.

For the moment, QtWebKit is here to stay for OpenShot. And my understanding is that it's still available for Ubuntu. If there are problems with the PPA not being able to _access_ PyQt5.QtWebKit, we should attempt to figure out what those issues are, how to correct them, and whether additional dependencies or whatever can be added to the OpenShot PPA build(s) to prevent them from occurring. 

I'm a Fedora user, so I can only really comment on the packaging there. But, on Fedora, the native OpenShot packages (which, due to the non-free licensing of several video components, are maintained — by me — in the third-party [rpmfusion](https://rpmfusion.org/) package collection) have dependencies on all of the other packages it requires in order to run:
```console
$ rpm -q --requires openshot
/usr/bin/python3
ffmpeg-libs
python(abi) = 3.6
python3-httplib2
python3-libopenshot >= 0.2.0
python3-qt5
python3-qt5-webkit
python3-zmq
```
Which means OpenShot can't be installed _without_ those components. As well as all of _their_ dependencies, and their dependencies' dependencies and so on and so on*. 

(The _full_ dependency list for OpenShot is, therefore, rather extreme.)<details>
<summary>Complete dependency list for `openshot-2.4.3-1.fc28.noarch`</summary>

```console
$ rpmdep.pl openshot|sed -e 's/,/, /g'|fold -s
openshot depends upon ImageMagick-c++, ImageMagick-libs, OpenEXR-libs, SDL2, 
acl, adobe-mappings-cmap, adobe-mappings-cmap-deprecated, adobe-mappings-pdf, 
alsa-lib, audit-libs, avahi-libs, basesystem, bash, bluez-libs, bzip2-libs, 
ca-certificates, cairo, cdparanoia-libs, chkconfig, coreutils, 
coreutils-common, cracklib, crypto-policies, cryptsetup-libs, cups-libs, curl, 
cyrus-sasl-lib, dbus, dbus-glib, dbus-libs, device-mapper, device-mapper-libs, 
dwz, elfutils-default-yama-scope, elfutils-libelf, elfutils-libs, 
emacs-filesystem, expat, fedora-gpg-keys, fedora-release, fedora-repos, 
ffmpeg-libs, fftw-libs-double, file, file-libs, filesystem, findutils, 
flac-libs, fontconfig, fontpackages-filesystem, fpc-srpm-macros, freetype, 
fribidi, gawk, gdbm, gdbm-libs, gdk-pixbuf2, ghc-srpm-macros, glib-networking, 
glib2, glibc, glibc-common, glibc-langpack-de, glx-utils, gmp, 
gnat-srpm-macros, gnutls, go-srpm-macros, google-crosextra-carlito-fonts, 
google-droid-sans-fonts, graphite2, grep, gsettings-desktop-schemas, gsm, 
gssdp, gstreamer1, gstreamer1-plugins-bad-free, gstreamer1-plugins-base, gupnp, 
gupnp-igd, gzip, harfbuzz, hwdata, hyphen, ilmbase, info, iptables-libs, 
iso-codes, jbig2dec-libs, jbigkit-libs, json-c, jsoncpp, keyutils-libs, 
kmod-libs, krb5-libs, lame-libs, lcms2, libICE, libSM, libX11, libX11-common, 
libX11-xcb, libXau, libXcomposite, libXcursor, libXdamage, libXext, libXfixes, 
libXft, libXi, libXinerama, libXmu, libXrandr, libXrender, libXt, libXtst, 
libXv, libXxf86misc, libXxf86vm, libacl, libaom, libarchive, libargon2, libass, 
libasyncns, libatomic, libattr, libavdevice, libblkid, libbluray, libcap, 
libcap-ng, libcdio, libcdio-paranoia, libcom_err, libcroco, libcurl, libdatrie, 
libdb, libdb-utils, libdrm, libdvdnav, libdvdread, libevdev, libfdisk, libffi, 
libfontenc, libgcc, libgcrypt, libglvnd, libglvnd-egl, libglvnd-gles, 
libglvnd-glx, libgomp, libgpg-error, libgs, libgudev, libicu, libidn, libidn2, 
libijs, libinput, libjpeg-turbo, libmcpp, libmetalink, libmfx, libmodman, 
libmount, libmpcdec, libnghttp2, libnice, libnsl2, libogg, libopenshot, 
libopenshot-audio, libpaper, libpcap, libpciaccess, libpkgconf, libpng, 
libproxy, libpsl, libpwquality, librsvg2, libseccomp, libselinux, libsemanage, 
libsepol, libsigsegv, libsmartcols, libsndfile, libsoup, libsrtp, libssh, 
libstdc++, libtasn1, libthai, libtheora, libtiff, libtirpc, libtool-ltdl, 
libunistring, libusbx, libutempter, libuuid, libv4l, libva, libvdpau, libverto, 
libvisual, libvorbis, libvpx, libwacom, libwacom-data, libwayland-client, 
libwayland-cursor, libwayland-egl, libwayland-server, libwebp, libwmf-lite, 
libxcb, libxcrypt, libxcrypt-common, libxkbcommon, libxkbcommon-x11, libxml2, 
libxshmfence, libxslt, libzstd, lua-libs, lz4-libs, mcpp, mesa-filesystem, 
mesa-libEGL, mesa-libGL, mesa-libgbm, mesa-libglapi, mpfr, mtdev, ncurses, 
ncurses-base, ncurses-libs, nettle, nim-srpm-macros, nspr, nss, nss-softokn, 
nss-softokn-freebl, nss-sysinit, nss-util, numactl-libs, ocaml-srpm-macros, 
ocl-icd, openal-soft, openblas-srpm-macros, opencore-amr, openjpeg2, openldap, 
openpgm, openssl-libs, opus, orc, p11-kit, p11-kit-trust, pam, pango, pcre, 
pcre2, pcre2-utf16, perl-srpm-macros, pixman, pkgconf, pkgconf-m4, 
pkgconf-pkg-config, popt, publicsuffix-list-dafsa, pulseaudio-libs, 
pulseaudio-libs-glib2, python-qt5-rpm-macros, python-srpm-macros, python3, 
python3-dbus, python3-httplib2, python3-libopenshot, python3-libs, python3-pip, 
python3-qt5, python3-qt5-base, python3-qt5-webkit, python3-setuptools, 
python3-sip, python3-zmq, python37, qrencode-libs, qt-settings, qt5-qtbase, 
qt5-qtbase-common, qt5-qtbase-gui, qt5-qtconnectivity, qt5-qtdeclarative, 
qt5-qtenginio, qt5-qtlocation, qt5-qtmultimedia, qt5-qtsensors, 
qt5-qtserialport, qt5-qtsvg, qt5-qttools-common, qt5-qttools-libs-designer, 
qt5-qttools-libs-help, qt5-qtwebchannel, qt5-qtwebkit, qt5-qtwebsockets, 
qt5-qtx11extras, qt5-qtxmlpatterns, qt5-srpm-macros, readline, 
redhat-rpm-config, rpm, rpm-libs, rpm-plugin-selinux, rust-srpm-macros, sed, 
setup, shadow-utils, shared-mime-info, soundtouch, soxr, speex, sqlite-libs, 
systemd, systemd-libs, systemd-pam, tcl, tk, tzdata, unzip, 
urw-base35-bookman-fonts, urw-base35-c059-fonts, urw-base35-d050000l-fonts, 
urw-base35-fonts, urw-base35-fonts-common, urw-base35-gothic-fonts, 
urw-base35-nimbus-mono-ps-fonts, urw-base35-nimbus-roman-fonts, 
urw-base35-nimbus-sans-fonts, urw-base35-p052-fonts, 
urw-base35-standard-symbols-ps-fonts, urw-base35-z003-fonts, util-linux, 
vid.stab, vo-amrwbenc, webrtc-audio-processing, x264-libs, x265-libs, xcb-util, 
xcb-util-image, xcb-util-keysyms, xcb-util-renderutil, xcb-util-wm, 
xkeyboard-config, xml-common, xorg-x11-font-utils, xorg-x11-server-utils, 
xvidcore, xz-libs, zeromq, zip, zlib, zvbi
openshot depends upon ImageMagick-c++, ImageMagick-libs, OpenEXR-libs, SDL2, 
acl, adobe-mappings-cmap, adobe-mappings-cmap-deprecated, adobe-mappings-pdf, 
alsa-lib, audit-libs, avahi-libs, basesystem, bash, bluez-libs, bzip2-libs, 
ca-certificates, cairo, cdparanoia-libs, chkconfig, coreutils, 
coreutils-common, cracklib, crypto-policies, cryptsetup-libs, cups-libs, curl, 
cyrus-sasl-lib, dbus, dbus-glib, dbus-libs, device-mapper, device-mapper-libs, 
dwz, elfutils-default-yama-scope, elfutils-libelf, elfutils-libs, 
emacs-filesystem, expat, fedora-gpg-keys, fedora-release, fedora-repos, 
ffmpeg-libs, fftw-libs-double, file, file-libs, filesystem, findutils, 
flac-libs, fontconfig, fontpackages-filesystem, fpc-srpm-macros, freetype, 
fribidi, gawk, gdbm, gdbm-libs, gdk-pixbuf2, ghc-srpm-macros, glib-networking, 
glib2, glibc, glibc-common, glibc-langpack-de, glx-utils, gmp, 
gnat-srpm-macros, gnutls, go-srpm-macros, google-crosextra-carlito-fonts, 
google-droid-sans-fonts, graphite2, grep, gsettings-desktop-schemas, gsm, 
gssdp, gstreamer1, gstreamer1-plugins-bad-free, gstreamer1-plugins-base, gupnp, 
gupnp-igd, gzip, harfbuzz, hwdata, hyphen, ilmbase, info, iptables-libs, 
iso-codes, jbig2dec-libs, jbigkit-libs, json-c, jsoncpp, keyutils-libs, 
kmod-libs, krb5-libs, lame-libs, lcms2, libICE, libSM, libX11, libX11-common, 
libX11-xcb, libXau, libXcomposite, libXcursor, libXdamage, libXext, libXfixes, 
libXft, libXi, libXinerama, libXmu, libXrandr, libXrender, libXt, libXtst, 
libXv, libXxf86misc, libXxf86vm, libacl, libaom, libarchive, libargon2, libass, 
libasyncns, libatomic, libattr, libavdevice, libblkid, libbluray, libcap, 
libcap-ng, libcdio, libcdio-paranoia, libcom_err, libcroco, libcurl, libdatrie, 
libdb, libdb-utils, libdrm, libdvdnav, libdvdread, libevdev, libfdisk, libffi, 
libfontenc, libgcc, libgcrypt, libglvnd, libglvnd-egl, libglvnd-gles, 
libglvnd-glx, libgomp, libgpg-error, libgs, libgudev, libicu, libidn, libidn2, 
libijs, libinput, libjpeg-turbo, libmcpp, libmetalink, libmfx, libmodman, 
libmount, libmpcdec, libnghttp2, libnice, libnsl2, libogg, libopenshot, 
libopenshot-audio, libpaper, libpcap, libpciaccess, libpkgconf, libpng, 
libproxy, libpsl, libpwquality, librsvg2, libseccomp, libselinux, libsemanage, 
libsepol, libsigsegv, libsmartcols, libsndfile, libsoup, libsrtp, libssh, 
libstdc++, libtasn1, libthai, libtheora, libtiff, libtirpc, libtool-ltdl, 
libunistring, libusbx, libutempter, libuuid, libv4l, libva, libvdpau, libverto, 
libvisual, libvorbis, libvpx, libwacom, libwacom-data, libwayland-client, 
libwayland-cursor, libwayland-egl, libwayland-server, libwebp, libwmf-lite, 
libxcb, libxcrypt, libxcrypt-common, libxkbcommon, libxkbcommon-x11, libxml2, 
libxshmfence, libxslt, libzstd, lua-libs, lz4-libs, mcpp, mesa-filesystem, 
mesa-libEGL, mesa-libGL, mesa-libgbm, mesa-libglapi, mpfr, mtdev, ncurses, 
ncurses-base, ncurses-libs, nettle, nim-srpm-macros, nspr, nss, nss-softokn, 
nss-softokn-freebl, nss-sysinit, nss-util, numactl-libs, ocaml-srpm-macros, 
ocl-icd, openal-soft, openblas-srpm-macros, opencore-amr, openjpeg2, openldap, 
openpgm, openssl-libs, opus, orc, p11-kit, p11-kit-trust, pam, pango, pcre, 
pcre2, pcre2-utf16, perl-srpm-macros, pixman, pkgconf, pkgconf-m4, 
pkgconf-pkg-config, popt, publicsuffix-list-dafsa, pulseaudio-libs, 
pulseaudio-libs-glib2, python-qt5-rpm-macros, python-srpm-macros, python3, 
python3-dbus, python3-httplib2, python3-libopenshot, python3-libs, python3-pip, 
python3-qt5, python3-qt5-base, python3-qt5-webkit, python3-setuptools, 
python3-sip, python3-zmq, python37, qrencode-libs, qt-settings, qt5-qtbase, 
qt5-qtbase-common, qt5-qtbase-gui, qt5-qtconnectivity, qt5-qtdeclarative, 
qt5-qtenginio, qt5-qtlocation, qt5-qtmultimedia, qt5-qtsensors, 
qt5-qtserialport, qt5-qtsvg, qt5-qttools-common, qt5-qttools-libs-designer, 
qt5-qttools-libs-help, qt5-qtwebchannel, qt5-qtwebkit, qt5-qtwebsockets, 
qt5-qtx11extras, qt5-qtxmlpatterns, qt5-srpm-macros, readline, 
redhat-rpm-config, rpm, rpm-libs, rpm-plugin-selinux, rust-srpm-macros, sed, 
setup, shadow-utils, shared-mime-info, soundtouch, soxr, speex, sqlite-libs, 
systemd, systemd-libs, systemd-pam, tcl, tk, tzdata, unzip, 
urw-base35-bookman-fonts, urw-base35-c059-fonts, urw-base35-d050000l-fonts, 
urw-base35-fonts, urw-base35-fonts-common, urw-base35-gothic-fonts, 
urw-base35-nimbus-mono-ps-fonts, urw-base35-nimbus-roman-fonts, 
urw-base35-nimbus-sans-fonts, urw-base35-p052-fonts, 
urw-base35-standard-symbols-ps-fonts, urw-base35-z003-fonts, util-linux, 
vid.stab, vo-amrwbenc, webrtc-audio-processing, x264-libs, x265-libs, xcb-util, 
xcb-util-image, xcb-util-keysyms, xcb-util-renderutil, xcb-util-wm, 
xkeyboard-config, xml-common, xorg-x11-font-utils, xorg-x11-server-utils, 
xvidcore, xz-libs, zeromq, zip, zlib, zvbi
```
</details>
<br/>

`dnf` (the Fedora "`apt`") won't **let** you install OpenShot if _any_ of the items on that list are missing or configured improperly. If you _try_, it'll damn well install them for you, or abort with an error if it can't. I've always assumed that the same goes for `apt`, or what's even the point of it? But on more than one occasion, I've been surprised to learn that doesn't appear to be the case, at least not by default.

Still, if there's any way we can _make_ it more the case, I'm very much interested in doing that, so that other Ubuntu users won't encounter these same issues.

**Comment by meiying-ghost** [comment]
My Debian system is the same.  I used pip to uninstall pyqt5 and sip. With apt-get installed Python 3-pyqt5, Python 3-sip, can be used normally.

**Comment by CoolGames** [comment]
Not sure why I get this as I am not a programmer.

```
 openshot-qt
Compiled translation resources missing!
Loading translations from: /usr/lib/python3/dist-packages/openshot_qt/language
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.3)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.3
         app:INFO libopenshot version: 0.2.2
         app:INFO platform: Linux-5.0.0-31-lowlatency-x86_64-with-Ubuntu-19.04-disco
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.7.3
         app:INFO qt5 version: 5.13.0
         app:INFO pyqt5 version: 5.13.1
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 60 fps
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to Cantarell
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.4.3', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 98, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 157, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```

SYSTEM INFO
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.04
Release:	19.04
Codename:	disco
(Actually Ubuntu Studio 19.04 with Pop added)
$ uname -a
Linux xxxxxxx 5.0.0-31-lowlatency #33-Ubuntu SMP PREEMPT Mon Sep 30 19:30:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
PyQTWebKit INFO

```
$ dpkg --list | grep qtwebkit
ii  libqtwebkit4:amd64                                          2.3.2-0ubuntu13                                                  amd64        Web content engine library for Qt
ii  python-pyqt5.qtwebkit                                       5.12.1+dfsg-1                                                    amd64        Python 2 bindings for Qt5's WebKit module
ii  python3-pyqt5.qtwebkit                                      5.12.1+dfsg-1                                                    amd64        Python 3 bindings for Qt5's WebKit module

```
Python3 Pip3 INFO

```
$ pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
$ python3 --version
Python 3.7.3
$  pip3 install  PyQtWebkit
Collecting PyQtWebkit
  Could not find a version that satisfies the requirement PyQtWebkit (from versions: )
No matching distribution found for PyQtWebkit


```

**Comment by behnambm** [comment]
This worked for me : 
` $pip3 uninstall pyqt5`

**Comment by Bishwas-py** [comment]
Thanks, bro

**Comment by ferdnyc** [comment]
This should be fixed in the latest daily PPAs, which now have a dependency on pyqtwebengine.
