### ISSUE TITLE
Cannot start OpenShot after delete some Python files

### ISSUE THREAD

**Issue by Nick222** [OpenShot/openshot-qt#2362]
Xubuntu 18.10
OpenShot-Qt 2.4.3 from https://launchpad.net/~openshot.developers/+archive/ubuntu/libopenshot-daily

I delete some files from /usr/local/lib/python3.6/dist-packages/openshot_qt-2.4.1-py.3.6.egg - because it was some errors while OpenShot starting.

Now I cannot start OpenShot at all:

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 578, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 895, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (openshot-qt 2.4.3.dev1 (/usr/lib/python3/dist-packages), Requirement.parse('openshot-qt==2.4.1'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/openshot-qt", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3105, in <module>
>     @_call_aside
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3089, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 580, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 781, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'openshot-qt==2.4.1' distribution was not found and is required by the application

What can I do to restore OpenShot work ?

**Comment by ferdnyc** [comment]
Glad to hear it! Please Close the issue, since it was specific to your install and has been solved.
