### ISSUE TITLE
AppImage doesn't work on Porteus 4 Xfce distro

### ISSUE THREAD

**Issue by fulalas** [OpenShot/openshot-qt#2493]
Here's the output for OpenShot version 2.4.3:

```
Loaded modules from current directory: /tmp/.mount_AZwap6/usr/bin
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 54, in <module>
    from classes.app import OpenShotApp
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_AZwap6/usr/bin/classes/app.py", line 34, in <module>
    from PyQt5.QtWidgets import QApplication, QStyleFactory, QMessageBox
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 22, in <module>
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 14, in __bootstrap__
ImportError: /usr/lib64/libGL.so.1: undefined symbol: xcb_dri3_get_supported_modifiers
```

The last daily build (OpenShot-v2.4.3-dev2-1546031351-a8f75a5b-3861a2c5-x86_64) gives me the same output error.

AppImages should be built using the most minimalist distro possible, like TinyCore. So, correct if I'm wrong, but I believe OpenShot AppImage is probably built using *buntu familiy, so it doesn't work with less bloated distros, like Porteus.

**Comment by peanutbutterandcrackers** [comment]
For the time being, perhaps you could use flatpaks?

**Comment by fulalas** [comment]
Thanks for the tip, but Flatpak is too complicated (tons of dependencies even for running the package).
