### ISSUE TITLE
Export Dialog Doesn't Appear

### ISSUE THREAD

**Issue by bwb289** [OpenShot/openshot-qt#2676]
When I click the export button, nothing happens. The program acts as if nothing was clicked.

Windows 10, Ver 2.4.3

**Comment by pferreir** [comment]
Same here.

**Comment by SuslikV** [comment]
@pferreir please, post your OpenShot log-file.

**Comment by pferreir** [comment]
In the meantime I managed to fix the project by editing the JSON and fixing some `null` fields. It had somehow gotten corrupted.

**Comment by jackoverfull** [comment]
Same problem here, on macOS Sierra 10.12.16 on MacBookPro5,1.

This is what I get in the Terminal when I click on the button:
```

     ui_util:INFO Initializing UI for Dialog
      export:INFO (4, 'Mono (1 canale)')
      export:INFO (3, 'Stereo (2 canali)')
      export:INFO (7, 'Surround (3 canali)')
      export:INFO (1551, 'Surround (5.1 canali)')
      export:INFO (1599, 'Surround (7.1 canali)')
      export:INFO /Applications/Video/OpenShot Video Editor.app/Contents/Resources/profiles/square_pal_wide
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/Applications/Video/OpenShot Video Editor.app/Contents/MacOS/windows/main_window.py", line 741, in actionExportVideo_trigger
    win = Export()
  File "/Applications/Video/OpenShot Video Editor.app/Contents/MacOS/windows/export.py", line 232, in __init__
    xmldoc = xml.parse(os.path.join(preset_path, file))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/dom/minidom.py", line 1958, in parse
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/dom/expatbuilder.py", line 911, in parse
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/dom/expatbuilder.py", line 207, in parseFile
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=7043b0ca-f692-46d5-a5d4-35abf5e45307&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_12_6%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.6.4&cd3=5.5.1&cd4=5.5.1&cd5=OS+X+10.12.6&t=screenview&cd=export-screen | (35 bytes)
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *failed-recording-exception*: Control/space characters not allowed (key=b':1:Darwin-2.5.1-xml.parsers.expat.ExpatError: no')
```

**Comment by SuslikV** [comment]
@jackoverfull that means that file:
```
/Applications/Video/OpenShot Video Editor.app/Contents/Resources/profiles/square_pal_wide
```
is malformed for python processing. Is the error happens to any export profile you have? And what version of the application you are using?
