### ISSUE TITLE
openshot-qt-2.4.4 fails to run with module 'openshot' has no attribute 'GetVersion'

### ISSUE THREAD

**Issue by juanitotc** [OpenShot/openshot-qt#2779]
Using libopenshot-0.2.3 and libopenshot-audio-0.1.8 on tinycorelinux where squashfs packages are loop mounted and symlinked to the root file system.

Is GetVersion() referring to libopenshot or am I missing a python package?

$ openshot-qt
Loaded modules from installed directory: /tmp/tcloop/openshot/usr/local/lib/python3.6/site-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.4)
      launch:INFO ------------------------------------------------
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-tc'
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/local/bin/openshot-qt", line 11, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.4.4', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/local/lib/python3.6/site-packages/openshot_qt/launch.py", line 103, in main
      logger:ERROR app = OpenShotApp(argv)
      logger:ERROR   File "/tmp/tcloop/openshot/usr/local/lib/python3.6/site-packages/openshot_qt/classes/app.py", line 87, in __init__
      logger:ERROR from classes import exceptions
      logger:ERROR   File "/tmp/tcloop/openshot/usr/local/lib/python3.6/site-packages/openshot_qt/classes/exceptions.py", line 30, in <module>
      logger:ERROR from classes.metrics import track_exception_stacktrace
      logger:ERROR   File "/tmp/tcloop/openshot/usr/local/lib/python3.6/site-packages/openshot_qt/classes/metrics.py", line 46, in <module>
      logger:ERROR libopenshot_version = openshot.GetVersion()
      logger:ERROR AttributeError
      logger:ERROR :
      logger:ERROR module 'openshot' has no attribute 'GetVersion'

**Comment by juanitotc** [comment]
The error was caused by libopenshot not installing the following:

/usr/local/lib/python3.6/site-packages/_openshot.so
/usr/local/lib/python3.6/site-packages/openshot.py

..now these have been added things work better (but still need qtwebkit <sigh>)
