### ISSUE TITLE
AppImage 2.0.7 build fail to launch - "undefined symbol: g_variant_dict_ref"

### ISSUE THREAD

**Issue by Pigi-102** [OpenShot/openshot-qt#279]
I'm on slackware 14.1 and have this issue.
pigi@topolinux: /home/pigi> ./OpenShot-v2.0.7-55-g448a3ce-48-560-x86_64.bin 
/tmp/.mount_KOkI32/usr/bin/openshot-qt.wrapper
realPath called with a relative path './share/pixmaps/', please fix
realPath called with a relative path './share/icons/', please fix
kdialog(23636)/kdeui (KNotification) KNotificationManager::notificationClosed: 4097
Loaded modules from current directory: /tmp/.mount_KOkI32/usr/bin
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.3-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 53, in <module>
    from classes.app import OpenShotApp
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_KOkI32/usr/bin/classes/app.py", line 33, in <module>
    from PyQt5.QtWidgets import QApplication, QStyleFactory
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 22, in <module>
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 14, in __bootstrap__
ImportError: /tmp/.mount_KOkI32/usr/bin/libgobject-2.0.so.0: undefined symbol: g_variant_dict_ref

I have read the issue #163 and that's why I've tried the daily, but the problem seems to be still there.

I can see that:
pigi@topolinux: /home/pigi> ldd ./OpenShot-v2.0.7-55-g448a3ce-48-560-x86_64.bin
        linux-vdso.so.1 (0x00007fffab5ff000)
        libfuse.so.2 => /lib64/libfuse.so.2 (0x00007ff56bfe8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff56bdca000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007ff56baa0000)
        libz.so.1 => /lib64/libz.so.1 (0x00007ff56b88b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff56b4ce000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ff56b2c6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ff56b0c2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff56c255000)

Thus it seems that the libglib-2.0 being used is the distribution one, not the included ( and it's missing the needed symbol ).

Pigi

**Comment by jonoomph** [comment]
The AppImage should be fixed now.  Please give this a try again, and re-open this ticket if it still breaks. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot's AppImage. Thanks!
