### ISSUE TITLE
New version 2.5 will not start, some problem with something called PyQt5.QtWebKitWidgets

### ISSUE THREAD

**Issue by dln949** [OpenShot/openshot-qt#3216]
Running Ubuntu 18.04
Openshot 2.5 from the openshot.developers PPA

After this upgrade, when I try to start openshot, I get the error messages you see below.  I am sorry, I am not a technical person, so I don't know what it is telling me, nor what I should do.  I did see that there were other issues that mentioned PyQt5.QtWebKitWidgets, but I did not understand from them what I should be doing to fix this issue.  Would someone explain to me what needs to be done by a layman like me?  Thanks.  

```
main1@system1:~$ openshot-qt %F
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Tue Feb 11 20:13:27 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.0-dev1)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.0-dev1
         app:INFO libopenshot version: 0.2.4-dev1
         app:INFO platform: Linux-5.3.0-7625-generic-x86_64-with-Ubuntu-18.04-bionic
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.6.9
         app:INFO qt5 version: 5.13.2
         app:INFO pyqt5 version: 5.13.2
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HDV 720 24p
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.5.0.dev1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 220, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 45, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 42, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *failed-recording-exception*: Control/space characters not allowed (key=b':1:Linux-2.5.0-dev1-ModuleNotFoundError: No module n')
```

**Comment by SuslikV** [comment]
The mentioned lib is part of the other lib (_libopenshot_) that required to start OpenShot. Unfortunately, all these libs should be from the same build to make the OpenShot to work. If after install the mentioned lib couldn't be found then you need to look at other installation source that will ship/download all required files.

**Comment by ferdnyc** [comment]
@SuslikV is mistaken, PyQt5.QtWebKitWidgets is part of the Python dependencies for OpenShot.

You should install the QtWebKit Python package using `apt`, @dln949  — specifically:
```sh
sudo apt install python3-pyqt5.qtwebkit
```

**Comment by SuslikV** [comment]
@ferdnyc you can compile _libopenshot_ without Python?

**Comment by dln949** [comment]
> @SuslikV is mistaken, PyQt5.QtWebKitWidgets is part of the Python dependencies for OpenShot.
> 
> You should install the QtWebKit Python package using `apt`, @dln949 — specifically:
> 
> ```shell
> sudo apt install python3-pyqt5.qtwebkit
> ```

@ferdnyc , per Synaptic, I already have python3-pyqt5.qtwebkit installed, version 5.10.1+dfsg-1ubuntu2 (bionic)

How does that alter your thinking about what the problem is that I am seeing?
