### ISSUE TITLE
Ubuntu 14.04 LTS: Title font dialog always resets to Ubuntu Medium 11 px font

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#33]
Although the title editor (Ctrl+T) does appear and allow adding a title, it does not seem possible to modify the title font at all.

The title font dialog opens as expected but no matter what properties I set in the font editor, the title font is not affected.

Snippet when invoking dialog. Seems like initialization of some element didn't quite work but I do not know if that's the actual offender.

```
QMetaObject::invokeMethod: No such method QMenuBar::aboutToShow()
    uiparser:DEBUG UI version is 4.0
    uiparser:DEBUG uiname is Dialog
    uiparser:DEBUG toplevel widget is TitleEditor
  properties:DEBUG setting property geometry
  properties:DEBUG setting property windowTitle
  properties:DEBUG setting property autoFillBackground
    uiparser:DEBUG push TitleEditor Dialog
    uiparser:DEBUG push QGridLayout gridLayout
  properties:DEBUG setting property orientation
  properties:DEBUG setting property standardButtons
    uiparser:DEBUG push QDialogButtonBox buttonBox
    uiparser:DEBUG pop widget QDialogButtonBox buttonBox
    uiparser:DEBUG new topwidget <windows.title_editor.TitleEditor object at 0x7f418e7b2f78>
  properties:DEBUG setting property orientation
    uiparser:DEBUG push QSplitter splitter
    uiparser:DEBUG push QWidget widget
  properties:DEBUG setting property margin
    uiparser:DEBUG push QGridLayout gridLayout_2
  properties:DEBUG setting property minimumSize
    uiparser:DEBUG push QGraphicsView graphicsView
    uiparser:DEBUG pop widget QGraphicsView graphicsView
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7921f8>
    uiparser:DEBUG pop layout QGridLayout gridLayout_2
    uiparser:DEBUG pop widget QWidget widget
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QSplitter object at 0x7f418e792168>
  properties:DEBUG setting property sizePolicy
    uiparser:DEBUG push QWidget widgetForm
  properties:DEBUG setting property sizeConstraint
  properties:DEBUG setting property fieldGrowthPolicy
  properties:DEBUG setting property margin
    uiparser:DEBUG push QFormLayout formLayout
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel label
    uiparser:DEBUG pop widget QLabel label
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property minimumSize
    uiparser:DEBUG push QComboBox cmbTemplate
    uiparser:DEBUG pop widget QComboBox cmbTemplate
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblLine1
    uiparser:DEBUG pop widget QLabel lblLine1
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property minimumSize
    uiparser:DEBUG push QTextEdit txtLine1
    uiparser:DEBUG pop widget QTextEdit txtLine1
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblLine2
    uiparser:DEBUG pop widget QLabel lblLine2
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property minimumSize
    uiparser:DEBUG push QTextEdit txtLine2
    uiparser:DEBUG pop widget QTextEdit txtLine2
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblLine3
    uiparser:DEBUG pop widget QLabel lblLine3
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property minimumSize
    uiparser:DEBUG push QTextEdit txtLine3
    uiparser:DEBUG pop widget QTextEdit txtLine3
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblLine4
    uiparser:DEBUG pop widget QLabel lblLine4
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property minimumSize
    uiparser:DEBUG push QTextEdit txtLine4
    uiparser:DEBUG pop widget QTextEdit txtLine4
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblLine5
    uiparser:DEBUG pop widget QLabel lblLine5
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property minimumSize
    uiparser:DEBUG push QTextEdit txtLine5
    uiparser:DEBUG pop widget QTextEdit txtLine5
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblFont
    uiparser:DEBUG pop widget QLabel lblFont
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property enabled
  properties:DEBUG setting property text
    uiparser:DEBUG push QPushButton btnFont
    uiparser:DEBUG pop widget QPushButton btnFont
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblTextColor
    uiparser:DEBUG pop widget QLabel lblTextColor
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property enabled
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property text
    uiparser:DEBUG push QPushButton btnFontColor
    uiparser:DEBUG pop widget QPushButton btnFontColor
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblBackColor
    uiparser:DEBUG pop widget QLabel lblBackColor
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property enabled
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property text
    uiparser:DEBUG push QPushButton btnBackgroundColor
    uiparser:DEBUG pop widget QPushButton btnBackgroundColor
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblAdvanced
    uiparser:DEBUG pop widget QLabel lblAdvanced
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property enabled
  properties:DEBUG setting property text
    uiparser:DEBUG push QPushButton btnAdvanced
    uiparser:DEBUG pop widget QPushButton btnAdvanced
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property minimumSize
    uiparser:DEBUG push QTextEdit txtLine6
    uiparser:DEBUG pop widget QTextEdit txtLine6
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblLine6
    uiparser:DEBUG pop widget QLabel lblLine6
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7f418e7923a8>
    uiparser:DEBUG pop layout QFormLayout formLayout
    uiparser:DEBUG pop widget QWidget widgetForm
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QSplitter object at 0x7f418e792168>
    uiparser:DEBUG pop widget QSplitter splitter
    uiparser:DEBUG new topwidget <windows.title_editor.TitleEditor object at 0x7f418e7b2f78>
    uiparser:DEBUG pop layout QGridLayout gridLayout
    uiparser:DEBUG pop widget TitleEditor Dialog
    uiparser:DEBUG new topwidget None
     ui_util:INFO Initializing UI for Dialog
     ui_util:INFO Failed to initialize an element on Dialog
```

Snippet from terminal just prior to crash. 

Ubuntu 14.04 LTS, BTW.

```
     ui_util:INFO Initializing UI for Dialog
     ui_util:INFO Failed to initialize an element on Dialog
title_editor:INFO Advanced title editor command: inkscape /home/jarl/.openshot_qt/title/temp.svg 
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/windows/title_editor.py", line 362, in btnFont_clicked
      logger:ERROR self.set_font_style()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/windows/title_editor.py", line 479, in set_font_style
      logger:ERROR ar[fs] = "font-style:" + self.font_style
      logger:ERROR TypeError
      logger:ERROR :
      logger:ERROR list indices must be integers, not NoneType

```

**Comment by olielvewen** [comment]
Hum looking the end of the output, I've a question.
Did are you using the font of the title editor or did are you using inkscape ? 
BTW I've just tested (but on Manjaro like I've seen that you are on 14.04) quickly and I can change it without any problem.

BTW Thanks a lot helping us  to rendering OpenShot 2.0 better than he was on the 1.4.3. (and he was so good) reporting bugs, new features,.....

**Comment by jarlarntzen** [comment]
![image](https://cloud.githubusercontent.com/assets/2108412/12413378/b519fe4e-be8e-11e5-91cf-f81015d15e92.png)

Actually, turns out changing the font works beautifully on OSX El Capitan. (I've tried several templates)
BTW: Thanks and likewise:)

**Comment by jarlarntzen** [comment]
@olielvewen I did only use the OpenShot title editor.

**Comment by jarlarntzen** [comment]
**Ubuntu 14.04 LTS**: Changing the font actually *does* work but for some reason, the font selector dialog keeps returning to the default Ubuntu Medium font whenever it's opened.
![image](https://cloud.githubusercontent.com/assets/2108412/12505537/111368ec-c0e8-11e5-8bec-3189774d0465.png)

**Comment by jarlarntzen** [comment]
**OSX El Capitan**: Here, the font dialog does remember the last font set the next time it is opened.

**Comment by jonoomph** [comment]
I see the font dialog initializing to the current font (Ubuntu medium 11), but I am able to change the font and it correctly applies to the Title. This is on Ubuntu 14.04.

**Comment by jarlarntzen** [comment]
Yes. Setting the font to, say, Times New Roman does work but when I open the dialog again, the font dialog is reset to Ubuntu Medium 11 and I have to select Times New Roman again for my next title. I would like for the dialog to stay at the last selected font. Thanks :)

**Comment by jreynojustin** [comment]
Hi @jarlarntzen,

It seems like from what you are saying you can switch font types correctly but prefer the existing font to be pre-selected when changing it in the dialogue. This would be an enhancement we'd need to look into. If you still want to have us look into this please reopen the issue. Otherwise because of the age of this post and the nature of its request I am closing the issue.
