### ISSUE TITLE
AppImage: Remove the Desktop Integration dialog

### ISSUE THREAD

**Issue by aoloe** [OpenShot/openshot-qt#3510]
When starting the OpenShot AppImage there is a dialog asking for Desktop Integration.

During my project I had to restart OpenShot very often and I was more and more bothered by it.

I asked in the AppImage chat and they told me that the script triggering this dialog should not be used anymore.

Would you mind removing the script?
The AppImage people can help you doing so if you ask in their irc channel on freenode : - )

**Comment by aoloe** [comment]
the issue is still there.

but, now, on my debian testing openshot's appimage does crashes...

```
Loaded modules from current directory: /tmp/.mount_US5Mj2/usr/bin
         app:INFO ------------------------------------------------
         app:INFO             Fri Nov 27 12:06:37 2020
         app:INFO               Starting new session
         app:ERROR OpenShotApp::Import Error: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 104, in <module>
    main()
  File "openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/tmp/.mount_US5Mj2/usr/bin/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_US5Mj2/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 28, in <module>
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 20, in swig_import_helper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 539, in _check_name_wrapper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1715, in load_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
ImportError: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items
         app:INFO             OpenShot's session ended
         app:INFO             Fri Nov 27 12:06:44 2020
         app:INFO ================================================
```

there are bigger problems around : - )
