### ISSUE TITLE
OpenShot v2.1.0 won't launch on OS X 10.8.5

### ISSUE THREAD

**Issue by simonrob** [OpenShot/openshot-qt#354]
OpenShot won't launch for me (the icon bounces then exits immediately). I'm running OS X 10.8.5.

Running launch-mac.sh directly gives the following errors (after all the dyld load lines):

```
Traceback (most recent call last):
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/openshot.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_openshot', [dirname(__file__)])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 296, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cx_Freeze-5.0-py3.5-macosx-10.6-intel.egg/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "openshot_qt/launch.py", line 53, in <module>
    from classes.app import OpenShotApp
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/classes/app.py", line 40, in <module>
    from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/openshot.py", line 28, in <module>
    _openshot = swig_import_helper()
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/openshot.py", line 20, in swig_import_helper
    import _openshot
ImportError: dlopen(/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/python3.5/_openshot.so, 2): Symbol not found: ___sincos_stret
  Referenced from: /Applications/OpenShot Video Editor.app/Contents/MacOS/libopenshot-audio.3.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/OpenShot Video Editor.app/Contents/MacOS/libopenshot-audio.3.dylib

```

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.

**Comment by neps-in** [comment]
Yea i am also facing this issue.

**Comment by phreaknerd** [comment]
Still an issue.

**Comment by JacksonRG** [comment]
We are now on version 2.5, and nearing the release of 2.6. Versions 2.1 and 2.2 are no longer supported, and I can only recommend updating to 2.5, or the [daily build](https://www.openshot.org/download/)
