### ISSUE TITLE
Undefined symbol error throws exception - app won't start

### ISSUE THREAD

**Issue by sangemaru** [OpenShot/openshot-qt#3615]
**Describe the bug:**

**Steps to reproduce the behavior:**
1. Install the stable PPA build
2. run openshot-qt
3. See error

**Expected behavior:**
The app should start

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Exception / Stacktrace:**
openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Mon Jul 20 11:42:27 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.1-dev2)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1-dev2
         app:INFO libopenshot version: 0.2.5-dev2
         app:INFO platform: Linux-5.4.0-40-generic-x86_64-with-glibc2.29
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.8.2
         app:INFO qt5 version: 5.15.0
         app:INFO pyqt5 version: 5.15.0
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.5.1.dev2', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 220, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 45, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 42, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5

**Comment by sangemaru** [comment]
Note that downloading and running the AppImage works fine so far.

**Comment by dinilbose** [comment]
Same error for me too

**Comment by Slavenin** [comment]
after update pyQt to the latest version, I have this bug
```
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Fri Nov 13 10:32:34 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.1-dev2)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1-dev2
         app:INFO libopenshot version: 0.2.5-dev2
         app:INFO platform: Linux-5.4.0-53-generic-x86_64-with-glibc2.29
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.8.5
         app:INFO qt5 version: 5.15.1
         app:INFO pyqt5 version: 5.15.1
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['ru-RU']
    language:INFO LANG Environment Variable: ru_RU.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.5.1.dev2', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 220, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 45, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 42, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *failed-recording-exception*: Control/space characters not allowed (key=b':1:Linux-2.5.1-dev2-ImportError: /lib/x86_64-linux-g')
^C      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.8/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
      logger:ERROR lock.acquire()
      logger:ERROR KeyboardInterrupt
      logger:ERROR :
         app:INFO             OpenShot's session ended            
         app:INFO             Fri Nov 13 10:32:46 2020            
         app:INFO ================================================

```

**Comment by ferdnyc** [comment]
@Slavenin 

When you updated PyQt, did you also update PyQtWebKit? And the underlying Qt5 and versions as well? 

AFAICT the exception being thrown appears to show a version mismatch between the PyQt and Qt components themselves. It's not coming from the OpenShot code, it's being thrown the moment we do a `from PyQt5.QtWebKitWidgets import QWebView`. If you were to run `python3` in a terminal and enter that same line of code, you'd presumably get the same traceback.

Looks to me like updating your PyQt installation broke it.

QtWebKit is no longer officially supported in Qt (not since Qt 5.6), but it's still being developed as an external project and most distros still ship a build of it. However, if you updated the underlying Qt5, that QtWebKit package will need to be rebuilt for the new version of Qt.

The other option is to switch over to our daily PPA builds, where we've replaced QtWebKit with QtWebEngine (still supported by current Qt5).

**Comment by Mohammad-Mohsen** [comment]
Having same error, reinstalled QtWebKit and nothing changed.
But I can launch openshot with `sudo openshot-qt` ; but it will show this error:
![image](https://user-images.githubusercontent.com/52295823/113626135-04c18c80-9677-11eb-99f3-18eefbbac499.png)
It must be a permission error and unrevelant to this issue; but Why root permissions workaround this problem?
