### ISSUE TITLE
TypeError: metaclass conflict TimelineWebView

### ISSUE THREAD

**Issue by ChillerDragon** [OpenShot/openshot-qt#3683]
openshot-qt version: https://github.com/OpenShot/openshot-qt/commit/3eb04bf527280c5adbdacef191b4218c63113f2c
libopenshot version: https://github.com/OpenShot/libopenshot/commit/f71051e8f1add0b893ffaa9a799625017978e7f8
libopenshot-audio version: https://github.com/OpenShot/libopenshot-audio/commit/7b76f1de9c6a111f1aba2979eeb4a847a93aeeb4

```
uname -a
Linux debian 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```

```
Loaded modules from: /home/chiller/Desktop/git-extern/openshot-qt/src
         app:INFO ------------------------------------------------
         app:INFO             Wed Aug 26 17:21:17 2020
         app:INFO               Starting new session
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.1-dev2)
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1-dev2
         app:INFO libopenshot version: 0.2.5-dev2
         app:INFO platform: Linux-4.19.0-10-amd64-x86_64-with-debian-10.5
         app:INFO processor:
         app:INFO machine: x86_64
         app:INFO python version: 3.7.3
         app:INFO qt5 version: 5.11.3
         app:INFO pyqt5 version: 5.11.3
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable:
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to /home/chiller/Desktop/git-extern/openshot-qt/src/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "src/launch.py", line 143, in <module>
    main()
  File "src/launch.py", line 136, in main
    app = OpenShotApp(argv)
  File "/home/chiller/Desktop/git-extern/openshot-qt/src/classes/app.py", line 242, in __init__
    from windows.main_window import MainWindow
  File "/home/chiller/Desktop/git-extern/openshot-qt/src/windows/main_window.py", line 45, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/home/chiller/Desktop/git-extern/openshot-qt/src/windows/views/timeline_webview.py", line 154, in <module>
    class TimelineWebView(TimelineMixin, updates.UpdateInterface):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by ChillerDragon** [comment]
Oh okay now I understand this is a missing dependency issue but https://github.com/OpenShot/openshot-qt/commit/d07488d5eb3c29a6a6d1058baed9bec7a41ae538 makes it harder to understand. Before this change the error message looked like this:

```
Loaded modules from: /home/chiller/Desktop/git-extern/openshot-qt/src
Traceback (most recent call last):
  File "src/launch.py", line 143, in <module>
    main()
  File "src/launch.py", line 131, in main
    from classes.app import OpenShotApp
  File "/home/chiller/Desktop/git-extern/openshot-qt/src/classes/app.py", line 43, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

And the fix in my case on debian 10 was:

```
sudo apt install python3-pyqt5.qtwebengine
```

So its not a error but hard to debug the missing dependency. I added the dependency to linux libopenshot wiki so I guess this issue is closed in https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions/0f7ee4550807f609a6e925558d5b536b0f7618b1

**Comment by ferdnyc** [comment]
Reopening, because we really should raise a _useful_ error if **both** web backends are missing. As you say, "ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'" is clear. But now we're hiding those exceptions.
