### ISSUE TITLE
Unable to use Dissolving Text in Animated Title

### ISSUE THREAD

**Issue by TotallyClueless** [OpenShot/openshot-qt#3730]
**Describe the bug**
Unable to use Dissolving Text in Animated Title

**Steps to reproduce the behavior:**
1. Go to 'Title'
2. Click on 'Animated Title'
3. Scroll down to 'Dissolving Text slide'
4. Unable to render the slide

**Expected behavior**
I expected to be able to render the title with Blender. Although the daily build is an improvement on my original download as it refused to even recognise that I had updated  preferences with the path to Blender (C:/Program Files/Blender Foundation/Blender 2.90/blender.exe) Now I just get the spinning blue wheel of tedium and can't click on render

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1600468920-66121bfe-12ddb3df-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ks126xipwxgh8chgeywxia4q28sdkka9/openshot-qt.zip) (145 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/ks126xipwxgh8chgeywxia4q28sdkka9/libopenshot.zip) (112 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by TotallyClueless** [comment]
Just to add some more info to the above. I looked in the openshot-qt log file and saw that two of the entries:

blender_listview:INFO Checking Blender version, command: 'C:/Program Files/Blender Foundation/Blender 2.90/blender.exe' -v
blender_listview:ERROR Worker exception: No Blender version detected in output

I do have Blender 2.90 installed in that location and if I run C:/Program Files/Blender Foundation/Blender 2.90/blender.exe -v from a command prompt I get the below:

C:\Program Files\Blender Foundation\Blender 2.90>blender.exe -v
Blender 2.90.0
        build date: 2020-08-31
        build time: 10:00:13
        build commit date: 2020-08-31
        build commit time: 11:26
        build hash: 0330d1af29c0
        build platform: Windows
        build type: Release
        build c flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /nologo /J /Gd /MP /bigobj -openmp
        build c++ flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /nologo /J /Gd /MP /EHsc /bigobj /permissive- /Zc:twoPhase- -openmp /std:c++17
        build link flags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152 /ignore:4049 /ignore:4217 /ignore:4221
        build system: CMake
Error: Not freed memory blocks: 371, total unfreed memory 0.135872 MB

Hopefully that provides you with some more pertinent information

**Comment by TotallyClueless** [comment]
The dissolve.blend python module fails in Blender 2.90 as do the others so I'm guessing that OpenShot is not currently compatible with the latest version of Blender and they will need a rewrite to work. I tried to see if I could sort out the Python script/module for dissolve but my Python experience is limited to using it this afternoon so I was destined for failure! 

Here's my system console output from Blender if that helps anyone with better Python skills than my non-existent ones:

Read prefs: C:\Users\ilike\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.90\2.90\python
Read blend: C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend
Error, region type 5 missing in - name:"Text", id:9
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 7, in <module>
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "view_align" unrecognized
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 9, in <module>
AttributeError: 'bpy_prop_collection' object has no attribute 'active'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 13, in <module>
AttributeError: 'bpy_prop_collection' object has no attribute 'active'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 13, in <module>
AttributeError: 'bpy_prop_collection' object has no attribute 'active'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 13, in <module>
AttributeError: 'bpy_prop_collection' object has no attribute 'active'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 13, in <module>
AttributeError: 'bpy_prop_collection' object has no attribute 'active'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 15, in <module>
AttributeError: 'bpy_prop_collection' object has no attribute 'active'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 18, in <module>
AttributeError: bpy_prop_collection: attribute "active" not found
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 19, in <module>
AttributeError: 'Object' object has no attribute 'select'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 19, in <module>
AttributeError: 'Object' object has no attribute 'select'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 19, in <module>
AttributeError: 'Object' object has no attribute 'select_set'
Error: Python script failed, check the message in the system console

Info: Deleted 1 object(s)
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 26, in <module>
KeyError: 'bpy_prop_collection[key]: key "TurbulenceField" not found'
Error: Python script failed, check the message in the system console

Info: Deleted 1 object(s)
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\blender\blend\dissolve.blend\dissolve", line 26, in <module>
KeyError: 'bpy_prop_collection[key]: key "TurbulenceField" not found'
Error: Python script failed, check the message in the system console

Error, region type 5 missing in - name:"Text", id:9

**Comment by TotallyClueless** [comment]
Uninstalled OpenShot so no longer an issue
