### ISSUE TITLE
NVENC:Error while writing raw video frame

### ISSUE THREAD

**Issue by stratus-ss** [OpenShot/openshot-qt#3731]
**Describe the bug:**
When attempting to export video with the following settings:

![image](https://user-images.githubusercontent.com/8162705/93786830-bd554080-fbfd-11ea-9878-fb0ad2db50e6.png)

The editor throws the following error:
![image](https://user-images.githubusercontent.com/8162705/93787175-276de580-fbfe-11ea-94e8-b4ecae24a97e.png)

```
Sorry, there was an error exporting your video: 
Error while writing raw video frame
```

**Steps to reproduce the behavior:**
1. Create project
2. Add video to time line
3. Click on the render button
4. Select target of NVENC
5. See error

**Expected behavior:**
Video renders with the GPU

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Arch Linux

```
System:
 Kernel: 5.4.60-1-lts x86_64 bits: 64 
  Desktop: GNOME 3.36.5 Distro: Arch Linux 
Machine:
  Type: Desktop System: ASUS product: All Series v: N/A serial: N/A 
  Mobo: ASUSTeK model: Z97-WS v: Rev 1.xx serial: 140525546300294 
  UEFI [Legacy]: American Megatrends v: 2403 date: 06/18/2015 
Memory:
  RAM: total: 31.31 GiB used: 9.71 GiB (31.0%) 
CPU:
  Info: Quad Core Intel Core i7-4790K [MT MCP] speed: 1185 MHz 
  min/max: 800/4400 MHz 
Graphics:
  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 450.66 
  Display: server: X.Org 1.20.8 driver: nvidia unloaded: modesetting,vesa 
  resolution: 1: 1920x1080~60Hz 2: 2560x1440~100Hz 3: 1080x1920~60Hz 
  4: 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 970/PCI
e/SSE2 v: 4.6.0 NVIDIA 450.66 
Network:
  Device-1: Intel Ethernet I218-LM driver: e1000e 
  Device-2: Intel I210 Gigabit Network driver: igb 
Drives:
  Local Storage: total: 2.74 TiB used: 1.62 TiB (59.0%) 
  ID-1: /dev/sda vendor: Silicon Power model: SPCC Solid State Disk 
  size: 119.24 GiB 
  ID-2: /dev/sdb vendor: Intel model: SSDSC2BW120A4 size: 111.79 GiB 
  ID-3: /dev/sdc vendor: Seagate model: ST32000542AS size: 1.82 TiB 
  ID-4: /dev/sdd vendor: Crucial model: CT512MX100SSD1 size: 476.94 GiB 
  ID-5: /dev/sde vendor: SanDisk model: X400 M.2 2280 256GB size: 238.47 GiB 


Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc1       1.9T  1.2T  710G  62% /blu_rays
```

**Log Files:**
[openshot-qt.log.gz](https://github.com/OpenShot/openshot-qt/files/5256494/openshot-qt.log.gz)

**Comment by salexan2001** [comment]
Unfortunately I'm also affected by this issue and it seems to persist with kernel 6.1.27-1-lts (ArchLinux).

In my case encoding using NVENC directly with ffmpeg works absolutely fine, e.g.:

```
ffmpeg -i input.mp4 -c:v h264_nvenc -rc constqp -qp 28 output.mp4
```

Can we reopen this issue? How can I help to solve it?

**Comment by Colorjet3** [comment]
Hello @salexan2001 Which version of Openshot are you running?  I would like you to try and run v3.1.1 (either via PPA installation and/or the AppImage).

PPA Clean Installation:
Clean Installation - Stable PPA:  
# sudo apt purge openshot-qt
# sudo apt autoremove
# sudo add-apt-repository ppa:openshot.developers/ppa
# sudo apt update
# sudo apt install openshot-qt


AppImage:
1.  Go to openshot.org
2.  Click on DOWNLOAD v3.1.1

Please don't run them in Parallel as they share the same /home/username/.openshot_qt folder.

If the problem persists then I will ask the lead developer to look into this issue.

**Comment by salexan2001** [comment]
Thanks, I'm running v3.1.1 already (on ArchLinux, so using the official repositories via pacman):

```
$ pacman -Qi openshot 
Name                     : openshot
Version                  : 3.1.1-1
Beschreibung             : An award-winning free and open-source video editor
```

(https://archlinux.org/packages/extra/any/openshot/)

I can try the AppImage later, but it should not make a difference, right?

![screenshot_openshot_2023-05-23 14-57-07](https://github.com/OpenShot/openshot-qt/assets/10830207/8ba5cfaf-ab89-4625-8dd9-fe441730f628)

**Comment by Colorjet3** [comment]
Yeah, I don't think the AppImage will make a difference but try it any way just to confirm.  I am going to assign this to the lead developer to look into.

**Comment by salexan2001** [comment]
I also tried the AppImage, but it does not seem to be compatible with my system due to incompatible versions of glibc:

```
$ ./OpenShot-v3.1.1-x86_64.AppImage 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShxmGHp7/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libharfbuzz.so.0)
```

```
$ pacman -Qi glibc | head
Name                     : glibc
Version                  : 2.37-3
```

But the version from the official repositories is working and up to date, so this is no real issue for me.

**Comment by Borketh** [comment]
I'm also having this issue with 3.1.1
also of note is that it segfaults when trying to use VAAPI instead.

**Comment by shashanknimje** [comment]
Same issue here with oepnshot version 3.1.1 (libopenshot: 0.3.2) trying to render using NVENC MP4 (h.264 nv) running on Arch Linux with proprietary Nvidia drivers version: 535.104.05.

**Comment by jonoomph** [comment]
@salexan2001 The GLIBC error has been fixed in the latest **daily build** AppImage: https://www.openshot.org/download/#daily
