### ISSUE TITLE
Qt 5.15 + Python 3.8: crash at startup

### ISSUE THREAD

**Issue by eszlari** [OpenShot/openshot-qt#3750]
https://github.com/flathub/org.openshot.OpenShot/pull/11

I'm trying to move the flatpak from Qt 5.14 + Python 3.7 to Qt 5.15 + Python 3.8, but the app crashes at startup:

```
         app:INFO ------------------------------------------------
         app:INFO             Wed Oct  7 01:07:28 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
[Detaching after fork from child process 11]
         app:INFO platform: Linux-5.4.0-48-generic-x86_64-with-glibc2.2.5
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.8.5
         app:INFO qt5 version: 5.15.1
         app:INFO pyqt5 version: 5.15.1
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['de-DE']
    language:INFO LANG Environment Variable: de_DE.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
[New Thread 0x7fffe2205700 (LWP 12)]
[New Thread 0x7fffe1a04700 (LWP 13)]
[New Thread 0x7fffe1203700 (LWP 14)]
[New Thread 0x7fffe0a02700 (LWP 15)]
[New Thread 0x7fffdbfff700 (LWP 16)]
         app:INFO Setting font to /app/lib/python3.8/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
[New Thread 0x7fffcfc33700 (LWP 17)]
[New Thread 0x7fffcf432700 (LWP 18)]
[Thread 0x7fffcf432700 (LWP 18) exited]
[Thread 0x7fffcfc33700 (LWP 17) exited]
[New Thread 0x7fffcf432700 (LWP 19)]
[Thread 0x7fffcf432700 (LWP 19) exited]
[New Thread 0x7fffcf432700 (LWP 20)]
[New Thread 0x7fffcfc33700 (LWP 21)]
[New Thread 0x7fffceb85700 (LWP 22)]
[New Thread 0x7fffce384700 (LWP 23)]
[New Thread 0x7fffcdb83700 (LWP 24)]
[New Thread 0x7fffcd382700 (LWP 25)]
[New Thread 0x7fffccb81700 (LWP 26)]
[New Thread 0x7fffaffff700 (LWP 27)]
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
[New Thread 0x7fffaedee700 (LWP 28)]
[New Thread 0x7fffae5ed700 (LWP 29)]
[New Thread 0x7fffaddec700 (LWP 30)]
[New Thread 0x7fff5f7ff700 (LWP 31)]
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
effects_model:INFO updating effects model.
properties_model:INFO updating clip properties model.
transition_model:INFO updating transitions model.
 files_model:INFO updating files model.
     version:INFO Found current version: {"openshot_version": "2.5.1"}
[Thread 0x7fffaedee700 (LWP 28) exited]
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
[New Thread 0x7fffaedee700 (LWP 32)]
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
[New Thread 0x7fff5e7ff700 (LWP 33)]

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
_PyErr_FormatVFromCause (vargs=0x7fffffffc960, format=0x7ffff7ef0fd8 "%R returned a result with an error set", exception=0x7ffff7f78e60 <_PyExc_SystemError>, tstate=0x555555580e80) at ../Python/errors.c:508
508         Py_DECREF(exc);
(gdb) bt
#0  _PyErr_FormatVFromCause (vargs=0x7fffffffc960, format=0x7ffff7ef0fd8 "%R returned a result with an error set", exception=0x7ffff7f78e60 <_PyExc_SystemError>, tstate=0x555555580e80) at ../Python/errors.c:508
#1  _PyErr_FormatFromCause (exception=0x7ffff7f78e60 <_PyExc_SystemError>, format=format@entry=0x7ffff7ef0fd8 "%R returned a result with an error set") at ../Python/errors.c:533
#2  0x00007ffff7d1b19a in _Py_CheckFunctionResult (callable=callable@entry=0x7ffff78a0cc0, result=<optimized out>, where=where@entry=0x0) at ../Objects/call.c:51
#3  0x00007ffff7cde343 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff466a1f8, callable=0x7ffff78a0cc0) at ../Include/cpython/abstract.h:128
#4  call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x555555580e80) at ../Python/ceval.c:4963
#5  _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3486
#6  0x00007ffff7dedc04 in _PyEval_EvalCodeWithName
    (_co=<optimized out>, globals=globals@entry=0x7fffea660800, locals=locals@entry=0x0, args=<optimized out>, argcount=1, kwnames=0x0, kwargs=0x7fffe991d7b0, kwcount=0, kwstep=1, defs=0x7fffea6174d8, defcount=2, kwdefs=0x0, closure=0x0, name=0x7ffff743f630, qualname=0x7ffff743f630) at ../Python/ceval.c:4298
#7  0x00007ffff7deecf1 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:435
#8  0x00007ffff7cde3db in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fffe991d7a8, callable=0x7fffea616ca0) at ../Include/cpython/abstract.h:127
#9  call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x555555580e80) at ../Python/ceval.c:4963
#10 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3469
#11 0x00007ffff7cd6f13 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=2, globals=<optimized out>) at ../Objects/call.c:283
#12 0x00007ffff7cde336 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fffe22fc3d8, callable=0x7fffea62dee0) at ../Include/cpython/abstract.h:127
#13 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x555555580e80) at ../Python/ceval.c:4963
#14 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3486
#15 0x00007ffff7dedc04 in _PyEval_EvalCodeWithName
    (_co=<optimized out>, globals=globals@entry=0x7fffe229afc0, locals=locals@entry=0x0, args=<optimized out>, argcount=2, kwnames=0x0, kwargs=0x7fffffffd0d0, kwcount=0, kwstep=1, defs=0x7fffe22c7ec8, defcount=1, kwdefs=0x0, closure=0x0, name=0x7ffff788b530, qualname=0x7fffe00874e0) at ../Python/ceval.c:4298
#16 0x00007ffff7deecf1 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:435
#17 0x00007ffff7d4bef7 in _PyObject_FastCallDict (callable=callable@entry=0x7fffcfc34ca0, args=args@entry=0x7fffffffd0c0, nargsf=nargsf@entry=2, kwargs=kwargs@entry=0x0) at ../Objects/call.c:96
#18 0x00007ffff7d4c06d in _PyObject_Call_Prepend (callable=callable@entry=0x7fffcfc34ca0, obj=0x7fffffffd0c0, obj@entry=0x7fffe22f9ca0, args=args@entry=0x7ffff745c880, kwargs=kwargs@entry=0x0) at ../Objects/call.c:887
#19 0x00007ffff7d60e71 in slot_tp_init (self=0x7fffe22f9ca0, args=0x7ffff745c880, kwds=0x0) at ../Objects/typeobject.c:6787
#20 0x00007ffff7d610e5 in type_call (type=<optimized out>, args=0x7ffff745c880, kwds=0x0) at ../Objects/typeobject.c:994
#21 0x00007ffff7d4bcb7 in _PyObject_MakeTpCall (callable=callable@entry=0x5555559e90d0, args=args@entry=0x5555555f8a20, nargs=<optimized out>, keywords=keywords@entry=0x0) at ../Objects/call.c:159
#22 0x00007ffff7cdda57 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x5555555f8a20, callable=0x5555559e90d0) at ../Include/cpython/abstract.h:125
#23 _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x5555555f8a20, callable=0x5555559e90d0) at ../Include/cpython/abstract.h:115
#24 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x555555580e80) at ../Python/ceval.c:4963
#25 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3500
#26 0x00007ffff7dedc04 in _PyEval_EvalCodeWithName
    (_co=<optimized out>, globals=globals@entry=0x7ffff463ed00, locals=locals@entry=0x0, args=<optimized out>, argcount=2, kwnames=0x0, kwargs=0x7fffffffd4a0, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x7ffff463ec00, closure=0x0, name=0x7ffff788b530, qualname=0x7ffff4640a80) at ../Python/ceval.c:4298
#27 0x00007ffff7deecf1 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:435
#28 0x00007ffff7d4bef7 in _PyObject_FastCallDict (callable=callable@entry=0x7ffff36504c0, args=args@entry=0x7fffffffd490, nargsf=nargsf@entry=2, kwargs=kwargs@entry=0x0) at ../Objects/call.c:96
#29 0x00007ffff7d4c06d in _PyObject_Call_Prepend (callable=callable@entry=0x7ffff36504c0, obj=0x7fffffffd490, obj@entry=0x7ffff467a5e0, args=args@entry=0x7ffff77bcac0, kwargs=kwargs@entry=0x0) at ../Objects/call.c:887
#30 0x00007ffff7d60e71 in slot_tp_init (self=0x7ffff467a5e0, args=0x7ffff77bcac0, kwds=0x0) at ../Objects/typeobject.c:6787
#31 0x00007ffff7d610e5 in type_call (type=<optimized out>, args=0x7ffff77bcac0, kwds=0x0) at ../Objects/typeobject.c:994
#32 0x00007ffff7d4bcb7 in _PyObject_MakeTpCall (callable=callable@entry=0x555555739de0, args=args@entry=0x7ffff7440bf0, nargs=<optimized out>, keywords=keywords@entry=0x0) at ../Objects/call.c:159
#33 0x00007ffff7cdda57 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff7440bf0, callable=0x555555739de0) at ../Include/cpython/abstract.h:125
#34 _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff7440bf0, callable=0x555555739de0) at ../Include/cpython/abstract.h:115
#35 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x555555580e80) at ../Python/ceval.c:4963
#36 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3500
#37 0x00007ffff7cd6f13 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>) at ../Objects/call.c:283
#38 0x00007ffff7cdd9eb in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff77d75c0, callable=0x7ffff75158b0) at ../Include/cpython/abstract.h:127
#39 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x555555580e80) at ../Python/ceval.c:4963
#40 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3500
#41 0x00007ffff7dedc04 in _PyEval_EvalCodeWithName
    (_co=_co@entry=0x7ffff76a20e0, globals=globals@entry=0x7ffff7839800, locals=locals@entry=0x7ffff7839800, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at ../Python/ceval.c:4298
#42 0x00007ffff7dedefe in PyEval_EvalCodeEx
    (_co=_co@entry=0x7ffff76a20e0, globals=globals@entry=0x7ffff7839800, locals=locals@entry=0x7ffff7839800, args=args@entry=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:4327
#43 0x00007ffff7dedf2b in PyEval_EvalCode (co=co@entry=0x7ffff76a20e0, globals=globals@entry=0x7ffff7839800, locals=locals@entry=0x7ffff7839800) at ../Python/ceval.c:718
#44 0x00007ffff7dee337 in run_eval_code_obj (co=co@entry=0x7ffff76a20e0, globals=globals@entry=0x7ffff7839800, locals=locals@entry=0x7ffff7839800) at ../Python/pythonrun.c:1125
#45 0x00007ffff7e58a31 in run_mod
--Type <RET> for more, q to quit, c to continue without paging--
    (mod=mod@entry=0x555555636e78, filename=filename@entry=0x7ffff78073f0, globals=globals@entry=0x7ffff7839800, locals=locals@entry=0x7ffff7839800, flags=flags@entry=0x7fffffffdaa8, arena=arena@entry=0x7ffff779a910)
    at ../Python/pythonrun.c:1147
#46 0x00007ffff7e595f2 in PyRun_FileExFlags
    (fp=fp@entry=0x555555559340, filename_str=filename_str@entry=0x7ffff7808d10 "/app/bin/openshot-qt", start=start@entry=257, globals=globals@entry=0x7ffff7839800, locals=locals@entry=0x7ffff7839800, closeit=closeit@entry=1, flags=0x7fffffffdaa8) at ../Python/pythonrun.c:1063
#47 0x00007ffff7e691bb in PyRun_SimpleFileExFlags (fp=fp@entry=0x555555559340, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7fffffffdaa8) at ../Python/pythonrun.c:428
#48 0x00007ffff7e6968c in PyRun_AnyFileExFlags (fp=fp@entry=0x555555559340, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7fffffffdaa8) at ../Python/pythonrun.c:86
#49 0x00007ffff7e6c390 in pymain_run_file (cf=0x7fffffffdaa8, config=0x555555580210) at ../Modules/main.c:381
#50 pymain_run_python (exitcode=0x7fffffffda9c) at ../Modules/main.c:606
#51 Py_RunMain () at ../Modules/main.c:685
#52 0x00007ffff7e6c886 in pymain_main (args=0x7fffffffdba0) at ../Modules/main.c:715
#53 Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at ../Modules/main.c:739
#54 0x00007ffff7ac1022 in __libc_start_main (main=0x555555555050 <main>, argc=2, argv=0x7fffffffdd08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcf8) at ../csu/libc-start.c:308
#55 0x000055555555508e in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by eszlari** [comment]
After updating all python dependencies, it now works.
