### ISSUE TITLE
Openshot 2.5.1 doesn't start on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by intelliant01** [OpenShot/openshot-qt#3772]
**Describe the bug:**
Openshot doesn't start at all on Ubuntu 20.04.1 arm64 system.

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Ubuntu 20.04.1

**Exception / Stacktrace:**
This is the error when started via terminal - 
```
$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Sat Oct 17 14:26:51 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.1-dev2)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1-dev2
     metrics:ERROR Error determining OS version in metrics.py
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 11, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.5.1.dev2', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
      logger:ERROR app = OpenShotApp(argv)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 115, in __init__
      logger:ERROR from classes import exceptions
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/exceptions.py", line 30, in <module>
      logger:ERROR from classes.metrics import track_exception_stacktrace
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/metrics.py", line 83, in <module>
      logger:ERROR "cd1": openshot.OPENSHOT_VERSION_FULL,  # Dimension 1: libopenshot version
      logger:ERROR AttributeError
      logger:ERROR :
      logger:ERROR module 'openshot' has no attribute 'OPENSHOT_VERSION_FULL'
         app:INFO             OpenShot's session ended            
         app:INFO             Sat Oct 17 14:26:52 2020            
         app:INFO ================================================
```

Taking a hint from #3220 tried installing libopenshot19 but there isn't an arm64 package available.

These are the packages installed -

```
$ dpkg -l |grep openshot
ii  libopenshot-audio6:arm64                      0.1.7+dfsg1-1                               arm64        library for high-quality audio editing
ii  libopenshot16:arm64                           0.2.2+dfsg1-1ubuntu3                        arm64        library for high-quality video editing
ii  openshot-qt                                   2.5.1+dfsg2+1218+202003032149~ubuntu20.04.1 all          OpenShot video editor
ii  python3-openshot                              0.2.2+dfsg1-1ubuntu3                        arm64        OpenShot video library bindings for Python 3

```

**Comment by jonoomph** [comment]
Are you using a PPA, or the official repository for Ubuntu 20.04? Also, have you tried our latest daily build *.AppImage? I would be curious how that works as well: https://www.openshot.org/download/#daily. 

Essentially, the error you pasted means that libopenshot was found, but it appears to be an older version without the OPENSHOT_VERSION_FULL attribute. That attribute was added to libopenshot in July, 2019... so a while ago. This means your libopenshot is very old and needs to be updated.

**Comment by jonoomph** [comment]
But I bet the AppImage works fine. :+1:

**Comment by intelliant01** [comment]
@jonoomph I have tried both approaches - official build for Ubuntu 20.04 and the PPA as given at  https://www.openshot.org/ppa/

I could not spot an appimage for arm64. Can you pls guide me with a link to the same?

As also identified by you, it is the missing libopenshot19 for arm64 that I am looking for.

**Comment by pleshevskiy** [comment]
@intelliant01 I've just ran into this. Need to uninstall old openshot packages and install from ppa.

```bash
sudo apt purge openshot-qt libopenshot16:amd64 libopenshot-audio6:amd64 python3-openshot
sudo apt install openshot-qt
```
