### ISSUE TITLE
Python error on startup of v2.5.1

### ISSUE THREAD

**Issue by DocSalvager** [OpenShot/openshot-qt#3807]
**Describe the bug:**
NOTE:  Openshot 2.4.4 is running on this system

Tried to run Openshot 2.5.1...

**Steps to reproduce the behavior:**
1. Downloaded OpenShot-v2.5.1-x86_64.AppImage
2. Moved to /opt/openshot directory
3. chmod +x Open*
4. ln -s OpenShot-v2.5.1-x86_64.AppImage  openshot
5. ...
 alpha@LX02:/opt/openshot  openshot
zenity, kdialog, Xdialog missing. Skipping ./bin//openshot-qt.wrapper.
Loaded modules from current directory: /tmp/.mount_bS0oBk/usr/bin
         app:INFO ------------------------------------------------
         app:INFO             Thu Oct 29 09:58:04 2020            
         app:INFO               Starting new session              
         app:ERROR OpenShotApp::Import Error: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 104, in <module>
    main()
  File "openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/tmp/.mount_bS0oBk/usr/bin/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_bS0oBk/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 28, in <module>
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 20, in swig_import_helper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 539, in _check_name_wrapper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1715, in load_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
ImportError: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items
         app:INFO             OpenShot's session ended            
         app:INFO             Thu Oct 29 09:58:39 2020            
         app:INFO ================================================

**Expected behavior:**
Expected to be presented with OpenShot window similar to v2.4.4.

**System Details:**
- OpenShot Version [e.g. 2.5.1]: {{ log_context.openshot_qt_version }}
- Operating System / Distro:... (from v2.4.4 startup)
zenity, kdialog, Xdialog missing. Skipping ./bin//openshot-qt.wrapper.
Loaded modules from current directory: /tmp/.mount_BAy8Ws/usr/bin
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.4)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.4
         app:INFO libopenshot version: 0.2.3
         app:INFO platform: Linux-4.9.87-antix.1-amd64-smp-x86_64-with-antiX-17.1-stretch
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.4.3
         app:INFO qt5 version: 5.2.1
         app:INFO pyqt5 version: 5.2.1
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).
[openshot_qt-2.5.1-crash.tar.gz](https://github.com/OpenShot/openshot-qt/files/5459240/openshot_qt-2.5.1-crash.tar.gz)

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by DocSalvager** [comment]
Looks like some problem with the libgobject 'g_uri_ref' function.

Downloaded and tried to launch latest dev version and it failed too with this...

 alpha@LX02:~  /opt/openshot/OpenShot-v2.5.1-dev2-1604017827-896b3073-2cb4eeff-x86_64.AppImage
Copying icon thumbnails to cache
ICONFILE = /home/alpha/.cache/thumbnails/normal/849a3e7ab4e6f070fbb01d5839fb0829.png
zenity, kdialog, Xdialog missing. Skipping ./bin//openshot-qt-launch.wrapper.
Loaded modules from: /tmp/.mount_haehLA/usr/bin
INFO app: ------------------------------------------------
INFO app:             Fri Oct 30 07:29:08 2020            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 14, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_haehLA/usr/bin/classes/app.py", line 87, in __init__
    from classes import (
  File "/tmp/.mount_haehLA/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 17, in <module>
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 16, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ImportError: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 14, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "openshot_qt/launch.py", line 147, in <module>
    main()
  File "openshot_qt/launch.py", line 140, in main
    app = OpenShotApp(argv)
  File "/tmp/.mount_haehLA/usr/bin/classes/app.py", line 87, in __init__
    from classes import (
  File "/tmp/.mount_haehLA/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 17, in <module>
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 16, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ImportError: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref
INFO app:             OpenShot's session ended            
INFO app:             Fri Oct 30 07:29:14 2020            
INFO app: ================================================

**Comment by ferdnyc** [comment]
@DocSalvager 

Hmm, thanks for the report. We've been excluding `libgobject-2.0.so.0` from our packaging for quite some time now, as recommended by [the pkg2appimage exclusion list](https://github.com/AppImage/pkg2appimage/blob/master/excludelist)... but we _are_ bundling `libgio-2.0.so.0` which is also on their list and is linked with `libgobject`. I wonder if that's where we're getting ourselves into trouble? The fact that the symbol in question is `g_uri_ref` makes me think that's probably the case. (We're bundling `libgmodule` also, but that's not linked with either `libgobject` or `libgio`... though `libgio-2.0.so.0` is linked with _it_ as well.)

`libgio` and `libgmodule` are all part of glib, same as `libgobject`, and I'd think any Linux system can be trusted to have those available. Perhaps the best approach is to exclude all of them.

**Comment by ferdnyc** [comment]
@DocSalvager 

Sorry for the delay. This AppImage build:
[OpenShot-v2.5.1-dev2-no-glib-1605133643-b910d2f6-2cb4eeff-x86_64.AppImage](https://drive.google.com/file/d/1S1cOT2MTTKEB1sijZHWfxZMmnl9Qjnmf/view?usp=sharing)
has all of the glib components excluded from bundling. Would you be able to test and let us know if it solves the launch errors on your system?

**Comment by phelix001** [comment]
Can't run .2.5.1-dev2 appimage failed on Ubuntu 20.10, running 5.9.8;
OpenShot-v2.5.1-dev2-no-glib-1605133643-b910d2f6-2cb4eeff-x86_64.AppImage

~/Downloads$ ./OpenShot-v2.5.1-dev2-no-glib-1605133643-b910d2f6-2cb4eeff-x86_64.AppImage 
Copying icon thumbnails to cache
ICONFILE = /home/phelix/.cache/thumbnails/normal/1408610efde709eefa33778e99e08648.png
Loaded modules from: /tmp/.mount_ER5aHk/usr/bin
INFO app: ------------------------------------------------
INFO app:             Thu Nov 12 09:57:41 2020            
INFO app:               Starting new session              
Aborted (core dumped)
  

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5531387/openshot-qt.log)

**Comment by phelix001** [comment]
> @DocSalvager
> 
> Sorry for the delay. This AppImage build:
> [OpenShot-v2.5.1-dev2-no-glib-1605133643-b910d2f6-2cb4eeff-x86_64.AppImage](https://drive.google.com/file/d/1S1cOT2MTTKEB1sijZHWfxZMmnl9Qjnmf/view?usp=sharing)
> has all of the glib components excluded from bundling. Would you be able to test and let us know if it solves the launch errors on your system?

Didn't work; see below; thanks for trying.

**Comment by ferdnyc** [comment]
@phelix001 

Well, now that's very strange. I tested on Fedora 33, and the new build did indeed launch, where 2.5.1 release does not (as reported by @supravirtual).

There are a couple of error messages that concern me somewhat:
```text
/tmp/.mount_KnqYUZ/usr/bin/QtWebEngineProcess: 
/tmp/.mount_KnqYUZ/usr/bin/libselinux.so.1: 
no version information available (required by /lib64/libgio-2.0.so.0)
/tmp/.mount_KnqYUZ/usr/bin/QtWebEngineProcess: 
/tmp/.mount_KnqYUZ/usr/bin/libselinux.so.1: 
no version information available (required by /lib64/libmount.so.1)
```

But despite that it appears to be fully functional.

You're on Ubuntu 20.04, was it, @phelix001 ? If that's the case, it's very possible my worries was correct, and the Debian 10 `OPENSSL_CONF` bug (#3242) has returned. I would imagine Ubuntu 20.04 is fairly close to Debian 10. The fact that it hardly gets far enough to even _start_ running OpenShot itself sounds like a recurrence of that issue.

**Comment by AdamLeonSmith** [comment]
On Ubuntu 20, the production build doesn't work for me., same issue as OP described  The dev build referenced above DOES work.

**Comment by joshnatis** [comment]
Having the same problem on Arch Linux, kernel 5.4.80-2-lts -- I downloaded the AppImage from https://www.openshot.org/download/, ran `chmod +x OpenShot...`, then `./OpenShot...`. A graphical window opens with an error trace complaining about ImportErrors for `_openshot` and `libselinux.so`.

This is the full trace:
```
Module: _openshot

Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_oJVQLs/usr/bin/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_oJVQLs/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 28, in <module>
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 20, in swig_import_helper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 539, in _check_name_wrapper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1715, in load_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory
```

Additionally, when I run the image I see `zenity, kdialog, Xdialog missing. Skipping ./bin//openshot-qt-wrapper`.

I tried to run the dev version linked [by ferdnyc above](https://github.com/OpenShot/openshot-qt/issues/3807#issuecomment-725780680), but this also fails (albeit differently). No graphical window launches, instead I get a trace culminating in an ImportError for `libbsd.so.0`:

```
zenity, kdialog, Xdialog missing. Skipping ./bin//openshot-qt-launch.wrapper.
Loaded modules from: /tmp/.mount_UiJMDf/usr/bin
Traceback (most recent call last):
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "openshot_qt/launch.py", line 147, in <module>
    main()
  File "openshot_qt/launch.py", line 135, in main
    from classes.app import OpenShotApp
  File "/tmp/.mount_UiJMDf/usr/bin/classes/app.py", line 39, in <module>
    from PyQt5.QtGui import QPalette, QColor, QFontDatabase, QFont
ImportError: libbsd.so.0: cannot open shared object file: No such file or directory
```

After installing `libbsd` with my system's package manager, running the dev version works!
