### ISSUE TITLE
Cannot start AppImage: libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items

### ISSUE THREAD

**Issue by raffaem** [OpenShot/openshot-qt#3941]
I have downloaded [OpenShot][1] v2.5.1 (the latest version as of today), in the form of x86_64 AppImage.

Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2
Kernel Version: 5.8.0-33-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz
Memory: 15,5 GiB of RAM
Graphics Processor: GeForce GTX 1060/PCIe/SSE2

Here is the error message when I try to run it:

```
Module: _openshot

Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_z2XiKa/usr/bin/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_z2XiKa/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 28, in <module>
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 20, in swig_import_helper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 539, in _check_name_wrapper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1715, in load_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
ImportError: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items
```

  [1]: http://www.openshot.org

**Comment by raffaem** [comment]
Works on the latest daily builds

OpenShot-v2.5.1-dev2-6268-2699e7d1-d3337154-x86_64.AppImage

compiled on Dec. 27, 2020, 10:34 a.m.

**Comment by USATechDude** [comment]
I don't have 20.10, I'm still on 20.04 LTS.  Is `libpango-1.0.so.0` included in 20.10?  What happens is you use `apt-get` to install `libpango-1.0.so.0`?

**Comment by not-samurai** [comment]
facing the same issue in manjaro 20.1, please help

**Comment by JaapJoris** [comment]
I am also experiencing this issue using [this app image](https://github.com/OpenShot/openshot-qt/releases/download/v2.5.1/OpenShot-v2.5.1-x86_64.AppImage) on Debian 11. 

I have the package `libpango-1.0-0` installed. When I removed it, I got a different error:

```
ImportError: libpango-1.0.so.0: cannot open shared object file: No such file or directory
```
