### ISSUE TITLE
Appimage won't start

### ISSUE THREAD

**Issue by ruben-herold** [OpenShot/openshot-qt#3971]
Appimage won'T start:

Module: _openshot

Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_3qOmm5/usr/bin/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_3qOmm5/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 28, in <module>
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 20, in swig_import_helper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 539, in _check_name_wrapper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1715, in load_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
ImportError: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items

**Comment by MakiWolf** [comment]
Duplicate of [https://github.com/OpenShot/openshot-qt/issues/3859](https://github.com/OpenShot/openshot-qt/issues/3859)
