### ISSUE TITLE
undefined symbol: __gmpn_cnd_sub_n

### ISSUE THREAD

**Issue by rmefe** [OpenShot/openshot-qt#4008]
**undefined symbol: __gmpn_cnd_sub_n**

Some uptodate libraries are missing in the appimage

**Steps to reproduce the behavior:**
1. Install CentOS 8
2. run Openshot

**Expected behavior:**
Openshot should provide all necessary libraries

**System Details:**
- OpenShot Version : 2.5.1
- Operating System / Distro: Centos 8.3.2011

**Exception / Stacktrace:**

[r@centos ~]$ ./Downloads/OpenShot-v2.5.1-x86_64.AppImage 
Traceback (most recent call last):
  File "openshot_qt/launch.py", line 47, in <module>
    from classes import info
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_2ed9eE/usr/bin/classes/info.py", line 30, in <module>
    from PyQt5.QtCore import QDir
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "ExtensionLoader_PyQt5_QtCore.py", line 22, in <module>
  File "ExtensionLoader_PyQt5_QtCore.py", line 14, in __bootstrap__
ImportError: /lib64/libhogweed.so.4: undefined symbol: __gmpn_cnd_sub_n

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 52, in <module>
    from classes import info
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_2ed9eE/usr/bin/classes/info.py", line 30, in <module>
    from PyQt5.QtCore import QDir
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "ExtensionLoader_PyQt5_QtCore.py", line 22, in <module>
  File "ExtensionLoader_PyQt5_QtCore.py", line 14, in __bootstrap__
ImportError: /lib64/libhogweed.so.4: undefined symbol: __gmpn_cnd_sub_n

**Comment by rmefe** [comment]
I tried to workaround this with LD_PRELOAD:

export LD_PRELOAD="/usr/lib64/libhogweed.so.4.5 /usr/lib64/libgmp.so /usr/lib64/libgnutls.so.30"

But then I'm stuck at:

[r@centos ~]$ ./Downloads/OpenShot-v2.5.1-x86_64.AppImage 
/tmp/.mount_SJ1gP7/usr/bin/openshot-qt: symbol lookup error: /usr/lib64/libgnutls.so.30: undefined symbol: asn1_der_decoding2, version LIBTASN1_0_3

**Comment by rmefe** [comment]
export LD_PRELOAD="/usr/lib64/libhogweed.so.4.5 /usr/lib64/libgmp.so /usr/lib64/libgnutls.so.30 /usr/lib64/libtasn1.so.6" solved the issue with loading, but AFAIK it should be loaded/provided by the AppImage.
