### ISSUE TITLE
Error determining OS version in metrics.py

### ISSUE THREAD

**Issue by grahamwhiteuk** [OpenShot/openshot-qt#4025]
**Describe the bug:**
Upon starting openshot-qt on Linux I see `metrics:ERROR Error determining OS version in metrics.py`

**Steps to reproduce the behavior:**
1. Start the application on Linux
2. Observe the error text `metrics:ERROR Error determining OS version in metrics.py`

**Expected behavior:**
No error should be present, application should correctly detect OS version

**System Details:**
Fedora Linux version 33, Python 3.9.1

    app:INFO ------------------------------------------------
    app:INFO             Fri Feb 26 09:45:15 2021            
    app:INFO               Starting new session              
    app:INFO ------------------------------------------------
    app:INFO             OpenShot (version 2.5.1)            
    app:INFO ------------------------------------------------
    app:INFO openshot-qt version: 2.5.1
    app:INFO libopenshot version: 0.2.5
    app:INFO platform: Linux-5.10.16-200.fc33.x86_64-x86_64-with-glibc2.32
    app:INFO processor: x86_64
    app:INFO machine: x86_64
    app:INFO python version: 3.9.1
    app:INFO qt5 version: 5.15.2
    app:INFO pyqt5 version: 5.15.0

**Problem Identified and Fix**
The problem is that `metrics.py` from openshot-qt attempts to get the Linux distribution details via
    
    linux_distro = "-".join(platform.linux_distribution())

However, `platform..linux_distribution()` has been deprecated ([more info on Stackoverflow](https://stackoverflow.com/questions/49554443/platform-linux-distribution-deprecated-what-are-the-alternatives)) in more recent versions of Python

The fix is to
    
    import distro
    distro.linux_distribution()

**Comment by leisti** [comment]
I just reproduced the problem after installing openshot-qt using the command `sudo apt install openshot-qt`. On commanding `openshot-qt &` in the terminal emulator, the following was output:

```
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Mon Jan  1 00:15:37 2024
         app:INFO               Starting new session
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.10.12
         app:INFO qt5 version: 5.15.3
         app:INFO pyqt5 version: 5.15.6
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['en-GB']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable:
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to Cantarell
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
     version:INFO Found current version: {"openshot_version": "3.1.1", "error_rate_stable": 0.25, "trans_rate_unstable": 0.001, "trans_rate_stable": 0.01, "error_rate_unstable": 0.05}
```

My system: Linux Mint 21.2, kernel Linux 5.15.0-91-generic, machine Lenovo ThinkPad X1 Carbon 7th generation, architecture x86-64.

The application doesn't crash, just hangs. I notice that my version is the same as in the original bug report above — I suppose I have to wait for an update to Linux Mint to get the one with the fix to this bug?
