### ISSUE TITLE
Can't launch the app

### ISSUE THREAD

**Issue by stemy2** [OpenShot/openshot-qt#4038]
**Describe the bug:**
Nothing happens when i try to launch openshot.

**Steps to reproduce the behavior:**
1. Launch the app.

**Expected behavior:**
App is launched

**System Details:**
- OpenShot Version 2.4.3
- Operating System / Distro: Debian stable

**Exception / Stacktrace:**
```
stem@debian:~$ openshot-qt
Compiled translation resources missing!
Loading translations from: /usr/lib/python3/dist-packages/openshot_qt/language
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.3)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.3
         app:INFO libopenshot version: 0.2.2
         app:INFO platform: Linux-5.10.0-0.bpo.3-amd64-x86_64-with-debian-10.8
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.7.3
         app:INFO qt5 version: 5.13.0
         app:INFO pyqt5 version: 5.13.0
    language:INFO Qt Detected Languages: ['fr']
    language:INFO LANG Environment Variable: fr_BE.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to Cantarell
         app:INFO Setting custom dark theme
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.4.3', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 98, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 157, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```
I'd like to point out that the command didn't even terminated, i had to hit Ctrl + c to resume control over the terminal.

**Comment by USATechDude** [comment]
OpenShot v2.4.3 is an ancient version.  You probably will not receive much help with version 2.4.3.  I realize it is the version included with your Linux distribution, but have you tried downloading [the AppImage file](https://www.openshot.org/download/) from the webserver?
