### ISSUE TITLE
Path key in project json file is uncorrect for some paths (Windows)

### ISSUE THREAD

**Issue by damwiw** [OpenShot/openshot-qt#4405]
**Describe the bug:**
On Windows, when you include files in the project from some drive distinct from the project one, the project json file is uncorrectly saved. In the json structure, instead of "path" you will get path (without quotes).

**Steps to reproduce the behavior:**
1. Start a new project and save it on "C:\Users\<myuser>\foo\test.osp".
2. Include two files, one located in C ("C:\Users\<myuser>\images\myimage.jpg") and the other one on some other drive, such as "D:\bar\myotherimage.jpg".
3. Save and close the project.
4. Open it again. You will get an error message 'name "ex" is not defined'.
5. If you look at the openshot-qt.log file, application is complaining about property not enclosed in double quote.
6. If you open the osp file, you will see something like:
_For the file on the same drive:_
      "path": "../images/myimage.jpg",
_For the file on the other drive:_
      path: "D:/bar/myotherimage.jpg",

**Expected behavior:**
Correctly saved json file.

**System Details:**
```
12:08:25 INFO app: ------------------------------------------------
12:08:25 INFO app:             Wed Sep  8 12:08:25 2021            
12:08:25 INFO app:               Starting new session              
12:08:25 INFO app: ------------------------------------------------
12:08:25 INFO app:             OpenShot (version 2.6.0)            
12:08:25 INFO app: ------------------------------------------------
12:08:25 INFO app: openshot-qt version: 2.6.0
12:08:25 INFO app: libopenshot version: 0.2.6
12:08:25 INFO app: platform: Windows-10-10.0.18362
12:08:25 INFO app: processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
12:08:25 INFO app: machine: AMD64
12:08:25 INFO app: python version: 3.8.9
12:08:25 INFO app: qt5 version: 5.15.2
12:08:25 INFO app: pyqt5 version: 5.15.4
12:08:25 INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.0-release-candidate-8083-73b009d3-6a84f7ee",
    "date": "2021-08-25 15:11",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "release-20210819",
        "CI_COMMIT_SHA": "73b009d38f678ca77a1b1564e1f2492b8ff1fed7",
        "CI_JOB_ID": "26986",
        "CI_PIPELINE_ID": "8070",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "20",
        "VERSION": "0.2.6"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "release-20210819",
        "CI_COMMIT_SHA": "6a84f7ee7c6ed49b1143b7611e2bcb9765f9139a",
        "CI_JOB_ID": "26976",
        "CI_PIPELINE_ID": "8068",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.1"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20210819",
        "CI_COMMIT_SHA": "6e636e823a5a16dccb8e58e50ba15989cdd34e6c",
        "CI_JOB_ID": "27028",
        "CI_PIPELINE_ID": "8083",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.0"
    }
}

```
**Log Files:**
```
12:37:44 INFO project_data: Loading project file: C:\Users\<myuser>\Openshot\OpenShot\Test OpenShot.osp
12:37:44 ERROR json_data: Couldn't load project data file
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\classes\json_data.py", line 191, in read_from_file
    return json.loads(contents)
  File "C:/msys64/mingw64/lib/python3.8/json/__init__.py", line 357, in loads
  File "C:/msys64/mingw64/lib/python3.8/json/decoder.py", line 337, in decode
  File "C:/msys64/mingw64/lib/python3.8/json/decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 311 column 5 (char 4483)
12:37:44 ERROR project_data: Failed to load legacy project file C:\Users\<myuser>\Openshot\OpenShot\Test OpenShot.osp
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\classes\json_data.py", line 191, in read_from_file
    return json.loads(contents)
  File "C:/msys64/mingw64/lib/python3.8/json/__init__.py", line 357, in loads
  File "C:/msys64/mingw64/lib/python3.8/json/decoder.py", line 337, in decode
  File "C:/msys64/mingw64/lib/python3.8/json/decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 311 column 5 (char 4483)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\classes\project_data.py", line 350, in load
    project_data = self.read_from_file(file_path, path_mode="absolute")
  File "C:\Program Files\OpenShot Video Editor\classes\json_data.py", line 198, in read_from_file
    raise Exception(msg) from ex
Exception: Couldn't load project data file

```

**Issue by-pass:**
Move the resource files in the same drive than the project one (or the opposite!).

Thanks for your effort. Have a nice day.

Damien

**Comment by JacksonRG** [comment]
Hi, I made a change to fix this bug. The fix is present in our daily build, as well as our new release 2.6.1!

Please try our new release, and let me know if this fixes the problem. If not, I'd be happy to investigate further.

**Comment by damwiw** [comment]
Hi,
That's running fine now (2.6.1), you fixed it fast!
Thanks a lot. Have a nice week,
Damien
