### ISSUE TITLE
AppImage on RHEL 8 based systems not launching

### ISSUE THREAD

**Issue by michaelbarkdoll** [OpenShot/openshot-qt#4444]
$ ./OpenShot-v2.6.1-dev-daily-8320-21597c8a-73c519f0-x86_64.AppImage 
Copying icon thumbnails to cache
ICONFILE = /home/cisadmin/.cache/thumbnails/normal/3dabeeb2fe9b697259a5036a1f9badcf.png
Traceback (most recent call last):
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "openshot_qt/launch.py", line 47, in <module>
    from PyQt5.QtCore import Qt
ImportError: /tmp/.mount_ecqmWg/usr/bin/libgnutls.so.30: version `GNUTLS_3_6_9' not found (required by /lib64/libglib-2.0.so.0)

$ ./OpenShot-v2.6.1-x86_64.AppImage 
Copying icon thumbnails to cache
ICONFILE = /home/cisadmin/.cache/thumbnails/normal/2418c2261e8197f4a69e34adc13c0b7e.png
Traceback (most recent call last):
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "openshot_qt/launch.py", line 47, in <module>
    from PyQt5.QtCore import Qt
ImportError: /tmp/.mount_hD8iVq/usr/bin/libgnutls.so.30: version `GNUTLS_3_6_9' not found (required by /lib64/libglib-2.0.so.0)

**Comment by sc0nway** [comment]
<details>
  <summary>A similar issue was reported by a customer to our Help Desk.</summary>

[Freshdesk Ticket #3150](https://support.openshot.org/a/tickets/3150)
</details>

```
$ ./OpenShot-v2.6.1-x86_64.AppImage
Copying icon thumbnails to cache
ICONFILE = /home/fotieno/.cache/thumbnails/normal/aa961c45614c68957d58307251a27059.png
Traceback (most recent call last):
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "openshot_qt/launch.py", line 47, in <module>
    from PyQt5.QtCore import Qt
ImportError: /tmp/.mount_cqDrPl/usr/bin/libgnutls.so.30: version `GNUTLS_3_6_9' not found (required by /lib64/libglib-2.0.so.0)
$ 
```

**Comment by jperkyns** [comment]
Is there any workaround on this issue? I am having it too with a fresh install of Rocky Linux.

**Comment by gauze** [comment]
Samesies

**Comment by YJesus** [comment]
Why not integrate OpenShot in Snap ? Lot of pain will be avoided

**Comment by Karm** [comment]
The same here. Centos Stream 8.

**Comment by JacksonRG** [comment]
I believe I've seen a similar issue to this before. Some packages are basic enough that Appimage doesn't bundle them automatically. Do you get a different result if you install `gnutils v3.6.9`? Or if you install `libglib-2.0`?

**Comment by jonoomph** [comment]
This is now fixed, and our AppImage should correctly load in Red Hat based distros, as well as continue to work on Debian and other distros. If you find a distro that does not work, please let us know.

**Comment by YJesus** [comment]
Thank you !! Nice work.

**Comment by michaelbarkdoll** [comment]
Rocky Linux 8.5 (RHEL 8)
```
$ ./OpenShot-v2.6.1-dev-daily-9498-664c5db8-46255e46-x86_64.AppImage
Copying icon thumbnails to cache
ICONFILE = /home/username/.cache/thumbnails/normal/117422f942037967ea122549e9d4c250.png
Detected scale factor: 1.04
Setting QT_SCREEN_SCALE_FACTORS='1.04;'
Loaded modules from: /tmp/.mount_pwJ2Za/usr/bin
INFO app: ------------------------------------------------
INFO app:             Tue Jun  7 09:39:43 2022            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:           OpenShot (version 2.6.1-dev)          
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1-dev
INFO app: libopenshot version: 0.2.7-dev
INFO app: platform: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-centos-8.6-Green_Obsidian
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.6.9
INFO app: qt5 version: 5.9.5
INFO app: pyqt5 version: 5.10.1
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.1-dev-daily-9498-664c5db8-46255e46",
    "date": "2022-05-26 18:05",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "664c5db821d356059f86c132e71646894e9f9d0f",
        "CI_JOB_ID": "30770",
        "CI_PIPELINE_ID": "9480",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "21",
        "VERSION": "0.2.7-dev"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "46255e46a46cad990236f941130e096155e2577a",
        "CI_JOB_ID": "30259",
        "CI_PIPELINE_ID": "9280",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.2-dev"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "0b11c34dfd46385cf8ba92fe9423cd5cbfbd77be",
        "CI_JOB_ID": "30816",
        "CI_PIPELINE_ID": "9498",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.1-dev"
    }
}
INFO project_data: Setting default profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
Screen DP-2
   devicePixelRatio: 1.04
   logicalDotsPerInch: 92.3076923076923
   physicalDotsPerInch: 102.13292009852704
   availableSizes: PyQt5.QtCore.QSize(3308, 1359)
Screen DP-4
   devicePixelRatio: 1.0
   logicalDotsPerInch: 92.3076923076923
   physicalDotsPerInch: 106.1985926725811
   availableSizes: PyQt5.QtCore.QSize(3440, 1413)
INFO language: Qt Detected Languages: ['en-US']
INFO language: LANG Environment Variable: en_US.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO app: Setting font to /tmp/.mount_pwJ2Za/usr/bin/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
INFO ui_util: Initializing UI for MainWindow
Sandboxing disabled by user.
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Installed Qt WebEngine locales directory not found at location /tmp/.mount_pwJ2Za/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_pwJ2Za/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/username/.openshot'
[0607/093945.299597:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
Installed Qt WebEngine locales directory not found at location /tmp/.mount_pwJ2Za/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_pwJ2Za/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/username/.QtWebEngineProcess'
[0607/093945.779840:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
INFO thumbnail: Starting thumbnail server listening on port 49993
INFO webengine: WebEngine backend initializing
INFO transition_model: updating transitions model.
INFO version: Found current version: {'openshot_version': '2.6.1', 'trans_rate_stable': 0.01, 'error_rate_stable': 0.16, 'trans_rate_unstable': 0.001, 'error_rate_unstable': 0.05}
INFO effects_model: updating effects model.
INFO emoji_model: updating emoji model.
INFO sentry: Sentry initialized for 'unstable': 0.05 sample rate, 0.001 transaction rate
INFO main_window: InitCacheSettings
INFO main_window: cache-mode: CacheMemory
INFO main_window: cache-limit-mb: 1024
INFO main_window: Creating CacheMemory object with 1073741824 byte limit
INFO preview_thread: QThread Start Method Invoked
INFO main_window: Cleared temporary files: /home/username/.openshot_qt/thumbnail
INFO main_window: Cleared temporary files: /home/username/.openshot_qt/blender
INFO main_window: Cleared temporary files: /home/username/.openshot_qt/title
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
  /lib64/libc.so.6               ( abort                                     + 0x127 )  [0x7f3c15f09db5]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Core.so.5 (                                           + 0x96fb7)  [0x7f3c074a3fb7]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5QuickWidgets.so.5 (                                           + 0xa9f0)  [0x7f3bf8eb39f0]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5QuickWidgets.so.5 (                                           + 0xad5a)  [0x7f3bf8eb3d5a]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5QuickWidgets.so.5 ( QQuickWidget::resizeEvent(QResizeEvent*)  + 0x38e )  [0x7f3bf8eb5f8e]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5WebEngineWidgets.so.5 (                                           + 0x307fd)  [0x7f3c002027fd]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidget::event(QEvent*)                   + 0xda2 )  [0x7f3c0322ebe2]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5QuickWidgets.so.5 ( QQuickWidget::event(QEvent*)              + 0x19b )  [0x7f3bf8eb69eb]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5WebEngineWidgets.so.5 (                                           + 0x30b1b)  [0x7f3c00202b1b]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x9c  )  [0x7f3c031ef83c]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x2a4 )  [0x7f3c031f7104]
  /tmp/.mount_pwJ2Za/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x3ab97e)  [0x7f3c03c8d97e]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x118 )  [0x7f3c076978a8]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool)  + 0x1ab )  [0x7f3c032270eb]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::show_helper()             + 0x33  )  [0x7f3c0322aec3]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::showChildren(bool)        + 0x8e  )  [0x7f3c0322adde]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::show_helper()             + 0x4f  )  [0x7f3c0322aedf]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidget::setVisible(bool)                 + 0x1eb )  [0x7f3c0322dbdb]
  /tmp/.mount_pwJ2Za/usr/bin/lib/PyQt5/QtWebEngineWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x16183)  [0x7f3c00429183]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::showChildren(bool)        + 0xe0  )  [0x7f3c0322ae30]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::show_helper()             + 0x4f  )  [0x7f3c0322aedf]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::showChildren(bool)        + 0x8e  )  [0x7f3c0322adde]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::show_helper()             + 0x4f  )  [0x7f3c0322aedf]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidget::setVisible(bool)                 + 0x1eb )  [0x7f3c0322dbdb]
  /tmp/.mount_pwJ2Za/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x346923)  [0x7f3c03c28923]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::showChildren(bool)        + 0xe0  )  [0x7f3c0322ae30]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidgetPrivate::show_helper()             + 0x4f  )  [0x7f3c0322aedf]
  /tmp/.mount_pwJ2Za/usr/bin/libQt5Widgets.so.5 ( QWidget::setVisible(bool)                 + 0x1eb )  [0x7f3c0322dbdb]
  /tmp/.mount_pwJ2Za/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x22ded3)  [0x7f3c03b0fed3]
  /tmp/.mount_pwJ2Za/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x37f512)  [0x7f3c03c61512]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyCFunction_FastCallDict                 + 0x1bb )  [0x7f3c164c053b]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17c1ec)  [0x7f3c164291ec]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x4ec3)  [0x7f3c1642f303]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17ba0f)  [0x7f3c16428a0f]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyFunction_FastCallDict                  + 0x1e4 )  [0x7f3c16428d34]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyObject_FastCallDict                    + 0x131 )  [0x7f3c16513fd1]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyObject_Call_Prepend                    + 0xcd  )  [0x7f3c165146fd]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( PyObject_Call                             + 0x48  )  [0x7f3c16514768]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x1f4739)  [0x7f3c164a1739]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x1fc1c2)  [0x7f3c164a91c2]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyObject_FastCallDict                    + 0x89  )  [0x7f3c16513f29]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17bec8)  [0x7f3c16428ec8]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x4ec3)  [0x7f3c1642f303]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17a803)  [0x7f3c16427803]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17c2be)  [0x7f3c164292be]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x4ec3)  [0x7f3c1642f303]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17a803)  [0x7f3c16427803]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17c2be)  [0x7f3c164292be]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x4ec3)  [0x7f3c1642f303]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17ba0f)  [0x7f3c16428a0f]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( PyEval_EvalCodeEx                         + 0x3e  )  [0x7f3c164294ce]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( PyEval_EvalCode                           + 0x1b  )  [0x7f3c1642a24b]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x18855d)  [0x7f3c1643555d]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyCFunction_FastCallDict                 + 0x1bb )  [0x7f3c164c053b]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17c1ec)  [0x7f3c164291ec]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x4ec3)  [0x7f3c1642f303]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17a803)  [0x7f3c16427803]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17c2be)  [0x7f3c164292be]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x4ec3)  [0x7f3c1642f303]
  /tmp/.mount_pwJ2Za/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17a803)  [0x7f3c16427803]
---- End of Stack Trace ----
```

**Comment by michaelbarkdoll** [comment]
Thank you !!! This works on Rocky Linux 8.6 tested with proprietary Nvidia driver installed and it works great, thanks.
