### ISSUE TITLE
Openshot 2.2 doesn't support ubuntu 16.10

### ISSUE THREAD

**Issue by simonazriel** [OpenShot/openshot-qt#458]
After installing from ppa and running from command line I get:

```
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.2.0)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.2.0
         app:INFO libopenshot version: 0.1.3
         app:INFO platform: Linux-4.8.0-32-generic-x86_64-with-Ubuntu-16.10-yakkety
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2+
         app:INFO qt5 version: 5.7.0
         app:INFO pyqt5 version: 5.7
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: en_US
    language:INFO Skipping English language (no need for translation): en_US.UTF-8
    language:INFO Skipping English language (no need for translation): en_US
project_data:INFO Setting default profile to HD 1080p 60 fps
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.2.0', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 161, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 42, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 39, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: {'server': 'Apache/2.2.22 (Ubuntu)', 'vary': 'Accept-Encoding', 'content-length': '29', 'status': '200', 'date': 'Sat, 31 Dec 2016 19:44:59 GMT', 'content-type': 'text/html; charset=utf-8', '-content-encoding': 'gzip'} (b'*exception-successfully-sent*')
^C      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.5/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
      logger:ERROR t.join()
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1054, in join
      logger:ERROR self._wait_for_tstate_lock()
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
      logger:ERROR elif lock.acquire(block, timeout):
      logger:ERROR KeyboardInterrupt
```

It looks like the version of PyQt5 on 16.10 is later than 5.6 so the Webkit has been removed
http://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules

"With Qt 5.6 the following modules are no longer part of the release packages, but users can still build them from source:

Qt WebKit
Qt Declarative (Qt Quick 1)"

It looks like ubuntu 16.10 yakkety yak ships with a later version so doesn't have the required dependency.

**Comment by leventelist** [comment]
Install these: python3-pyqt5.qtwebkit and python3-pyqt5.qtsvg

**Comment by ankitpati** [comment]
@jonoomph Please take note. The DEB file in the PPA should mention these as dependencies. It should complain while installing, not while running.

**Comment by DylanC** [comment]
OpenShot 2.3.4 does support Ubuntu 16.10 now. (correct me on this if im wrong) Closing for now.
