### ISSUE TITLE
OpenShot 2.6.1 does not start on MacOS Monterey

### ISSUE THREAD

**Issue by subzero01** [OpenShot/openshot-qt#4588]
**Describe the bug:**
App does not start.

**Steps to reproduce the behavior:**
Start the app

**Expected behavior:**
App should start

**System Details:**
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 2.6.1)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1
INFO app: libopenshot version: 0.2.7
INFO app: platform: Darwin-21.1.0-x86_64-i386-64bit
INFO app: processor: i386
INFO app: machine: x86_64
INFO app: python version: 3.7.11
INFO app: qt5 version: 5.15.0
INFO app: pyqt5 version: 5.15.1.dev2007111314
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6",
    "date": "2021-09-04 18:49",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "59878784732fa399c47ac5d282bfc9dfe470d0dc",
        "CI_JOB_ID": "27418",
        "CI_PIPELINE_ID": "8237",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "21",
        "VERSION": "0.2.7"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "d588dbd6057f71c987dc6d8448322aa6b6e86f1a",
        "CI_JOB_ID": "27413",
        "CI_PIPELINE_ID": "8236",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.2"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "11f8e5050bd95c7731beccda28a01fbb481fcf7d",
        "CI_JOB_ID": "27423",
        "CI_PIPELINE_ID": "8238",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.1"
    }
}

Macos 12.0.1
**Log Files:**
...
INFO project_data: Setting default profile to HD 720p 30 fps
dyld[1899]: <87E92310-714B-321A-A9E6-7362CC3F0BAE> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/_elementtree.cpython-37m-darwin.so
dyld[1899]: <57286DB3-3F82-3CB6-8363-8ACE13C03100> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/pyexpat.cpython-37m-darwin.so
dyld[1899]: <26BB13BD-AAB9-343C-8E8D-0A7D20D51188> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/_ctypes.cpython-37m-darwin.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/__startup__.py", line 41, in run
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/Console.py", line 36, in run
  File "openshot_qt/launch.py", line 203, in <module>
    main()
  File "openshot_qt/launch.py", line 198, in main
    app.gui()
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/app.py", line 190, in gui
    from classes import language, sentry, ui_util, logger_libopenshot
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/logger_libopenshot.py", line 34, in <module>
    import zmq
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 50, in <module>
dyld[1899]: <F64945D3-E0F5-3496-A33F-66C02D2D8ED8> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/unicodedata.cpython-37m-darwin.so
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 16, in _load_libzmq
    the Free Software Foundation, either version 3 of the License, or
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 551, in <module>
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
MemoryError
INFO app:             OpenShot's session ended            
INFO app:             Fri Dec 10 23:38:23 2021            
INFO app: ================================================
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
QLibraryPrivate::unload succeeded on "/Applications/OpenShot Video Editor.app/Contents/MacOS/platforms/libqcocoa.dylib" 

**Exception / Stacktrace:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/__startup__.py", line 41, in run
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/Console.py", line 36, in run
  File "openshot_qt/launch.py", line 203, in <module>
    main()
  File "openshot_qt/launch.py", line 198, in main
    app.gui()
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/app.py", line 190, in gui
    from classes import language, sentry, ui_util, logger_libopenshot
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/logger_libopenshot.py", line 34, in <module>
    import zmq
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 50, in <module>
dyld[1869]: <F64945D3-E0F5-3496-A33F-66C02D2D8ED8> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/unicodedata.cpython-37m-darwin.so
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 16, in _load_libzmq
    the Free Software Foundation, either version 3 of the License, or
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 551, in <module>
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
MemoryError

**Comment by moseisleydk** [comment]
I seem to have the samme Issue.

**Comment by hmijail** [comment]
Same here.

**Comment by hmijail** [comment]
As reported in https://github.com/OpenShot/openshot-qt/issues/4533#issuecomment-993779503, the nightly builds fix this problem.

**Comment by igor-petrik-invitae** [comment]
Any idea when the stable release with this fix will come?

**Comment by gautamr2** [comment]
Same issue, is there any update?

**Comment by patrickatwsrn** [comment]
Still an issue. Todays nightly build from May 13, 2022, 4:40 p.m. works as promissed.

Thanks for your work!

**Comment by JacksonRG** [comment]
@patrickatwsrn You said the nightly build works as promised meaning (if I'm understanding) the next major release will include that fix. By "still an issue" do you mean that the release version still has this bug?

**Comment by madhusudan81** [comment]
@JacksonRG It's working.. download the latest version from daily builds here-> https://www.openshot.org/download/

**Comment by madhusudan81** [comment]
> 
Thanks @patrickatwsrn it's working fine after i updated openshot from the latest daily build. GG

**Comment by JacksonRG** [comment]
Good to hear! Closing for now. Feel free to reopen if needed.

**Comment by surya-ravi** [comment]
@JacksonRG @madhusudan81 Just wanted to check if this issue is back up. I am unable to open openshot on my Mac Monterey 12.4. Openshot is bouncing on the dock but not opening

**Comment by JacksonRG** [comment]
@madhusudan81 Is this failing to open with the most up to date [daily build](https://www.openshot.org/download/)?

**Comment by surya-ravi** [comment]
I tried the latest daily build and it is now working for me. Got this window on opening though
<img width="916" alt="Screenshot 2022-06-18 at 8 59 54 AM" src="https://user-images.githubusercontent.com/82202595/174421245-269cf1e4-247c-4061-ac11-631076acea5c.png">

**Comment by madhusudan81** [comment]
It's working fine for me.. I am using version 2.6.1-dev build date 26/5/22

**Comment by randomhammer** [comment]
Does not work for me. I downloaded the latest build and when I launch it nothing happens. Running Monterey on Intel with 64GB RAM.

**Comment by DMLSMT** [comment]
I am running Monterey 12.3.1 and am having issues, as reported above. I just downloaded the new version because I had problems with version 3.5. It kept freezing up.  Openshot 2.6.1 isn't working, as stated above. It bounces in the taskbar, then sits there and doesn't do anything.

It looks like it is still an issue; I don't know why this was closed.

**Comment by kaymckelly** [comment]
Same issue here as well. Monterey 12.5.1

**Comment by ajRiverav** [comment]
does not help to post this in a closed issue. 
Opened https://github.com/OpenShot/openshot-qt/issues/4906

**Comment by tsugabloom** [comment]
Latest non-daily download is still failing. If I open via CLI there's the same `MemoryError`. **The daily build:  `OpenShot-v2.6.1-dev-daily-9733-cfca6e77-46255e46-x86_64.dmg | Sept. 5, 2022, 10:27 a.m.`  does work tho!**

<details>
<summary>Logs from the normal (non-daily build):</summary>

```
OpenShot Video Editor.app/Contents/MacOS
❯ ./openshot-qt
Compiled translation resources missing!
Loading translations from: /Applications/OpenShot Video Editor.app/Contents/Resources/language
Loaded modules from: /Applications/OpenShot Video Editor.app/Contents/Resources
INFO app: ------------------------------------------------
INFO app:             Fri Sep  9 11:34:18 2022
INFO app:               Starting new session
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 2.6.1)
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1
INFO app: libopenshot version: 0.2.7
INFO app: platform: Darwin-21.5.0-x86_64-i386-64bit
INFO app: processor: i386
INFO app: machine: x86_64
INFO app: python version: 3.7.11
INFO app: qt5 version: 5.15.0
INFO app: pyqt5 version: 5.15.1.dev2007111314
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6",
    "date": "2021-09-04 18:49",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "59878784732fa399c47ac5d282bfc9dfe470d0dc",
        "CI_JOB_ID": "27418",
        "CI_PIPELINE_ID": "8237",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "21",
        "VERSION": "0.2.7"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "d588dbd6057f71c987dc6d8448322aa6b6e86f1a",
        "CI_JOB_ID": "27413",
        "CI_PIPELINE_ID": "8236",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.2"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "11f8e5050bd95c7731beccda28a01fbb481fcf7d",
        "CI_JOB_ID": "27423",
        "CI_PIPELINE_ID": "8238",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.1"
    }
}
INFO project_data: Setting default profile to HD 720p 30 fps
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/__startup__.py", line 41, in run
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/Console.py", line 36, in run
  File "openshot_qt/launch.py", line 203, in <module>
    main()
  File "openshot_qt/launch.py", line 198, in main
    app.gui()
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/app.py", line 190, in gui
    from classes import language, sentry, ui_util, logger_libopenshot
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/logger_libopenshot.py", line 34, in <module>
    import zmq
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 50, in <module>
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 16, in _load_libzmq
    the Free Software Foundation, either version 3 of the License, or
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 551, in <module>
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
MemoryError
INFO app:             OpenShot's session ended
INFO app:             Fri Sep  9 11:34:19 2022
INFO app: ================================================
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

OpenShot Video Editor.app/Contents/MacOS took 2s
❯ 
```

</details>

**Comment by amosdoublec** [comment]
happens to me too

**Comment by BlueCobold** [comment]
Still an issue for me latest downloaded version
