### ISSUE TITLE
OpenShot won't start if the proxy environment variable is malformed

### ISSUE THREAD

**Issue by harmin-parra** [OpenShot/openshot-qt#4589]
My Linux system has the following environment variables set:
```
http_proxy=localhost:3128
https_proxy=localhost:3128
```

OpenShot won't start

```
Loaded modules from: /tmp/.mount_XTV9Th/usr/bin
Traceback (most recent call last):
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "openshot_qt/launch.py", line 203, in <module>
    main()
  File "openshot_qt/launch.py", line 178, in main
    sentry.init_tracing()
  File "/tmp/.mount_XTV9Th/usr/bin/classes/sentry.py", line 67, in init_tracing
    environment=environment
  File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/hub.py", line 105, in _init
  File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/client.py", line 85, in __init__
  File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/client.py", line 107, in _init_impl
  File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/transport.py", line 393, in make_transport
  File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/transport.py", line 139, in __init__
  File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/transport.py", line 312, in _make_pool
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 429, in __init__
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme localhost

```
Tested with

- OpenShot-v2.6.1-x86_64.AppImage
- OpenShot-v2.6.1-dev-daily-8906-3c8dc71b-2b8b05c7-x86_64.AppImage

Works fine if the proxy variables have the `http://` prefix
```
http_proxy=http://localhost:3128
https_proxy=http://localhost:3128
```

**Comment by SirnoChan** [comment]
Nope, this should be an issue thrown to urllib3 project. Specifying the protocol is a necessary step to following the standards, but it should also be often to set a localhost proxy in http other than https.
