### ISSUE TITLE
Cannot launch v2.6.1 on macOS 12.0.1

### ISSUE THREAD

**Issue by jsumners** [OpenShot/openshot-qt#4603]
I found this application this morning and downloaded v2.6.1 from the releases tab in order to try it out. I tried launching it and the icon would pop up in the Dock and then disappear. So I attempted launching it directly and can see the resulting crash:

```
OpenShot Video Editor.app/Contents/MacOS
❯ ./openshot-qt
Compiled translation resources missing!
Loading translations from: /Applications/OpenShot Video Editor.app/Contents/Resources/language
Loaded modules from: /Applications/OpenShot Video Editor.app/Contents/Resources
INFO app: ------------------------------------------------
INFO app:             Fri Dec 17 09:15:01 2021
INFO app:               Starting new session
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 2.6.1)
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1
INFO app: libopenshot version: 0.2.7
INFO app: platform: Darwin-21.1.0-x86_64-i386-64bit
INFO app: processor: i386
INFO app: machine: x86_64
INFO app: python version: 3.7.11
INFO app: qt5 version: 5.15.0
INFO app: pyqt5 version: 5.15.1.dev2007111314
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6",
    "date": "2021-09-04 18:49",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "59878784732fa399c47ac5d282bfc9dfe470d0dc",
        "CI_JOB_ID": "27418",
        "CI_PIPELINE_ID": "8237",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "21",
        "VERSION": "0.2.7"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "d588dbd6057f71c987dc6d8448322aa6b6e86f1a",
        "CI_JOB_ID": "27413",
        "CI_PIPELINE_ID": "8236",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.2"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "11f8e5050bd95c7731beccda28a01fbb481fcf7d",
        "CI_JOB_ID": "27423",
        "CI_PIPELINE_ID": "8238",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.1"
    }
}
INFO project_data: Setting default profile to HD 720p 30 fps
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/__startup__.py", line 41, in run
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/Console.py", line 36, in run
  File "openshot_qt/launch.py", line 203, in <module>
    main()
  File "openshot_qt/launch.py", line 198, in main
    app.gui()
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/app.py", line 190, in gui
    from classes import language, sentry, ui_util, logger_libopenshot
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/logger_libopenshot.py", line 34, in <module>
    import zmq
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 50, in <module>
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 16, in _load_libzmq
    the Free Software Foundation, either version 3 of the License, or
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 551, in <module>
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
MemoryError
INFO app:             OpenShot's session ended
INFO app:             Fri Dec 17 09:15:01 2021
INFO app: ================================================
```

**Comment by diegomadero** [comment]
Same here on a MacBook Air with OS 12.0.1.

**Comment by MichaelFriedrich** [comment]
Same here on:
MacBookPro16,1
macOS 12.1 (21C52)

**Comment by hmijail** [comment]
As reported in https://github.com/OpenShot/openshot-qt/issues/4533#issuecomment-993779503, the nightly builds fix this problem.

**Comment by wongjiahau** [comment]
@hmijail Thanks that works for me on macOS Monterey.
