### ISSUE TITLE
OpenShot 2.6.1 not working on Montery 12.0.1

### ISSUE THREAD

**Issue by BlueCobold** [OpenShot/openshot-qt#4933]
**Describe the bug:**
The app closes during start

**Steps to reproduce the behavior:**
Start the app

**System Details:**
- OpenShot Version 2.6.1
- Operating System MacOS Montery 12.0.1

**Log Files:**
```
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 2.6.1)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1
INFO app: libopenshot version: 0.2.7
INFO app: platform: Darwin-21.1.0-x86_64-i386-64bit
INFO app: processor: i386
INFO app: machine: x86_64
INFO app: python version: 3.7.11
INFO app: qt5 version: 5.15.0
INFO app: pyqt5 version: 5.15.1.dev2007111314
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6",
    "date": "2021-09-04 18:49",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "59878784732fa399c47ac5d282bfc9dfe470d0dc",
        "CI_JOB_ID": "27418",
        "CI_PIPELINE_ID": "8237",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "21",
        "VERSION": "0.2.7"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "d588dbd6057f71c987dc6d8448322aa6b6e86f1a",
        "CI_JOB_ID": "27413",
        "CI_PIPELINE_ID": "8236",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.2"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "11f8e5050bd95c7731beccda28a01fbb481fcf7d",
        "CI_JOB_ID": "27423",
        "CI_PIPELINE_ID": "8238",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.1"
    }
}
INFO project_data: Setting default profile to HD 720p 30 fps
dyld[7777]: <87E92310-714B-321A-A9E6-7362CC3F0BAE> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/_elementtree.cpython-37m-darwin.so
dyld[7777]: <57286DB3-3F82-3CB6-8363-8ACE13C03100> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/pyexpat.cpython-37m-darwin.so
dyld[7777]: <26BB13BD-AAB9-343C-8E8D-0A7D20D51188> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/_ctypes.cpython-37m-darwin.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/__startup__.py", line 41, in run
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/Console.py", line 36, in run
  File "openshot_qt/launch.py", line 203, in <module>
    main()
  File "openshot_qt/launch.py", line 198, in main
    app.gui()
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/app.py", line 190, in gui
    from classes import language, sentry, ui_util, logger_libopenshot
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/logger_libopenshot.py", line 34, in <module>
    import zmq
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 50, in <module>
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 16, in _load_libzmq
dyld[7777]: <F64945D3-E0F5-3496-A33F-66C02D2D8ED8> /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/unicodedata.cpython-37m-darwin.so
    the Free Software Foundation, either version 3 of the License, or
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 551, in <module>
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
MemoryError
INFO app:             OpenShot's session ended            
INFO app:             Thu Sep 29 11:21:58 2022            
INFO app: ================================================
QLibraryPrivate::unload succeeded on "/Applications/OpenShot Video Editor.app/Contents/MacOS/platforms/libqcocoa.dylib" 
```

**Comment by Colorjet3** [comment]
I am not a developer but I know there has been many fixes for linux environments in the latest DEV Daily Build.  Please to go openshot.org/download, click on Daily Builds and download the latest AppImage.  Let us know if this resolved your issue.

**Comment by alex1712** [comment]
Solved for me installing the last daily from homebrew:
homebrew/cask-versions/openshot-video-editor-daily
