### ISSUE TITLE
ImportError: libkeyutils missing, python version "mismatch"

### ISSUE THREAD

**Issue by petaflot** [OpenShot/openshot-qt#5007]
**Describe the bug:**
ImportError when starting the app, app crashes on startup, gui does not even show for a fraction of a second

**Steps to reproduce the behavior:**
Download appimage, chmod+x, execute.

**Expected behavior:**
obviously the app should start.

neither sys-apps/keyutils nor dev-python/python-keyutils are installed on the system ; however, backtrace suggests python 3.6 which has been removed from the system around a year ago or so (system now has python 3.10.8 and 3.11.0 installed)

does it mean I need to reinstall the entire python 3.6 environment just for openshot? I thought the Appimage had "everything included" to make it work

**System Details:**
- OpenShot Version : /opt/OpenShot-v2.6.1-x86_64.AppImage
- Operating System / Distro: Gentoo Base System Release 2.9

**Log Files:**
see backtrace below.

**Exception / Stacktrace:**

```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-meta'
INFO app: ------------------------------------------------
INFO app:             Mon Nov 28 12:51:25 2022            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 14, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libkeyutils.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_esaaGf/usr/bin/classes/app.py", line 99, in __init__
    from classes import settings, project_data, updates
  File "/tmp/.mount_esaaGf/usr/bin/classes/project_data.py", line 48, in <module>
    import openshot
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 17, in <module>
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 16, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ImportError: libkeyutils.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 14, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libkeyutils.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "openshot_qt/launch.py", line 203, in <module>
    main()
  File "openshot_qt/launch.py", line 186, in main
    app = OpenShotApp(argv)
  File "/tmp/.mount_esaaGf/usr/bin/classes/app.py", line 99, in __init__
    from classes import settings, project_data, updates
  File "/tmp/.mount_esaaGf/usr/bin/classes/project_data.py", line 48, in <module>
    import openshot
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 17, in <module>
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 16, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ImportError: libkeyutils.so.1: cannot open shared object file: No such file or directory
INFO app:             OpenShot's session ended            
INFO app:             Mon Nov 28 12:51:26 2022            
INFO app: ================================================
```

**Comment by Colorjet3** [comment]
This is a known bug with version 2.6.1.  Please download the Daily Build 10243 from openshot.org/download/#daily.  Please DO NOT download any versions newer than that for now.  There are several bugs being worked on.

Let us know if this helped resolve your issue.

**Comment by petaflot** [comment]
unfortunately, this does not resolve the issue ; it just changes it slightly:
```
meta@gentx ~ $ /opt/OpenShot-v2.6.1-dev-daily-10243-854a3aa3-46255e46-x86_64.AppImage 
Copying icon thumbnails to cache
ICONFILE = /home/meta/.cache/thumbnails/normal/9158e617489e04578b4eb757d5b79ce1.png
Detected scale factor: 1.04
Setting QT_SCREEN_SCALE_FACTORS='1.04;'
Loaded modules from: /tmp/.mount_5A2aGr/usr/bin
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-meta'
INFO app: ------------------------------------------------
INFO app:             Tue Nov 29 11:00:42 2022            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 14, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libthai.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_5A2aGr/usr/bin/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/tmp/.mount_5A2aGr/usr/bin/classes/project_data.py", line 48, in <module>
    import openshot
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 17, in <module>
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 16, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ImportError: libthai.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 14, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libthai.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "openshot_qt/launch.py", line 189, in main
    app = OpenShotApp(argv)
  File "/tmp/.mount_5A2aGr/usr/bin/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/tmp/.mount_5A2aGr/usr/bin/classes/project_data.py", line 48, in <module>
    import openshot
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 17, in <module>
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 16, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ImportError: libthai.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/gitlab-runner/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "openshot_qt/launch.py", line 216, in <module>
    main()
  File "openshot_qt/launch.py", line 191, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Tue Nov 29 11:00:43 2022            
INFO app: ================================================
```

**Comment by Colorjet3** [comment]
Hello @petaflot  I am going to ask one of the DEV team members to take a look at this.

**Comment by jonoomph** [comment]
@petaflot The key part of this error message is `ImportError: libthai.so.0: cannot open shared object file: No such file or directory`. I'm no Gentoo expert though, but it appears you need to install this library. We purposely avoid packaging `libthai.so.0` in our AppImage, because we expect it to exist on the host system. However, I could not tell you the reason we expect that, lol. It's been a while, but hopefully this helps.

**Comment by petaflot** [comment]
`... requires no installation. Just download, make executable, and run.`

IMHO, "expecting" a host to have some dependency installed totally defeats the purpose of an AppImage.

What other components are not packaged? I'm really not in a mood to install a component, try/crash, install the next one, and so on recursively until it works.

Also and mentioned above, python 3.6 was entirely removed from my system months ago ; what prevents you from using an up-to-date version?

**Comment by petaflot** [comment]
so?

I'm afraid to admit you answer didn't help at all.

is there at least a list on what OSes this "AppImage" has been tested: Ubuntu? Windows ? ArchLinux? OpenBSD? Android? SourceMage?

I mean... at the very least be a little a little explicit.

**Comment by jonoomph** [comment]
I believe this is now fixed in https://github.com/OpenShot/openshot-qt/pull/5093. Please give our latest daily builds a try (in an hour or so): https://www.openshot.org/download#daily
