### ISSUE TITLE
Fresh Install From 'Ubuntu Software' Does Not Launch

### ISSUE THREAD

**Issue by FoamyGuy** [OpenShot/openshot-qt#5017]
I've just installed Openshot via the Ubuntu Software center. It seems to have successfully installed but it will not launch. When I try to launch the application from the app drawer nothing happens. 

If I attempt to launch it from the terminal it outputs this errors:
```
❯ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Fri Dec  2 14:24:07 2022            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.10.6
         app:INFO qt5 version: 5.15.3
         app:INFO pyqt5 version: 5.15.6
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to Cantarell
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
     version:INFO Found current version: {"trans_rate_stable": 0.01, "trans_rate_unstable": 0.001, "error_rate_stable": 0.16, "openshot_version": "2.6.1", "error_rate_unstable": 0.05}
```

**Comment by Colorjet3** [comment]
Which version of Ubuntu are you running.  Also, 2.5.1 is very old compared to all of the latest updates.  I highly recommend that you download the latest DEV Daily build AppImage from openshot.org/download/#daily and use this instead.  Uninstall v2.51 as the support for is being limited.

Let us know if you can now launch OpenShot via the latest AppImage.

**Comment by Colorjet3** [comment]
No response from user.
