### ISSUE TITLE
Fails to launch on macOS/MacPorts

### ISSUE THREAD

**Issue by ctreleaven** [OpenShot/openshot-qt#5039]
**Describe the bug:**

I contribute to the MacPorts project and I'm attempting to update our packaging from 2.6.0 to 3.0.0.  Version 2.6.0 installed and functioned correctly under MacPorts.  However, openshot-qt 3.0.0 fails to launch.  Terminal output follows:

```
$ /opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/openshot-qt --debug
Loaded modules from: /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt
INFO sentry: No sentry_sdk module detected (error reporting is disabled)
INFO app: ------------------------------------------------
INFO app:             Tue Dec 13 14:33:23 2022            
INFO app:               Starting new session              
DEBUG app: Command line: ['/opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/openshot-qt']
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
ModuleNotFoundError: No module named 'openshot'
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/launch.py", line 196, in main
    app = OpenShotApp(argv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
ModuleNotFoundError: No module named 'openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==3.0.0', 'gui_scripts', 'openshot-qt')())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/launch.py", line 198, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Tue Dec 13 14:33:23 2022            
INFO app: ================================================
```

Note that MacPorts installs in a 'unix' fashion under the PREFIX "/opt/local"; openshot-qt is not encapsulated in an application bundle.   Information on the 2.6.0 version of openshot-qt under MacPorts is at:

https://ports.macports.org/port/openshot-qt/details/

**System Details:**
macOS 10.15.7 (Catalina)

**Log Files:**
See above

**Exception / Stacktrace:**
N/A

**Comment by ctreleaven** [comment]
I got a step forward but still no joy.  When installing libopenshot, I had incorrectly specified the PYTHON_MODULE_PATH.  After fixing that, though, OpenShot still fails to launch:

```
$ /opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/openshot-qt
Loaded modules from: /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt
INFO sentry: No sentry_sdk module detected (error reporting is disabled)
INFO app: ------------------------------------------------
INFO app:             Wed Dec 14 09:33:31 2022            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.0.0)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.0.0
INFO app: libopenshot version: 0.3.0
INFO app: platform: macOS-10.15.7-x86_64-i386-64bit
INFO app: processor: i386
INFO app: machine: x86_64
INFO app: python version: 3.10.8
INFO app: qt5 version: 5.15.6
INFO app: pyqt5 version: 5.15.7
INFO project_data: Setting default profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 44100, 2 channels
INFO app: checking babl_ext_path: /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/lib/babl-ext
Screen iMac
   devicePixelRatio: 2.0
   logicalDotsPerInch: 72.0
   physicalDotsPerInch: 108.50000162950651
   availableSizes: PyQt5.QtCore.QSize(1998, 1129)
INFO language: Qt Detected Languages: ['en-CA', 'en-Latn-CA']
INFO language: LANG Environment Variable: en_CA.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO app: Setting font to /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
ERROR webview: Import failure loading WebKit backend
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/windows/views/webview.py", line 162, in <module>
    from .webview_backend.webengine import TimelineWebEngineView as WebViewClass
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/windows/views/webview_backend/webengine.py", line 38, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/windows/views/webview.py", line 166, in <module>
    from .webview_backend.webkit import TimelineWebKitView as WebViewClass
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/windows/views/webview_backend/webkit.py", line 36, in <module>
    from PyQt5.QtWebKitWidgets import QWebView, QWebPage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/windows/views/webview.py", line 162, in <module>
    from .webview_backend.webengine import TimelineWebEngineView as WebViewClass
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/windows/views/webview_backend/webengine.py", line 38, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==3.0.0', 'gui_scripts', 'openshot-qt')())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/launch.py", line 218, in main
    app.gui()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/classes/app.py", line 271, in gui
    from windows.main_window import MainWindow
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/windows/main_window.py", line 77, in <module>
    from windows.views.webview import TimelineWebView
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openshot_qt/windows/views/webview.py", line 172, in <module>
    raise RuntimeError(
RuntimeError: Need PyQt5.QtWebEngine (or PyQt5.QtWebView on Win32)
INFO app:             OpenShot's session ended            
INFO app:             Wed Dec 14 09:33:31 2022            
INFO app: ================================================
```

Again, I'm not conversant with Python but isn't this the module it seems to be failing to find?

```
$ file /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/widget-plugins/qtwebkit.py
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/widget-plugins/qtwebkit.py: Python script text executable, ASCII text
```

Craig

**Comment by ctreleaven** [comment]
Argh, that should be:

```
$ file /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/widget-plugins/qtwebenginewidgets.py
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/widget-plugins/qtwebenginewidgets.py: Python script text executable, ASCII text
```

**Comment by Colorjet3** [comment]
Hello @ctreleaven Please go to openshot.org/download/@daily and get the latest DEV Daily Available.  There are known issues with the v3.0.0-Release-Candidate not working on some Windows, Linux, and Mac platforms.  The DEV Daily Build should work.

**Comment by ctreleaven** [comment]
Thanks but I'm building this for inclusion in MacPorts.  MacPorts strongly prefers release tarballs although we sometimes add patches if that is the way to get past a problem.  Is there a specific commit or two that would get this build working?

**Comment by jonoomph** [comment]
@ctreleaven It would appear that you are missing the `PyQt5.QtWebEngineWidgets` python3 module, which is required to load our QtWebEngine-based timeline. We technically support both QtWebKit and QtWebEngine, whichever is detected as installed at runtime. But on Mac, typically this would be QtWebEngine.

**Comment by ctreleaven** [comment]
As I noted on December 14, the module is installed:

```
$ file /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/widget-plugins/qtwebenginewidgets.py
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/widget-plugins/qtwebenginewidgets.py: Python script text executable, ASCII text
```

```
$ ls -l /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/widget-plugins/qtwebenginewidgets.py
-rw-r--r-- 1 macports 1568 Jun 18  2022 /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/widget-plugins/qtwebenginewidgets.py
```

If you tell me the right incantation, I can verify that python3 is able to import the library.  Not sure why openshot is having trouble; all site packages under MacPorts are installed in the same fashion.
