### ISSUE TITLE
AppImage of v3.0 fails if `libthai.so` is missing

### ISSUE THREAD

**Issue by siefkenj** [OpenShot/openshot-qt#5060]
I am running the AppImage of v3.0 on a Gentoo system without `libthai` installed. Openshot fails to open in this case, saying it cannot find `libthai.so`. After installing `libthai`, Openshot will launch, but it seems like this should be an optional dependency, or bundled with the AppImage.

**Comment by amadvance** [comment]
The same happens on my Slackware system.
```

$ /opt/OpenShot-v3.0.0-x86_64.AppImage 
Loaded modules from: /tmp/.mount_OpenShxztjY8/usr/bin
INFO app: ------------------------------------------------
INFO app:             Thu Jan  5 00:13:25 2023            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/tmp/.mount_OpenShxztjY8/usr/bin/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/tmp/.mount_OpenShxztjY8/usr/bin/classes/project_data.py", line 48, in <module>
    import openshot
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gitlab-runner/builds/c8488186/0/OpenShot/openshot-qt/openshot.py", line 15, in <module>
ImportError: libthai.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "openshot_qt/launch.py", line 196, in main
    app = OpenShotApp(argv)
  File "/tmp/.mount_OpenShxztjY8/usr/bin/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/tmp/.mount_OpenShxztjY8/usr/bin/classes/project_data.py", line 48, in <module>
    import openshot
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gitlab-runner/builds/c8488186/0/OpenShot/openshot-qt/openshot.py", line 15, in <module>
ImportError: libthai.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 223, in <module>
    main()
  File "openshot_qt/launch.py", line 198, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Thu Jan  5 00:13:25 2023            
INFO app: ================================================
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by Colorjet3** [comment]
@siefkenj Thank you for the FYI.  I'll ensure that the lead developer sees this and weighs in.

**Comment by Colorjet3** [comment]
@amadvance Did you also try installing libthai?  Did that also resolve the startup issue?

**Comment by amadvance** [comment]
Just tried. After installing libthai, it starts.

Then it crashes when you try to use the UI, but likely it's for another reasons. Even with the latest daily AppImage. I'll try building from source and in case submit a bug report.

**Comment by Colorjet3** [comment]
I was discussing with the lead developer and he indicated that as far as he knows OpenShot is not dependent on libthai.  I wam going to ask him to look into this issue and chime in.

@jonoomph Please take a look at this issue.

**Comment by lockie** [comment]
I'm afraid that's still an issue with 3.0.0 AppImage. I'm using Gentoo and also getting the `libthai.so` message.
