### ISSUE TITLE
Openshot v3.0.0 crashes at start on Ubuntu 22.10

### ISSUE THREAD

**Issue by andreagangemi** [OpenShot/openshot-qt#5073]
**Describe the bug:**
Openshot not starting on Ubuntu 22.10

**Steps to reproduce the behavior:**
run the v3.0.0 AppImage

**Expected behavior:**

Openshot should start

**System Details:**
- OpenShot Version 3.0.0
- Operating System / Distro: Ubuntu 22.10

**Log Files:**
[log_files.zip](https://github.com/OpenShot/openshot-qt/files/10331855/log_files.zip)

**Exception / Stacktrace:**
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_OpenSh1gzDyG/usr/bin/libopenshot.so.23 ( openshot::AudioPlaybackThread::run()      + 0xba  )  [0x7f7281f66fca]
  /tmp/.mount_OpenSh1gzDyG/usr/bin/libopenshot-audio.so.9 ( juce::Thread::threadEntryPoint()          + 0xd9  )  [0x7f7281b73399]
  /tmp/.mount_OpenSh1gzDyG/usr/bin/libopenshot-audio.so.9 (                                           + 0x1734cd)  [0x7f7281b734cd]
  /lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x90402)  [0x7f7283a90402]
  /lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x11f590)  [0x7f7283b1f590]
---- End of Stack Trace ----
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
QObject::~QObject: Timers cannot be stopped from another thread
  /tmp/.mount_OpenSh1gzDyG/usr/bin/libQt5Gui.so.5 (                                           + 0x484480)  [0x7f7281884480]
  /tmp/.mount_OpenSh1gzDyG/usr/bin/libQt5Gui.so.5 ( QOpenGLFunctions::initializeOpenGLFunctions()  + 0xf   )  [0x7f728188467f]
  /tmp/.mount_OpenSh1gzDyG/usr/bin/libQt5Quick.so.5 ( QSGBatchRenderer::Renderer::Renderer(QSGDefaultRenderContext*)  + 0x3f9 )  [0x7f726d1959c9]
  /tmp/.mount_OpenSh1gzDyG/usr/bin/libQt5Quick.so.5 ( QSGDefaultRenderContext::createRenderer()  + 0x26  )  [0x7f726d1c61e6]

...

**Comment by andreagangemi** [comment]
Wonder if the issue is somehow related to pipewire?

**Comment by Colorjet3** [comment]
This is a known bug.  Please go to openshot.org/download/#daily build and get the latest DEV Daily Build.  Let us know if this fixed your issue.

**Comment by andreagangemi** [comment]
> This is a known bug. Please go to openshot.org/download/#daily build and get the latest DEV Daily Build. Let us know if this fixed your issue.

Apologize if I unintentionally created a duplicate, however the similar bug that I found was related to libfuse2, which is installed in my system.
Also, I tried different daily builds and I have a different problem: I get an sound error to fix but I am unable to save the preferences.

**Comment by Colorjet3** [comment]
Hello @andreagangemi 
1.  First of all I would like to know if your crashing issue has been resolved?  Yes/No?
2.  What similar bug are you talking about regarding libfuse2?
3.  Which daily build # are you running?  Just to confirm.
4.  Please elaborate a bit more on the sound error.  Not really understanding what the issue issue and what exactly are you not being able to save in the Preferences?

**Comment by andreagangemi** [comment]
Hello, 
1. I resolved the issue by installing the ubuntustudio-audio packages, (ubuntustudio-audio, aubuntustudio-audio-plugins and linux-lowlatency) basically I circumvented the problem by transforming my ubuntu 22.10 into a sort of ubuntu studio 22.10
2. I was referring to this issue: https://github.com/OpenShot/openshot-qt/issues/5031
3. I was referring  to this [OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64.AppImage](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64.AppImage) from december 22nd
but I tried many other versions
4. Sorry, it's definitely my fault with english, the problem I had with daily build is the following:
- when opeshot starts I get an "audio error please fix the problem" message
- when I open the preferences I change the audio source for preview
- I get a message saying that changes will be applied after restart
- however when I restart openshot, I get the same audio error and the preference that I chosed was not saved.
this in any case is a different issue

**Comment by Colorjet3** [comment]
Hello @andreagangemi Thank you for the update.  I am a very novice Linux user and you have done some things that I wouldn't know how to debug.  I am going to ask one of the DEV team members to look into this issue.

**Comment by smittie** [comment]
Seeing the same issue, missing file is libopenshot.so.23.

What I did:
1. Deleted OpenShot-v3.0.0-daily-11058-8f92bac0-b5bbab66-x86_64.AppImage.
2. Attempt to ensure that all related OpenShot-v3.0.0 files installed by above AppImage were removed (possibly overzealously)
3. Installed from DEV PPA; sudo apt install openshot-qt python3-openshot
4. Attempted to launch openshot from the command line: openshot-qt

Result:

```
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Fri Mar 10 15:23:48 2023            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/lib/python3/dist-packages/openshot.py", line 15, in <module>
    import _openshot
ImportError: libopenshot.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 196, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/lib/python3/dist-packages/openshot.py", line 15, in <module>
    import _openshot
ImportError: libopenshot.so.23: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==3.0.0', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 198, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_openshot-qt.1001.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 196, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/lib/python3/dist-packages/openshot.py", line 15, in <module>
    import _openshot
ImportError: libopenshot.so.23: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==3.0.0', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 198, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Fri Mar 10 15:23:48 2023            
INFO app: ================================================
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```
This issue does reproduce on stable from PPA and DEV build from DEV PPA. This issue does NOT reproduce from either stable or DEV AppImage.

It is entirely possible that I deleted by hand something critical, in which case I apologize.

libopenshot.log contains nothing interesting. openshot-qt.log is attached.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10946705/openshot-qt.log)
