### ISSUE TITLE
OpenShot AppImage crashes on Arch Linux

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5080]
**Replicate**

1. Visit https://www.openshot.org/download/
1. Download https://github.com/OpenShot/openshot-qt/releases/download/v3.0.0/OpenShot-v3.0.0-x86_64.AppImage
1. Run: `chmod +x OpenShot-v3.0.0-x86_64.AppImage`
1. Run: `./OpenShot-v3.0.0-x86_64.AppImage`

**Expected**

Application opens.

**Actual**

```
$ ./OpenShot-v3.0.0-x86_64.AppImage 
Loaded modules from: /tmp/.mount_OpenShpqVbTs/usr/bin
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
INFO app: ------------------------------------------------
INFO app:             Tue Jan  3 12:46:40 2023            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/tmp/.mount_OpenShpqVbTs/usr/bin/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/tmp/.mount_OpenShpqVbTs/usr/bin/classes/project_data.py", line 48, in <module>
    import openshot
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gitlab-runner/builds/c8488186/0/OpenShot/openshot-qt/openshot.py", line 15, in <module>
ImportError: /tmp/.mount_OpenShpqVbTs/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libcairo.so.2)
Traceback (most recent call last):
  File "openshot_qt/launch.py", line 196, in main
    app = OpenShotApp(argv)
  File "/tmp/.mount_OpenShpqVbTs/usr/bin/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/tmp/.mount_OpenShpqVbTs/usr/bin/classes/project_data.py", line 48, in <module>
    import openshot
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gitlab-runner/builds/c8488186/0/OpenShot/openshot-qt/openshot.py", line 15, in <module>
ImportError: /tmp/.mount_OpenShpqVbTs/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libcairo.so.2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 223, in <module>
    main()
  File "openshot_qt/launch.py", line 198, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Tue Jan  3 12:46:40 2023            
INFO app: ================================================
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**System**

``` bash
$ uname -a
Linux hostname 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux
$ python --version
Python 3.10.9
```

**Comment by Colorjet3** [comment]
Please go to openshot.org/download/#daily and get the latest DEV Daily Build available.  This is a known issue and this latest daily build should fix your issue.
