### ISSUE TITLE
Openshot 3.0 doe snot launch on Ubuntu 20.04

### ISSUE THREAD

**Issue by tlhingan** [OpenShot/openshot-qt#5133]
**Describe the bug:**
Openshot 3.0 does not launch on Ubuntu 20.04. The new stable release of Openshot 3.0 for Ubuntu 20.04 requires QT5 5.15, Ubuntu 20.04 maxes out at 5.12.

**Steps to reproduce the behavior:**
1. Install or upgrade openshot
2. Launch
3. See error message
4. See error:
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==3.0.0', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 54, in <module>
    from PyQt5.QtCore import Qt
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/<username>/.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so)

**Expected behavior:**
Openshot should launch

**System Details:**
- OpenShot 3.0.0
- Ubuntu 20.04 LTS

**Comment by Colorjet3** [comment]
Hello @tlhingan Please go to openshot.org/download/#daily and download the latest available AppImage and see if that runs for you.  Most likely we will need the lead developer to take a look this once we get your result.

**Comment by tlhingan** [comment]
The AppImage runs, but I would prefer to run things natively. I am looking into installing QT5 5.15 on Ubuntu 20.04.

**Comment by Colorjet3** [comment]
Sounds good @tlhingan I'll look for your update and we can then decide on the next steps!!!

**Comment by tlhingan** [comment]
> Sounds good @tlhingan I'll look for your update and we can then decide on the next steps!!!

QT5 5.15 ain't happening on Ubuntu 20.04. I tried compiling QT5 from source, I tried compiling libQT5Core from source, I have even tried the "online installer." They all succeeded, but Openshot can't find QT5 5.15. Something is screwy with 5.15 on 20.04, and I can't find what it is.
Does Openshot 3.0 really need QT5 5.15, or did y'all just pick that one version?

**Comment by Colorjet3** [comment]
Hello @tlhingan I am not a developer so I don't know the answer to your question.  I will need to ping someone from the DEV team to look at this issue.

**Comment by tlhingan** [comment]
If Openshot 3.0 really needs QT5 5.15, can we get an older version (2.6.1?) flagged for Ubuntu 20.04? The only install candidate in the PPA for Ubuntu 20.04 is 3.0.

**Comment by Colorjet3** [comment]
Hello @tlhingan You can find older versions here:  https://openshot-video-editor.en.uptodown.com/windows/versions

**Comment by tlhingan** [comment]
> Hello @tlhingan You can find older versions here: https://openshot-video-editor.en.uptodown.com/windows/versions

That's the Windows version.

**Comment by Colorjet3** [comment]
@tlhingan Oops, sorry about that.  I thought all platforms will be included.  Let me find out and get back to you.

**Comment by Colorjet3** [comment]
@tlhingan While I am waiting to hear back from the dev team you can go to openshot.org/download/#daily.  On the bottom of the page click on More...  You will see a list of v2.6.1-Daily builds.  I would pick one of the earliest ones (build #8960 dated January 6, 2022) to try for now.

Stay tuned....

**Comment by tlhingan** [comment]
> @tlhingan While I am waiting to hear back from the dev team you can go to openshot.org/download/#daily. On the bottom of the page click on More... You will see a list of v2.6.1-Daily builds. I would pick one of the earliest ones (build #8960 dated January 6, 2022) to try for now.
> 
> Stay tuned....

You keep sending me to AppImages :)
The 3.0 AppImage works, I am asking for packages in the repo so this can be run natively.

**Comment by Colorjet3** [comment]
Hello @tlhingan v3.1.1 Official Release has been published.  Please try this:

# sudo apt purge openshot-qt
# sudo apt autoremove
# sudo apt-add-repository ppa:openshot.developers/ppa
# sudo apt update
# sudo apt install openshot-qt

**Comment by tlhingan** [comment]
Still the same issue, Openshot only launches on Ubuntu 20.04 from AppImage.

**Comment by Colorjet3** [comment]
Hello @tlhingan.  Are you seeing the same error message that you reported when you first submitted this ticket?  Obviously, it would have  v3.1.1 instead of v3.0.0 references.

Traceback (most recent call last):
File "/usr/bin/openshot-qt", line 11, in
load_entry_point('openshot-qt==3.0.0', 'gui_scripts', 'openshot-qt')()
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 490, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 2854, in load_entry_point
return ep.load()
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 2445, in load
return self.resolve()
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 2451, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 54, in
from PyQt5.QtCore import Qt
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home//.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so)

Please do this so we can get some more log data:
0.  Close Openshot if running (the AppImage).
1.  Go to /home/.openshot_qt folder.
2.  Delete libopenshot.log and openshot-qt.log files.
3.  edit openshot.settings file with a text editor.
4.  Search for "debug" excluding the quotes.
5. Please be careful not to change anything accidentally in this file.
6.  You should find a line that says: "title": "Debug Mode (Verbose)",
7.  Above this line you will find: "value": false,
8.  Change false, to true,   <---please note that the comma must stay.
9.  Save openshot.settings file and exit
10.  Start Openshot using the shortcut.
11. Now attach libopenshot.log and openshot-qt.log files.

Thank you in advance!

**Comment by tlhingan** [comment]
The log is empty.

**Comment by tlhingan** [comment]
I get this:
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)

**Comment by Colorjet3** [comment]
Hello @tlhingan Please check this out:  https://github.com/biolab/orange3/issues/5974

**Comment by tlhingan** [comment]
> Hello @tlhingan Please check this out: [biolab/orange3#5974](https://github.com/biolab/orange3/issues/5974)

I installed all the libraries on that post (I was only missing 1), still same error.

**Comment by Colorjet3** [comment]
Hello @tlhingan.  The DEV team will have to look at this issue.  They have been assigned to this issue.
