### ISSUE TITLE
After installing 3.1.0 in Ubuntu 20.04 from official PPA I get a Segmentation Fault ...

### ISSUE THREAD

**Issue by pmo-19** [OpenShot/openshot-qt#5194]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by pmo-19** [comment]
I am using /usr/bin/python3.8 version ...

from reading other bug reports in python 3.1 I understand the trouble is there ...

**Comment by smittie** [comment]
1. Had OpenShot 3.0 installed from Stable PPA.
2. Ran sudo apt update; sudo apt upgrade, noticed that OpenShot was in the list to be upgraded.
3. Launched OpenShot via the command line.
4. SegFault
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11193968/libopenshot.log)

Linux Mint 21.1
Python 3.10.6

[OpenShot bug #5194 Stacktrace.txt](https://github.com/OpenShot/openshot-qt/files/11193950/OpenShot.bug.5194.Stacktrace.txt)

[openshot.settings.txt](https://github.com/OpenShot/openshot-qt/files/11193974/openshot.settings.txt)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11193975/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11193976/openshot-qt.log)

**Comment by smittie** [comment]
1. sudo apt purge openshot-qt python3-openshot (removing the upgraded install of OpenShot)
2. sudo apt install openshot-qt python3-openshot

OpenShot launches without issue. 

Saved the ~/.openshot_qt/openshot.settings for purging the failing install of openshot. Restored settings using saved copy which restores previous settings. (on Linux Mint).

**Comment by pmo-19** [comment]
Purging and reinstalling from the Stable PPA (Contains only official releases) gives the very Core Dump for Segmentation Fault ...

**Comment by pmo-19** [comment]
Well. I did jut build the new version 3.1.0 packages of openshot-qt and all its dependencies with help from debian sid debian folders. All the builds wre smooth.

This time I have a hint of why it crashes. It looks like the Qt5 versions are not compatible ...

$ openshot-qt
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
qt5ct: using qt5ct plugin
INFO app: ------------------------------------------------
INFO app:             Mon Apr 10 20:20:53 2023            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.1.0)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.1.0
INFO app: libopenshot version: 0.2.7
INFO app: platform: Linux-5.13.0-48-generic-x86_64-with-glibc2.29
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.8.10
INFO app: qt5 version: 5.12.8
INFO app: pyqt5 version: 5.14.1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 196, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 131, in __init__
    self.project = project_data.ProjectDataStore()
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 66, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 291, in new
    profile = self.get_profile(profile_desc=default_profile_desc)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 341, in get_profile
    if legacy_profile and legacy_profile.Key() == temp_profile.Key():
AttributeError: 'Profile' object has no attribute 'Key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==3.1.0', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 198, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Mon Apr 10 20:20:53 2023            
INFO app: ================================================
$ 

Trouble lays with openshot-qt all other packages are stock Ubuntu / Debian.
