### ISSUE TITLE
undefined symbol: _ZdaPvm, version Qt_5 

### ISSUE THREAD

**Issue by GiorgosXou** [OpenShot/openshot-qt#5214]
I am just trying to install `openshot` on Arch via `sudo pacman -Syu openshot` and when I run `openshot-qt` i get this error
```terminal
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 5, in <module>
    from openshot_qt.launch import main
  File "/usr/lib/python3.10/site-packages/openshot_qt/launch.py", line 54, in <module>
    from PyQt5.QtCore import Qt
ImportError: /home/xou/.local/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdaPvm, version Qt_5
```

**Comment by GiorgosXou** [comment]
[Fixed by](https://stackoverflow.com/a/68811630/11465149):
```
pip uninstall pyqt5
```
```
sudo pacman -S pyqt5
```
