### ISSUE TITLE
Crash opening files in OpenShot AppImage 3.1.1 

### ISSUE THREAD

**Issue by John-Nagle** [OpenShot/openshot-qt#5228]
**Describe the bug:**
Crashes opening an existing project when running from the Linux AppImage version.

**Steps to reproduce the behavior:**
Tried to open a project created with OpenShot 2.4.3 using the new OpenShot 3.1.1

**Expected behavior:**
Not crashing.

**System Details:**
- OpenShot Version 3.1.1 (Linux x64, AppImage)
- 
- Operating System / Distro: [Ubuntu Linux 20.04 LTS]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

INFO project_data: Loading project file: /home/john/Videos/ff2023.osp
ERROR json_data: Error while converting relative paths to absolute paths
Traceback (most recent call last):
  File "/tmp/.mount_OpenShKidh1h/usr/bin/classes/json_data.py", line 275, in convert_paths_to_absolute
    data = re.sub(path_regex, self.replace_string_to_absolute, data)
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/tmp/.mount_OpenShKidh1h/usr/bin/classes/json_data.py", line 241, in replace_string_to_absolute
    path = json.loads('"%s"' % path)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)

===
terminate called after throwing an instance of 'openshot::InvalidFile'
  what():  File could not be opened.
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libc.so.6 ( abort                                     + 0x12b )  [0x7f3aa268e859]

[openshot-file-open-crash.txt](https://github.com/OpenShot/openshot-qt/files/11358264/openshot-file-open-crash.txt)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11358268/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11358269/openshot-qt.log)

**Comment by Colorjet3** [comment]
@John-Nagle Upgrades to v3.x.x were only tested from 2.51, 2.6.0, and 2.6.1.  And even then you could run into any issues.  I am not sure if you took a backup of /home/username/.openshot_qt folder before you executed v3.1.1 AppImage but you may not be able to gracefully recover as well.

Give this a try:
1.  Start v2.4.3 and open your project and perform a Save Project As... and save it as test01.osp.
2.  Make a backup of /home/username/.openshot_qt.
3.  Below I have provided links to previous versions.
a.  Download 2.5.0 AppImage, start it and open test01.osp.  If it opened, then save the project once.  Just the same name.  Close Openshot.
b.  Make a backup of /home/username/.openshot_qt folder...don't override the backup from step 2 above.  Keep them both.
c.  Download 2.6.0 Appimage, start it and open test01.osp.  If it opened, then save the project once.  Just the same name.  Close Openshot.
d.  Make a backup of /home/username/.openshot_qt folder...don't override the backup from step 3.b.  Keep them all.
e.  Now run v3.1.1 AppImage and open test01.osp.  If it worked, then you know what you need to do.
f.   if it didn't work, then close openshot.  Delete /home/username/.openshot_qt folder.  Start v3.1.1 AppImage and open your project.

Let us know the results.

**Comment by John-Nagle** [comment]
Did all that.
The result doesn't crash, and the video edit info is still there, but the titles lost their fonts.

**Comment by Colorjet3** [comment]
Hello @John-Nagle That is great that Openshot no longer crashes and the video edit info is still there.  The Font issue is not something we can easily fix due to the upgrade path and changes to how the fonts work.  You just have to reset the fonts.

If you are using Static Titles then right click on your title file in the "project files" window and select "Edit Title" and change the Font.

If they are animated Titles then you will most likely have to recreate those.

If all is good then please go ahead and close this ticket.
