### ISSUE TITLE
OpenShot crashes after file import on Ubuntu 22.04

### ISSUE THREAD

**Issue by SzilvasiPeter** [OpenShot/openshot-qt#5239]
**Describe the bug:**
OpenShot crashes after importing an _mp4_ file from the file dialog menu.  I have installed OpenShot following the [ppa installation](https://www.openshot.org/static/files/user-guide/installation.html#linux-ppa) steps.

**Steps to reproduce the behavior:**
1. Open the application with the `openshot-qt` command.
2. Right-click on **Project Files** panel then click on **Import Files...** option. 
3. Select an _mp4_ video.
4. OpenShot crashes.

**Expected behavior:**
OpenShot imports the files into the **Project Files** menu,

**System Details:**
- OpenShot Version: 3.1.1
- Operating System / Distro: Ubuntu 22.04.2 LTS

**Log Files:**
Information

```
INFO app: openshot-qt version: 3.1.1
INFO app: libopenshot version: 0.3.2
INFO app: platform: Linux-5.19.0-41-generic-x86_64-with-glibc2.35
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.6
INFO app: qt5 version: 5.15.3
INFO app: pyqt5 version: 5.15.6
```

Errors

`ERROR main_window: Unhandled crash detected: linux-/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value const 0x16 [0x7f23babaf9a6]`

Warning

`WARNING preview_thread: Your active audio device (||) does not match OpenShot (). Adjusting your 'Preferences->Playback->Audio Device' to match your active audio device: ||`

**Exception / Stacktrace:**
```
---- Unhandled Exception: Stack Trace ----
  /usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so ( swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value() const  + 0x16  )  [0x7f5313faf9a6]
  /usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so (                                           + 0xbcf6d)  [0x7f5313ebcf6d]
  /usr/bin/python3               (                                           + 0x15c3a4)  [0x55b7182f83a4]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a40)  [0x55b7182e3af0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55b7182f91ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x55b7182e18cb]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55b7182f91ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6d5 )  [0x55b7182e1785]
  /usr/bin/python3               (                                           + 0x16ac31)  [0x55b718306c31]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6d5 )  [0x55b7182e1785]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55b7182f91ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x55b7182e18cb]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55b7182f91ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x55b7182e18cb]
  /usr/bin/python3               ( _PyObject_FastCallDictTstate              + 0xc4  )  [0x55b7182ee634]
  /usr/bin/python3               (                                           + 0x166e94)  [0x55b718302e94]
  /usr/bin/python3               ( _PyObject_MakeTpCall                      + 0x1fc )  [0x55b7182ef44c]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6db6)  [0x55b7182e7e66]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55b7182f91ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x55b7182e18cb]
  /usr/bin/python3               (                                           + 0x16ad7e)  [0x55b718306d7e]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a40)  [0x55b7182e3af0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55b7182f91ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a40)  [0x55b7182e3af0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55b7182f91ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x63b2)  [0x55b7182e7462]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55b7182f91ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x55b7182e18cb]
  /usr/bin/python3               (                                           + 0x16ae91)  [0x55b718306e91]
  /usr/bin/python3               (                                           + 0x296e5b)  [0x55b718432e5b]
  /usr/bin/python3               (                                           + 0x28cf58)  [0x55b718428f58]
  /lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x94b43)  [0x7f5315a94b43]
  /lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x126a00)  [0x7f5315b26a00]
---- End of Stack Trace ----
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by Colorjet3** [comment]
Hello @SzilvasiPeter I have assigned this issue to the lead IT Technical Support and the Lead Developer to look into.  Meanwhile, please download the latest DEV Daily Build AppImage and see if Openshot works:

1.  Go to openshot.org/download/#daily and download Build #11427.
2.  Make it executable and run it.

Let us know the result.

**Comment by SzilvasiPeter** [comment]
Hi @Colorjet3, can you provide the Build #11427 AppImage full name? I am unable to find the corresponding release using the 11427 build number.

**Comment by Colorjet3** [comment]
Hello @SzilvasiPeter.  Daily Build #11447 was just released with a minor unrelated fix to this issue so give this a try:  https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.1.1-daily-11447-431d335a-dce55693-x86_64.AppImage

**Comment by Colorjet3** [comment]
Hello @SzilvasiPeter Were you able to download Daily Build #11447?  I am closing this ticket for now unless I hear differently from you.

**Comment by SzilvasiPeter** [comment]
Sorry for the delayed respond. Meanwhile I switched to another video editor software on a different OS. That is why I did not download the build. The issue can be closed.

**Comment by Colorjet3** [comment]
No worries @SzilvasiPeter and thank you for the update.  Best of luck with your projects.

Give Openshot a try again in the future as more fixes and enhancements will be added in upcoming releases.

Take care!

**Comment by thesp0nge** [comment]
Please don't close this issue. It happens also to me either on openSUSE Tumbleweed and openSUSE Leap 15.5 release candidate

**Comment by thesp0nge** [comment]
It happens on 3.1, 3.1.1 and latest dailybuild

**Comment by thesp0nge** [comment]
```
INFO files_model: Imported media file file.MP4
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /lib64/libpython3.10.so.1.0    ( PyTuple_New                               + 0x17  )  [0x7feccc90a1b7]
  /usr/lib64/python3.10/site-packages/_openshot.so (                                           + 0x1762c2)  [0x7feccb5762c2]
  /usr/lib64/python3.10/site-packages/_openshot.so (                                           + 0x943f8)  [0x7feccb4943f8]
  /lib64/libpython3.10.so.1.0    (                                           + 0x1252b2)  [0x7feccc9252b2]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x2bb3)  [0x7feccc91da03]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x649 )  [0x7feccc91b499]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x33c )  [0x7feccc91b18c]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    (                                           + 0x12c894)  [0x7feccc92c894]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x33c )  [0x7feccc91b18c]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x649 )  [0x7feccc91b499]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x649 )  [0x7feccc91b499]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    ( _PyObject_FastCallDictTstate              + 0x9f  )  [0x7feccc92230f]
  /lib64/libpython3.10.so.1.0    (                                           + 0x12b054)  [0x7feccc92b054]
  /lib64/libpython3.10.so.1.0    (                                           + 0x122cc3)  [0x7feccc922cc3]
  /lib64/libpython3.10.so.1.0    ( _PyObject_MakeTpCall                      + 0x74  )  [0x7feccc922a54]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x5422)  [0x7feccc920272]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x649 )  [0x7feccc91b499]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    (                                           + 0x12c97b)  [0x7feccc92c97b]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x2bb3)  [0x7feccc91da03]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x649 )  [0x7feccc91b499]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    ( _PyEval_EvalFrameDefault                  + 0x649 )  [0x7feccc91b499]
  /lib64/libpython3.10.so.1.0    (                                           + 0x11a07a)  [0x7feccc91a07a]
  /lib64/libpython3.10.so.1.0    (                                           + 0x12ca21)  [0x7feccc92ca21]
  /lib64/libpython3.10.so.1.0    (                                           + 0x1d8443)  [0x7feccc9d8443]
  /lib64/libpython3.10.so.1.0    (                                           + 0x1b21e4)  [0x7feccc9b21e4]
  /lib64/libc.so.6               (                                           + 0x8dab4)  [0x7feccc692ab4]
  /lib64/libc.so.6               (                                           + 0x114b60)  [0x7feccc719b60]
---- End of Stack Trace ----
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by Colorjet3** [comment]
@sc0nway or @jonoomph This needs your attention, please!

**Comment by thesp0nge** [comment]
@Colorjet3 thanks for reopening the bug :+1: 

I would also mention that I use also the Flatpak package and it happens the same issue on lib python

**Comment by thesp0nge** [comment]
HTH. If from Nautilus you choose to open an MP4 video with openshot, the program doesn't crash. It seems related only to drag and drop on project files.

**Comment by zie1ony** [comment]
Same here. PopOS 22.04. Build from PPA: `3.1.1+dfsg2+1650+202304212058~ubuntu22.04.1`

There must be something wrong with file reader. I've found that when I load a video file into Shotcut, it tells me that it has unfriendly encoding and proposes to convert it. After conversion I can import it to OpenShot just fine.

**Comment by T-McBride** [comment]
Gentoo Linux, same error with 3.11 and 3.10 builds as target. 

### From Build: 

```
Loaded modules from: /usr/lib/python3.11/site-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Mon Jun 19 02:22:45 2023            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 2.6.1)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1
INFO app: libopenshot version: 0.2.7
INFO app: platform: Linux-6.1.28-gentoo-x86_64-Intel-R-_Core-TM-_i7-4770K_CPU_@_3.50GHz-with-glibc2.36
INFO app: processor: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
INFO app: machine: x86_64
INFO app: python version: 3.11.3
INFO app: qt5 version: 5.15.9
INFO app: pyqt5 version: 5.15.9
INFO project_data: Setting default profile to HD 720p 30 fps
INFO language: Qt Detected Languages: ['en-US', 'en', 'en-Latn-US']
INFO language: LANG Environment Variable: en_US.utf8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO app: Setting font to /usr/lib/python3.11/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO app: Setting custom dark theme
INFO ui_util: Initializing UI for MainWindow
Could not create scene graph context for backend 'opengl' - check that plugins are installed correctly in /usr/lib64/qt5/plugins
INFO webengine: WebEngine backend initializing
INFO thumbnail: Starting thumbnail server listening on port 51719
INFO transition_model: updating transitions model.
INFO effects_model: updating effects model.
INFO emoji_model: updating emoji model.
INFO main_window: InitCacheSettings
INFO main_window: cache-mode: CacheMemory
INFO main_window: cache-limit-mb: 250
INFO main_window: Creating CacheMemory object with 262144000 byte limit
INFO preview_thread: QThread Start Method Invoked
INFO version: Found current version: {'trans_rate_stable': 0.01, 'openshot_version': '3.1.1', 'trans_rate_unstable': 0.001, 'error_rate_unstable': 0.05, 'error_rate_stable': 0.25}
ERROR main_window: Unhandled crash detected: linux-/lib64/libc.so.6 gsignal 0x12 [0x7ff1579eafa2]
INFO main_window: updateStatusChanged
INFO main_window: recover_backup
INFO project_data: Setting default profile to HD 720p 30 fps
INFO preview_thread: player Position(): 1
INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
INFO video_widget: Set video widget pixel aspect ratio to: 1.0
INFO main_window: updateStatusChanged
Unhandled Python exception
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
  /lib64/libc.so.6               ( gsignal                                   + 0x12  )  [0x7efd61415fa2]
  /lib64/libc.so.6               ( abort                                     + 0xd3  )  [0x7efd61400472]
  /usr/lib64/libQt5Core.so.5     (                                           + 0x91d5d)  [0x7efd60064d5d]
  /usr/lib/python3.11/site-packages/PyQt5/QtCore.abi3.so (                                           + 0xb6257)  [0x7efd60606257]
  /usr/lib/python3.11/site-packages/PyQt5/sip.cpython-311-x86_64-linux-gnu.so (                                           + 0x12c04)  [0x7efd6053ac04]
  /usr/lib/python3.11/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x14dead)  [0x7efd5d3f8ead]
  /usr/lib/python3.11/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x3d3d2b)  [0x7efd5d67ed2b]
  /usr/lib64/libQt5Widgets.so.5  ( QWidget::event(QEvent*)                   + 0x1a8 )  [0x7efd5cd794f8]
  /usr/lib/python3.11/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x3d64e3)  [0x7efd5d6814e3]
  /usr/lib64/libQt5Widgets.so.5  ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x7e  )  [0x7efd5cd372be]
  /usr/lib/python3.11/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x39642e)  [0x7efd5d64142e]
  /usr/lib64/libQt5Core.so.5     ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x138 )  [0x7efd6024d1f8]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::sendPaintEvent(QRegion const&)  + 0x35  )  [0x7efd5cd716a5]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x8eb )  [0x7efd5cd71feb]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x541 )  [0x7efd5cd733a1]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x556 )  [0x7efd5cd71c56]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x541 )  [0x7efd5cd733a1]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x556 )  [0x7efd5cd71c56]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x541 )  [0x7efd5cd733a1]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x386 )  [0x7efd5cd731e6]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x386 )  [0x7efd5cd731e6]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x386 )  [0x7efd5cd731e6]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x386 )  [0x7efd5cd731e6]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x386 )  [0x7efd5cd731e6]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x386 )  [0x7efd5cd731e6]
  /usr/lib64/libQt5Widgets.so.5  ( QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x556 )  [0x7efd5cd71c56]
  /usr/lib64/libQt5Widgets.so.5  (                                           + 0x174347)  [0x7efd5cd48347]
  /usr/lib64/libQt5Widgets.so.5  (                                           + 0x174b8a)  [0x7efd5cd48b8a]
  /usr/lib64/libQt5Widgets.so.5  (                                           + 0x1c19eb)  [0x7efd5cd959eb]
  /usr/lib64/libQt5Widgets.so.5  ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x7e  )  [0x7efd5cd372be]
  /usr/lib/python3.11/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x39642e)  [0x7efd5d64142e]
  /usr/lib64/libQt5Core.so.5     ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x138 )  [0x7efd6024d1f8]
  /usr/lib64/libQt5Gui.so.5      ( QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*)  + 0x91  )  [0x7efd5c71d381]
  /usr/lib64/libQt5Gui.so.5      ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0xab  )  [0x7efd5c6fbb3b]
  /usr/lib64/libQt5XcbQpa.so.5   (                                           + 0x6868a)  [0x7efd51bea68a]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_dispatch                   + 0x2ac )  [0x7efd5f703fdc]
  /usr/lib64/libglib-2.0.so.0    (                                           + 0x5a278)  [0x7efd5f704278]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_iteration                  + 0x2c  )  [0x7efd5f70430c]
  /usr/lib64/libQt5Core.so.5     ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x66  )  [0x7efd6029d2c6]
  /usr/lib64/libQt5Core.so.5     ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x12b )  [0x7efd6024bcab]
  /usr/lib64/libQt5Core.so.5     ( QCoreApplication::exec()                  + 0x96  )  [0x7efd60253c46]
  /usr/lib/python3.11/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x39513d)  [0x7efd5d64013d]
  /usr/lib64/libpython3.11.so.1.0 (                                           + 0x18d7a2)  [0x7efd6173b7a2]
  /usr/lib64/libpython3.11.so.1.0 ( _PyObject_MakeTpCall                      + 0x8b  )  [0x7efd616fa0bb]
  /usr/lib64/libpython3.11.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x67b9)  [0x7efd616ae2b9]
  /usr/lib64/libpython3.11.so.1.0 (                                           + 0x21f9a0)  [0x7efd617cd9a0]
  /usr/lib64/libpython3.11.so.1.0 ( PyEval_EvalCode                           + 0xad  )  [0x7efd617cda5d]
  /usr/lib64/libpython3.11.so.1.0 (                                           + 0x25fcf3)  [0x7efd6180dcf3]
  /usr/lib64/libpython3.11.so.1.0 (                                           + 0x25ff87)  [0x7efd6180df87]
  /usr/lib64/libpython3.11.so.1.0 (                                           + 0x26006f)  [0x7efd6180e06f]
  /usr/lib64/libpython3.11.so.1.0 ( _PyRun_SimpleFileObject                   + 0x11c )  [0x7efd6181097c]
  /usr/lib64/libpython3.11.so.1.0 ( _PyRun_AnyFileObject                      + 0x3b  )  [0x7efd61810e4b]
  /usr/lib64/libpython3.11.so.1.0 ( Py_RunMain                                + 0x818 )  [0x7efd6182db38]
  /usr/lib64/libpython3.11.so.1.0 ( Py_BytesMain                              + 0x5a  )  [0x7efd6182e0da]
  /lib64/libc.so.6               (                                           + 0x232ca)  [0x7efd614012ca]
  /lib64/libc.so.6               ( __libc_start_main                         + 0x7c  )  [0x7efd6140137c]
  /usr/bin/python3.11            ( _start                                    + 0x21  )  [0x565148e57081]
---- End of Stack Trace ----

```

### Error from AppImage 
https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.1.1-daily-11447-431d335a-dce55693-x86_64.AppImage :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShIPCWdn/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib64/libharfbuzz.so.0)

```

**Comment by Colorjet3** [comment]
A new dev daily build #11732 AppImage has been release to address the GLIBC issue.  Please go to openshot.org/download/#daily and get this AppImage and give it a try.

**Comment by jonoomph** [comment]
Fixed in https://github.com/OpenShot/openshot-qt/pull/5423
