### ISSUE TITLE
Openshot-Qt does not start

### ISSUE THREAD

**Issue by armengot** [OpenShot/openshot-qt#5242]
Bad luck with deb packages on Ubuntu 22.04 and Linux Mint 21.1
I had no problem with Ubuntu 20.04 deb packages.

After problemas, I tried to start from source code, following the instructions: https://www.openshot.org/static/files/user-guide/developers.html

Here the last output:

`Loaded modules from: /home/marcelo/dev/home/openshot-qt/src
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
INFO app: ------------------------------------------------
INFO app:             Sat May 20 19:23:54 2023            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.1.1)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.1.1
INFO app: libopenshot version: 0.2.5
INFO app: platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.6
INFO app: qt5 version: 5.15.3
INFO app: pyqt5 version: 5.15.6
Traceback (most recent call last):
  File "/home/marcelo/dev/home/openshot-qt/src/launch.py", line 196, in main
    app = OpenShotApp(argv)
  File "/home/marcelo/dev/home/openshot-qt/src/classes/app.py", line 131, in __init__
    self.project = project_data.ProjectDataStore()
  File "/home/marcelo/dev/home/openshot-qt/src/classes/project_data.py", line 66, in __init__
    self.new()
  File "/home/marcelo/dev/home/openshot-qt/src/classes/project_data.py", line 291, in new
    profile = self.get_profile(profile_desc=default_profile_desc)
  File "/home/marcelo/dev/home/openshot-qt/src/classes/project_data.py", line 340, in get_profile
    if legacy_profile and legacy_profile.Key() == temp_profile.Key():
AttributeError: 'Profile' object has no attribute 'Key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcelo/dev/home/openshot-qt/src/launch.py", line 223, in <module>
    main()
  File "/home/marcelo/dev/home/openshot-qt/src/launch.py", line 198, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Sat May 20 19:23:54 2023            
INFO app: ================================================
`

**Comment by Colorjet3** [comment]
Hello @armengot.  Please try this:
sudo apt purge openshot-qt
sudo apt autoremove
sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt update
sudo apt install openshot-qt

Find the Openshot shortcut and start it that way.

**Comment by armengot** [comment]
Thanks @Colorjet3 but I'm sorry, same error:
`AttributeError: 'Profile' object has no attribute 'Key'`

**Comment by Colorjet3** [comment]
Hello @armengot One more thing to try and then I will need to escalate this to the lead developer:
1. make a backup of /home/username/.opeshot_qt folder.
2. delete /home/username/.openshot_qt folder.
3. From a terminal run this command:  sudo apt install libfuse2
4. Start Openshot.

**Comment by armengot** [comment]
Thanks, I made it, but it didn't work.
