### ISSUE TITLE
Fails to Open (TypeError)

### ISSUE THREAD

**Issue by winrid** [OpenShot/openshot-qt#5361]
**Steps to reproduce the behavior:**
1. Install app.
2. Try to start it.

**Expected behavior:**
Application fails to start.

**System Details:**
```
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
winrid@pop-os:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

**Exception / Stacktrace:**
```
winrid@pop-os:~$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Wed Nov 22 13:13:17 2023            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.10.12
         app:INFO qt5 version: 5.15.3
         app:INFO pyqt5 version: 5.15.6
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to Cantarell
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
     version:INFO Found current version: {"trans_rate_unstable": 0.001, "trans_rate_stable": 0.01, "openshot_version": "3.1.1", "error_rate_stable": 0.25, "error_rate_unstable": 0.05}

```

**Comment by Colorjet3** [comment]
1.  Go to openshot.org/download/#daily.
2.  Download the latest DEV Daily build of v3.1.1.
3.  Make the AppImage executable and run it.

If you receive an error message regarding "libufse2" the execute this from a Terminal window:  sudo apt install libfuse2.

Now run the AppImage again.

**Comment by winrid** [comment]
I switched to another editor because it didn't work. Just thought I'd let you know this is an issue with latest deb package.
