### ISSUE TITLE
Fresh Install, fails to start with ImportError: /usr/lib/libcblas.so.3: undefined symbol: ssyrk_64_

### ISSUE THREAD

**Issue by Khris777** [OpenShot/openshot-qt#5366]
**Describe the bug:**
I installed openshot for the first time with pacman on EndeavorOS (Arch), it's this package: https://archlinux.org/packages/extra/any/openshot/
The program does not start. 
When executing openshot-qt in the console I get this error message:

```
Loaded modules from: /usr/lib/python3.11/site-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Sun Nov 26 09:31:32 2023            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/usr/lib/python3.11/site-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/lib/python3.11/site-packages/openshot.py", line 12, in <module>
    import _openshot
ImportError: /usr/lib/libcblas.so.3: undefined symbol: ssyrk_64_
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/openshot_qt/launch.py", line 196, in main
    app = OpenShotApp(argv)
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/usr/lib/python3.11/site-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/lib/python3.11/site-packages/openshot.py", line 12, in <module>
    import _openshot
ImportError: /usr/lib/libcblas.so.3: undefined symbol: ssyrk_64_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/openshot_qt/launch.py", line 198, in main
    app.show_errors()
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Sun Nov 26 09:31:32 2023            
INFO app: ================================================
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

The library cblas just got updated from version 3.11 to 3.12.

EDIT: I get the exact same problem with a new install of Inkscape, so it's possible that something in cblas got screwed up and this doesn't belong here.

**Steps to reproduce the behavior:**
Perform a fresh install with pacman on EndeavorOS (or probably any system that uses pacman).

**Expected behavior:**
Program should start.

**System Details:**
- OpenShot Version: 3.1.1
- Operating System / Distro: EndeavorOS, Kernel 6.1.62-1-lts

**Log File:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/13466309/openshot-qt.log)

**Comment by Khris777** [comment]
Update: I downgraded the library to version 3.11 and now it works. I don't know whose issues this is to fix, so I also created an issue with the [cblas people](https://github.com/Reference-LAPACK/lapack/issues/947).
