### ISSUE TITLE
--------

### ISSUE THREAD

**Issue by MatanzaBR** [OpenShot/openshot-qt#5479]

**Comment by Colorjet3** [comment]
Don't have any experience with Void Linux and a very novice Linux user to begin with.

Give this a try:
1.  Go to openshot.org/download/#daily and download the latest DEV Daily Build AppImage.
2.  Make it executable and run it.

**Comment by tuxslack** [comment]
> Don't have any experience with Void Linux and a very novice Linux user to begin with.
> 
> Give this a try:
> 
>     1. Go to openshot.org/download/#daily and download the latest DEV Daily Build AppImage.
> 
>     2. Make it executable and run it.



mkdir -p /opt/openshot && cd /opt/openshot && wget -c https://github.com/OpenShot/openshot-qt/releases/download/v3.1.1/OpenShot-v3.1.1-x86_64.AppImage

chmod +x /opt/openshot/OpenShot-v3.1.1-x86_64.AppImage


$ cd /opt/openshot/ && ./OpenShot-v3.1.1-x86_64.AppImage 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShQDhptj/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libharfbuzz.so.0)

**Comment by Colorjet3** [comment]
The GlibC issue has been resolved in the latest DEV Daily Build .  You don't need to perform all these steps.  Just go to openshot.org/download/#daily and get the latest DEV daily build AppImage.

**Comment by tuxslack** [comment]
> The GlibC issue has been resolved in the latest DEV Daily Build . You don't need to perform all these steps. Just go to openshot.org/download/#daily and get the latest DEV daily build AppImage.

I'm using OpenShot-v3.1.1-x86_64.AppImage created on 03/15/2024

Which file is working on the website.
 

![versao openshot](https://github.com/OpenShot/openshot-qt/assets/33039864/6ee41d96-8601-4a81-9dcf-238de8beeade)

Which .AppImage file does glibc-2.39_2 have?

Thanks

**Comment by Colorjet3** [comment]
I don't believe it is glibc-2.39_2 issue.  What happens is that OpenShot expects glibc_2.35 and the AppImage didn't have that version included.  So what would happen is that it would find whatever version the operating system contained which would then cause issue for OpenShot.

Stay with build #11909.  It has many more fixes and improvements besides the Glibc issue.

See this as well for the glibc fix by the lead developer:  https://github.com/OpenShot/openshot-qt/pull/5423

**Comment by Colorjet3** [comment]
Hello @tuxslack This issue does not belong in this thread.  It would be great if you start a new posting.  With that said here is what you should try:

1.  In Edit | Preferences | Preview tab, change the "Playback Audio Device" to Default.
2.  Restart OpenShot.
3.  See if the error goes away.

**Comment by tuxslack** [comment]
> Hello @tuxslack This issue does not belong in this thread. It would be great if you start a new posting. With that said here is what you should try:
> 
>     1. In Edit | Preferences | Preview tab, change the "Playback Audio Device" to Default.
> 
>     2. Restart OpenShot.
> 
>     3. See if the error goes away.

Changing the audio device is not saved after restarting OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-8e9d7edc-x86_64.AppImage returns as before.

I've done these procedures before and even used the command:

# chmod -R 777 /opt/openshot/

Changes to settings are not saved.

Where does OpenShot save user settings?

**Comment by Colorjet3** [comment]
In Windows environments it is saved at c:\users\username/.openshot_qt folder.

In the Linux world it should be saved at /home/username/.openshot_qt folder.

What operating system are you running?

**Comment by tuxslack** [comment]
Audio configuration is not saved even using the rm -Rf ~/.openshot_qt/ command did not solve the problem.

When restarting, it always returns as is in the default .AppImage file.


$ ./OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-8e9d7edc-x86_64.AppImage 
Loaded modules from: /tmp/.mount_OpenShcd1kKc/usr/bin
INFO app: ------------------------------------------------
INFO app:             Fri Mar 29 10:16:56 2024            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:           OpenShot (version 3.1.1-dev)          
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.1.1-dev
INFO app: libopenshot version: 0.3.2
INFO app: platform: Linux-6.6.22_1-x86_64-with-glibc2.4
INFO app: processor: 
INFO app: machine: x86_64
INFO app: python version: 3.8.10
INFO app: qt5 version: 5.12.8
INFO app: pyqt5 version: 5.14.1
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-8e9d7edc",
    "date": "2024-03-27 20:06",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "a9e34a9bce59fdb78123c0eb824a171948c6b9e8",
        "CI_JOB_ID": "37296",
        "CI_PIPELINE_ID": "11892",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "25",
        "VERSION": "0.3.2"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "8e9d7edc24cd2c4079c272d0ce6d13fa08a0b0e8",
        "CI_JOB_ID": "36789",
        "CI_PIPELINE_ID": "11692",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "9",
        "VERSION": "0.3.2"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "8f2006a2540b65559971a9c87024ebd014cc3877",
        "CI_JOB_ID": "37335",
        "CI_PIPELINE_ID": "11909",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "3.1.1-dev"
    }
}
INFO project_data: Setting profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 22050, 2 channels
INFO app: checking babl_ext_path: /tmp/.mount_OpenShcd1kKc/usr/bin/lib/babl-ext
INFO app: setting BABL_PATH: /tmp/.mount_OpenShcd1kKc/usr/bin/lib/babl-ext
Screen HDMI-0
   devicePixelRatio: 1.0
   logicalDotsPerInch: 95.95804195804196
   physicalDotsPerInch: 71.62225924091666
   availableSizes: PyQt5.QtCore.QSize(1920, 1053)
INFO language: Qt Detected Languages: ['pt-BR']
INFO language: LANG Environment Variable: pt_BR.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO app: Setting font to /tmp/.mount_OpenShcd1kKc/usr/bin/images/fonts/Ubuntu-R.ttf
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO ui_util: Initializing UI for MainWindow
INFO thumbnail: Starting thumbnail server listening on ('127.0.0.1', 49553)
Sandboxing disabled by user.
Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShcd1kKc/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_OpenShcd1kKc/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/fernando/.openshot'
[0329/101703.818903:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShcd1kKc/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_OpenShcd1kKc/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/fernando/.QtWebEngineProcess'
[0329/101703.993318:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
INFO webengine: WebEngine backend initializing
INFO transition_model: updating transitions model.
INFO effects_model: updating effects model.
INFO emoji_model: updating emoji model.
INFO main_window: InitCacheSettings
INFO main_window: cache-mode: CacheMemory
INFO main_window: cache-limit-mb: 512
INFO main_window: cache-ahead-percent: 0.7
INFO main_window: cache-preroll-min-frames: 24
INFO main_window: cache-preroll-max-frames: 48
INFO main_window: cache-max-frames: 600
INFO main_window: Creating CacheMemory object with 536870912 byte limit
INFO preview_thread: QThread Start Method Invoked
INFO main_window: Cleared temporary files: /home/fernando/.openshot_qt/thumbnail
INFO main_window: Cleared temporary files: /home/fernando/.openshot_qt/blender
INFO main_window: Cleared temporary files: /home/fernando/.openshot_qt/title
INFO main_window: updateStatusChanged
INFO main_window: recover_backup
INFO project_data: Setting profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 22050, 2 channels
INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
INFO video_widget: Set video widget pixel aspect ratio to: 1.0
INFO main_window: updateStatusChanged
INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(872, 492)
INFO webengine: Registering WebChannel connection with WebEngine
**WARNING preview_thread: Audio initialization error: no channels
WARNING preview_thread: Your active audio device (HD-Audio Generic, ALC892 Digital; IEC958 (S/PDIF) Digital Audio Output||ALSA) does not match OpenShot (Default ALSA Output (currently PulseAudio Sound Server)||ALSA). Adjusting your 'Preferences->Playback->Audio Device' to match your active audio device: HD-Audio Generic, ALC892 Digital; IEC958 (S/PDIF) Digital Audio Output||ALSA
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.**
Property 'modal'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowModality'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'enabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'geometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'frameGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'normalGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'x'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'y'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'pos'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'frameSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'size'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'width'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'height'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'rect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'childrenRect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'childrenRegion'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizePolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizeIncrement'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'baseSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'palette'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'font'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'cursor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'mouseTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'tabletTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'isActiveWindow'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'focusPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'focus'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'contextMenuPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'updatesEnabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'visible'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'fullScreen'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumSizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'acceptDrops'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowOpacity'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowModified'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'toolTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'toolTipDuration'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'statusTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'whatsThis'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'accessibleName'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'accessibleDescription'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'layoutDirection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'autoFillBackground'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'styleSheet'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'locale'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowFilePath'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'inputMethodHints'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'title'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'url'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'selectedText'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'hasSelection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'zoomFactor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
INFO webview: Qt Ready
INFO webview: Angular Ready
INFO version: Found current version: {'error_rate_stable': 0.25, 'trans_rate_unstable': 0.001, 'error_rate_unstable': 0.05, 'openshot_version': '3.1.1', 'trans_rate_stable': 0.01}
INFO sentry: Sentry initialized for 'unstable': 0.05 sample rate, 0.001 transaction rate
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 823, resource id: 16039747, major code: 40 (TranslateCoords), minor code: 0
INFO ui_util: Initializing UI for dlgPreferences
INFO main_window: Preferences add cancelled
INFO main_window: ---------------- Shutting down -----------------
INFO thumbnail: Shutting down thumbnail server: ('127.0.0.1', 49553)
INFO logger_libopenshot: Shutting down libopenshot logger
INFO updates: Remove listener from UpdateManager: <windows.preview_thread.PreviewParent object at 0x7f04ff94d820>
INFO app:             OpenShot's session ended            
INFO app:             Fri Mar 29 10:17:30 2024            
INFO app: ================================================

**Comment by Colorjet3** [comment]
Hello @tuxslack.  I am going to assign this to the lead developer as I am a very novice Linux user and really struggle with Arch Linux, more so than other flavors like Ubuntu and Mint.

**Comment by fdziarmagowski** [comment]
> INFO app: openshot-qt version: 3.1.1
> INFO app: libopenshot version: 0.3.0
                                                            ^^^^

This is a Void Linux packaging "bug", the libopenshot dependency is not correct (should be >= 0.3.2 is 0.3.0)

**Comment by tuxslack** [comment]
> > INFO app: openshot-qt version: 3.1.1
> > INFO app: libopenshot version: 0.3.0
> > ^^^^
> 
> This is a Void Linux packaging "bug", the libopenshot dependency is not correct (should be >= 0.3.2 is 0.3.0)

Wouldn't the AppImage file be system independent?

Theoretically, should use libopenshot from the AppImage file, ignoring anything from the system.

**Comment by Colorjet3** [comment]
Hello @tuxslack.  I agree that the AppImage should be independent of what is installed in the operating system.

**Comment by meator** [comment]
> This is a Void Linux packaging "bug", the libopenshot dependency is not correct (should be >= 0.3.2 is 0.3.0)

Just to inform you, this issue was already fixed on Void Linux's side (if this issue was indeed caused by the openshot-qt/libopenshot version mismatch as noted in the quote). This issue may be closed now (unless you want to discuss AppImages and their bundled dependencies further, but that discussion may be more appropriate in a new issue).
