### ISSUE TITLE
daily build & ppa issues on Ubuntu 23.10 (mantic)

### ISSUE THREAD

**Issue by jimav** [OpenShot/openshot-qt#5492]
The Linux AppImage (3.1.1) won't run on Ubuntu 23.10, dying with
```
ImportError: /tmp/.mount_OpenShy1nBVK/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib/x86_64-linux-gnu/libharfbuzz.so.0)
```
Ubuntu 23.10 comes with GLIBC 2.38.

I tried using the ppa, following instructions at https://www.openshot.org/static/files/user-guide/installation.html#linux-ppa :
```
$ sudo add-apt-repository ppa:openshot.developers/ppa
E: The repository 'https://ppa.launchpadcontent.net/openshot.developers/ppa/ubuntu mantic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
...
$ sudo apt update
Err:9 https://ppa.launchpadcontent.net/openshot.developers/ppa/ubuntu mantic Release
  404  Not Found [IP: 185.125.190.80 443]
```
Despite the above, mysteriously, `sudo apt install openshot-qt python3-openshot` apparently installed openshot 3.1.1-dev but it doesn't look like all the right files came, as there are missing symbols in Python code:
```
$ rm -rf $HOME/.openshot_qt/
$ openshot-qt 
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Tue Apr  9 15:49:11 2024            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:           OpenShot (version 3.1.1-dev)          
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.1.1-dev
INFO app: libopenshot version: 0.2.7
INFO app: platform: Linux-6.5.0-27-generic-x86_64-with-glibc2.38
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.11.6
INFO app: qt5 version: 5.15.10
INFO app: pyqt5 version: 5.15.9
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 196, in main
    app = OpenShotApp(argv)
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 131, in __init__
    self.project = project_data.ProjectDataStore()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 66, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 291, in new
    profile = self.get_profile(profile_desc=default_profile_desc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 341, in get_profile
    if legacy_profile and legacy_profile.Key() == temp_profile.Key():
                          ^^^^^^^^^^^^^^^^^^
AttributeError: 'Profile' object has no attribute 'Key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==3.1.1.dev0', 'gui_scripts', 'openshot-qt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 198, in main
    app.show_errors()
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Tue Apr  9 15:49:14 2024            
INFO app: ================================================
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by Colorjet3** [comment]
This is a known issue.  The workaround for now is to download and run the AppImage.

1.  Go to openshot.org/download/#daily and download the latest dev daily build AppImage.
2.  Make it executable and run it.

**Comment by jimav** [comment]
> This is a known issue. The workaround for now is to download and run the AppImage.

ok, I see now that the images at the top are different even though same version number.
