### ISSUE TITLE
Re open issue #5626

### ISSUE THREAD

**Issue by jamercee** [OpenShot/openshot-qt#5628]
I'd like to re-open https://github.com/OpenShot/openshot-qt/issues/5626

Yesterday, I reported an issue I was having with openshot. The issue affected my Windows 11 Pro installation, suddenly generating BEX64 events and crashing on load.   It appeared to be solved by updating the Intel Arc driver, but this morning the issue has reoccurred.

Over night, Windows did apply updates, but there do not appear to be anything related to video drivers.

I ran openshot with the gdb debugger, and I've included a capture below of the thread error. My quick read is this is something related to DirectX12.  Would someone mind glancing this over and letting me know what they think?

Thanks

[New Thread 19272.0x1094]
[New Thread 19272.0x3f4]
[New Thread 19272.0x1a78]
[New Thread 19272.0x3cb8]
[New Thread 19272.0x30cc]
[New Thread 19272.0x10c4]
[New Thread 19272.0x6238]
[New Thread 19272.0x2260]
[New Thread 19272.0x6114]
[New Thread 19272.0x4140]
[New Thread 19272.0x6138]
[Thread 19272.0x6138 exited with code 0]
[New Thread 19272.0x3b1c]
[Thread 19272.0x3b1c exited with code 0]
[New Thread 19272.0x646c]
[Thread 19272.0x646c exited with code 0]
[New Thread 19272.0x474c]
[New Thread 19272.0x2078]
[Thread 19272.0x2078 exited with code 0]
gdb: unknown target exception 0xc0000409 at 0x7ff932f81758

Thread 25 received signal ?, Unknown signal.
[Switching to Thread 19272.0x474c]
0x00007ff932f81758 in igd12um64xeh!ctlGetSupported3DCapabilities ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll

--------------------

#0  0x00007ff932f81758 in igd12um64xeh!ctlGetSupported3DCapabilities ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#1  0x00007ff932f816ea in igd12um64xeh!ctlGetSupported3DCapabilities ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#2  0x00007ff932f87ebf in igd12um64xeh!ctlGetSupported3DCapabilities ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#3  0x00007ff932061d19 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#4  0x00007ff932061ccf in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#5  0x00007ff93304c51d in igd12um64xeh!ctlGetSupported3DCapabilities ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#6  0x00007ff932099702 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#7  0x00007ff932074ea6 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#8  0x00007ff93207399a in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#9  0x00007ff9320734a4 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#10 0x00007ff9320837ba in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#11 0x00007ff9320677bc in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#12 0x00007ff9320673eb in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#13 0x00007ff932067370 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
#14 0x00007ff95f39249c in igd12umd64!OpenAdapter12 ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12umd64.dll
#15 0x00007ff95f38171c in igd12umd64!OpenAdapter12 ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12umd64.dll
#16 0x00007ff95e8b8de0 in d3d12core!D3D12GetInterface () from C:\Windows\SYSTEM32\D3D12Core.dll
#17 0x00007ff95e8ba536 in d3d12core!D3D12GetInterface () from C:\Windows\SYSTEM32\D3D12Core.dll
#18 0x00007ff95e836c89 in ?? () from C:\Windows\SYSTEM32\D3D12Core.dll
#19 0x00007ff95e8399d5 in ?? () from C:\Windows\SYSTEM32\D3D12Core.dll
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12umd64.dll
#15 0x00007ff95f38171c in igd12umd64!OpenAdapter12 ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12umd64.dll
#16 0x00007ff95e8b8de0 in d3d12core!D3D12GetInterface () from C:\Windows\SYSTEM32\D3D12Core.dll
#17 0x00007ff95e8ba536 in d3d12core!D3D12GetInterface () from C:\Windows\SYSTEM32\D3D12Core.dll
#18 0x00007ff95e836c89 in ?? () from C:\Windows\SYSTEM32\D3D12Core.dll
#19 0x00007ff95e8399d5 in ?? () from C:\Windows\SYSTEM32\D3D12Core.dll
#20 0x00007ff95e84048e in ?? () from C:\Windows\SYSTEM32\D3D12Core.dll
#21 0x00007ff95e8419d6 in d3d12core!D3D12GetInterface () from C:\Windows\SYSTEM32\D3D12Core.dll
#22 0x00007ff9d82d6c4b in d3d12!D3D12CreateDevice () from C:\Windows\SYSTEM32\D3D12.dll
#23 0x00007ff9d82d63ae in d3d12!D3D12CreateDevice () from C:\Windows\SYSTEM32\D3D12.dll
#24 0x00007ff953f9f585 in igxehpgicd64!DumpRegistryKeyDefinitions ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igxelpgicd64.dll
#25 0x00007ff9538d6a6e in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igxelpgicd64.dll
#26 0x00007ff953ef3c7f in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igxelpgicd64.dll
#27 0x00007ffa1d55257d in KERNEL32!BaseThreadInitThunk () from C:\Windows\System32\kernel32.dll
#28 0x00007ffa1f86af28 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
#29 0x0000000000000000 in ?? ()

**Comment by Colorjet3** [comment]
Do you by any chance have made any changes in OpenShot regarding Hardware Acceleration?

Please try this:
1.  Close OpenShot if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Start OpenShot and test.

Let us know the result.

**Comment by jamercee** [comment]
First, thanks very much for taking the time to help. 

I've made no changes regarding hardware acceleration & openshot. I do have Hardware-accelerated GPU Scheduling turned on at the system level, but I just turned it off, rebooted & retryed. Same crash sequence -- no change. To eliminate the possibility I made some sort of profile change somewhere, I just did a complete remove / reinstall from scratch of openshot, but no difference.

Regarding the openshot_qt folder, I routinely have been deleting that. 

What's interesting is that when it crashes, it seems to be a point a point in the boot cycle that is before logs are created. When I delete the openshot_qt folder, the skeleton structure of folders get recreated, but the directories are all empty.

**Comment by Colorjet3** [comment]
Thank you @jamercee for all that information.  This is beyond my expertise.  I just assigned this to the lead developer for his review and next steps.

**Comment by TS232CZ** [comment]
I can add to it. Probably Win 11 tighten the vulnerability checks with recent updates (I'm on 24H2)

openshot-qt.exe	Stopped working	15.11.2024 14:10:38
0xc0000409	The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.
0x00fd1758	igd12um64xeh.dll	32.0.101.5768	
C:\Program Files\OpenShot Video Editor\openshot-qt.exe
![Screenshot 2024-11-15 144109](https://github.com/user-attachments/assets/615c9951-6bf9-4735-8b60-152f4ddae9e2)

Hopefully, it can help developers debug it. Perhaps a problematic call to the igd12um64xeh.dll? I hope they would be able to find out. Thank you

**Comment by Colorjet3** [comment]
Hello @TS232CZ There is a new dev daily build release with some updated code to address some audio issues with Windows 11 24H2.  I am not sure if it directly addresses this issue but would be worth a try.

Please go to openshot.org/download/#daily and download build #13113.  Install it and test it.
