### ISSUE TITLE
New version of markupsafe broke OpenShot

### ISSUE THREAD

**Issue by elter-tef** [OpenShot/openshot-qt#5643]
**Describe the bug:**
OpenShot will not run with markupsafe==2.1.5

**Steps to reproduce the behavior:**
1.Open terminal
2.Run 'openshot-qt'
3.get 

**Expected behavior:**
App running.

**System Details:**
- OpenShot Version openshot-3.2.1-1
- Operating System / Distro: Arch linux
- Python version  3.12.6

**Log Files:**
Log file empty

**Exception / Stacktrace:**
the essential message
`ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.12/site-packages/markupsafe/__init__.py)`

full run errors 
`Loaded modules from: /usr/lib/python3.12/site-packages/openshot_qt
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/openshot_qt/launch.py", line 190, in main
    sentry.init_tracing()
  File "/usr/lib/python3.12/site-packages/openshot_qt/classes/sentry.py", line 104, in init_tracing
    sdk.init(
  File "/usr/lib/python3.12/site-packages/sentry_sdk/_init_implementation.py", line 41, in _init
    client = sentry_sdk.Client(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/sentry_sdk/client.py", line 242, in __init__
    self._init_impl()
  File "/usr/lib/python3.12/site-packages/sentry_sdk/client.py", line 365, in _init_impl
    self.integrations = setup_integrations(
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/sentry_sdk/integrations/__init__.py", line 168, in setup_integrations
    type(integration).setup_once()
  File "/usr/lib/python3.12/site-packages/sentry_sdk/integrations/starlette.py", line 110, in setup_once
    patch_templates()
  File "/usr/lib/python3.12/site-packages/sentry_sdk/integrations/starlette.py", line 513, in patch_templates
    from starlette.templating import Jinja2Templates  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/starlette/templating.py", line 14, in <module>
    import jinja2
  File "/home/user/.local/lib/python3.12/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/user/.local/lib/python3.12/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/user/.local/lib/python3.12/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.12/site-packages/markupsafe/__init__.py)`

**Temporary Fix:**
If I Downgrade markupsafe to 2.0.1 app will run correctly.
`pip install markupsafe==2.0.1` 

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
I am not a Linux guy and am not understanding this issue.  However, have you tried running the AppImage and see if that works for you?

1. Go to OpenSHot.org/download/#daily and get the latest dev daily build AppImage.
2. Make the AppImage executable and run it.

**Comment by Colorjet3** [comment]
Hello @elter-tef I am closing this ticket since I did not hear back from you regarding trying the AppImage.  If you did try the AppImage and it worked then it would be nice to get confirmation.
