### ISSUE TITLE
Openshot does not close properly (2.3.1 - Linux)

### ISSUE THREAD

**Issue by eliboni** [OpenShot/openshot-qt#574]
**System Details:**
* Operating System / Distro: Xubuntu "Ubuntu 16.04.2 LTS"
* OpenShot Version: 2.3.1
**Issue Description and steps to reproduce:**
Start Openshot-qt from a terminal. Close openshot-qt form the GUI. Terminal does show the error below and process is not terminated:

```
enrico@gling:~$ ps -ef | grep opens
enrico   17340 30542  5 21:35 pts/8    00:01:58 /usr/bin/python3 /usr/bin/openshot-qt
```

```
Error
preview_thread:INFO onModeChanged
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 123, in closeEvent
    self.preview_thread.player.CloseAudioDevice()
  File "/usr/lib/python3/dist-packages/openshot.py", line 3758, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, QtPlayer, name)
  File "/usr/lib/python3/dist-packages/openshot.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/lib/python3/dist-packages/openshot.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
     metrics:INFO Track metric: {'date': 'Wed, 05 Apr 2017 23:12:54 GMT', 'pragma': 'no-cache', 'x-content-type-options': 'nosniff', 'age': '507269', 'content-type': 'image/gif', 'server': 'Golfe2', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'content-length': '35', 'access-control-allow-origin': '*', 'status': '200', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-location': 'http://www.google-analytics.com/collect?ul=en&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd3=5.5.1&tid=UA-4381101-5&cd4=5.5.1&v=1&aid=org.openshot.openshot-qt&cd2=3.5.2&sc=end&cd5=Ubuntu-16.04-xenial&cd1=0.1.3&cid=e5a89458-268c-49d5-833f-9a8fef74a7ea&t=screenview&aip=1&an=OpenShot+Video+Editor&av=2.3.1&cd=close-app'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track exception: {'date': 'Tue, 11 Apr 2017 20:10:26 GMT', 'content-length': '29', 'status': '200', 'vary': 'Accept-Encoding', '-content-encoding': 'gzip', 'content-type': 'text/html; charset=utf-8', 'server': 'Apache/2.2.22 (Ubuntu)'} (b'*exception-successfully-sent*')
```

**Comment by ankitpati** [comment]
No repro on Ubuntu 16.04 with [OpenShot 2.3.1 AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.AppImage "Download").

Please consider retrying the steps with the AppImage version instead of using the PPA, and let us know if the issue persists.

**Comment by eliboni** [comment]
Look, my ubuntu just updated some packages including

```
$ grep " install " /var/log/dpkg.log | grep "open"
2017-04-12 22:41:55 install libopenshot11:amd64 <none> 0.1.4+0+588+107+201703310337+daily~ubuntu16.04.1
```

now the problem is gone, I can close openshot-qt properly.

Also, several other minor problem which I did not report yesterday seems solved (example: I could not use preview).

Please close this one! Thanks

**Comment by ankitpati** [comment]
Looks like the problem was never with `openshot-qt`, but with `libopenshot`, a sister project.

Closing this as fixed.
