### ISSUE TITLE
Cant launch export dialog after revision 741.

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#591]
After revision 741, I can;t launch the export dialog.

> ui_util:INFO Initializing UI for Dialog
>   exceptions:ERROR Unhandled Exception
> Traceback (most recent call last):
>   File "/koko/2.0/src/windows/main_window.py", line 626, in actionExportVideo_trigger
>     win = Export()
>   File "/koko/2.0/src/windows/export.py", line 88, in __init__
>     get_app().window.timeline_sync.timeline.ClearAllCache()
>   File "/usr/lib/python3.6/site-packages/openshot.py", line 3966, in <lambda>
>     __getattr__ = lambda self, name: _swig_getattr(self, Timeline, name)
>   File "/usr/lib/python3.6/site-packages/openshot.py", line 80, in _swig_getattr
>     raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
> AttributeError: 'Timeline' object has no attribute 'ClearAllCache'

The change that causes the issue is from:
> if get_app().window.cache_object:
>            get_app().window.cache_object.Clear()

To:
> get_app().window.timeline_sync.timeline.ClearAllCache()

Archlinux 32 bit.

**Comment by firew4lker** [comment]
It was a failure of my system. Not Openshot.
