### ISSUE TITLE
AttributeError: 'QtPlayer' object has no attribute 'CloseAudioDevice'

### ISSUE THREAD

**Issue by v2e** [OpenShot/openshot-qt#638]
**System Details:**
* Operating System / Distro: Gentoo GNU/Linux
* OpenShot Version: 2.3.0

**Issue Description and steps to reproduce:**

Just start openshot-qt from the text console, close the application and see the log in the console. It ends with something like this:

```
preview_thread:INFO onModeChanged
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/openshot_qt/windows/main_window.py", line 123, in closeEvent
    self.preview_thread.player.CloseAudioDevice()
  File "/usr/lib64/python3.4/site-packages/openshot.py", line 3617, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, QtPlayer, name)
  File "/usr/lib64/python3.4/site-packages/openshot.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'QtPlayer' object has no attribute 'CloseAudioDevice'
```

**Comment by DylanC** [comment]
@v2e - I will have a look at this soon thanks.

**Comment by DylanC** [comment]
Not able to reproduce this in v2.4.1.
