### ISSUE TITLE
on Win7 x64 con't launch, ImportError: DLL load failed

### ISSUE THREAD

**Issue by arthur-jx** [OpenShot/openshot-qt#773]
**System Details:**
* Operating System / Distro: ? Win7 x64
* OpenShot Version: ?  v2.3.4-x86_64.
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.5\site-packages\cx_freeze-5.0-py3.5-mingw.egg\cx_Freeze\initscripts\Console.py", line 21, in <module>
  File "openshot_qt/launch.py", line 53, in <module>
  File "C:\Program Files\OpenShot Video Editor\classes\app.py", line 34, in <module>
    from PyQt5.QtWidgets import QApplication, QStyleFactory, QMessageBox
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 22, in <module>
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 14, in __bootstrap__
  File "C:\msys64\mingw64\lib\python3.5\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: 找不到指定的程序。

**Comment by DylanC** [comment]
@arthur-jx - Do you have this issue on v2.4?

**Comment by DylanC** [comment]
This error does not happen in latest version.
