### ISSUE TITLE
ERROR No module named 'httplib2'

### ISSUE THREAD

**Issue by ErunamoJAZZ** [OpenShot/openshot-qt#78]
Hello, I was installing openshot-qt in Debian Jessie with ubuntu Vivid ppa, and on start, this fail bc package *python3-httplib2* was not installed as a dependency.

```
$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.0.6)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.0.6
         app:INFO libopenshot version: 0.1.0
         app:INFO platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.4.2
         app:INFO qt5 version: 5.3.2
         app:INFO pyqt5 version: 5.3.2
    language:INFO Qt Detected Languages: ['es-CO', 'es']
    language:INFO LANG Environment Variable: es_CO.UTF-8
    language:INFO LOCALE Environment Variable: es_CO
    language:INFO Attempting to load qt_es_CO.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qt_es_CO.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load es_CO.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load es/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded es/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: es_CO.UTF-8)
project_data:INFO Setting default profile to HDV 720 24p
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.0.6', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
      logger:ERROR app = OpenShotApp(sys.argv)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 104, in __init__
      logger:ERROR import classes.metrics
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/metrics.py", line 28, in <module>
      logger:ERROR import httplib2
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'httplib2'
```

Thank you ;)

**Comment by jonoomph** [comment]
Thanks for the bug report! I've added this missing dependency to my daily PPA and notified the official Debian packager.
