### ISSUE TITLE
ImportError: No module named 'PyQt5.QtWebKitWidgets'

### ISSUE THREAD

**Issue by aboettger** [OpenShot/openshot-qt#887]
**System Details:**
* Operating System / Distro: Kubuntu 17.04
* OpenShot Version: 2.3.4
* Installed via PPA
````
openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.3.4)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.3.4
         app:INFO libopenshot version: 0.1.7
         app:INFO platform: Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.3
         app:INFO qt5 version: 5.9.1
         app:INFO pyqt5 version: 5.9
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_de in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load de_DE.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: de_DE.UTF-8
    language:INFO LOCALE Environment Variable: en_US
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_de in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_de_DE.UTF-8 in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Successfully loaded qtbase_de_DE.UTF-8 in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_de in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_de_DE.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_de in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load de_DE.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: de_DE.UTF-8)
project_data:INFO Setting default profile to HDV 720 24p
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.3.4', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 163, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *old-exception-ignored*
```

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@aboettger - This version is out of date. Can you please try v2.4.

**Comment by aboettger** [comment]
@DylanC 
```
openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.0)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.0
         app:INFO libopenshot version: 0.1.8
         app:INFO platform: Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.3
         app:INFO qt5 version: 5.9.1
         app:INFO pyqt5 version: 5.9
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_de in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load de_DE.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: de_DE.UTF-8
    language:INFO LOCALE Environment Variable: en_US
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_de in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_de_DE.UTF-8 in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Successfully loaded qtbase_de_DE.UTF-8 in '/home/aboettger/.local/lib/python3.5/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_de in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_de_DE.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_de in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load de_DE.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: de_DE.UTF-8)
project_data:INFO Setting default profile to HDV 720 24p
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.4.0', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 163, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *duplicate-exception-ignored*
```

**Comment by DylanC** [comment]
@aboettger - Does the appImage work for you?

**Comment by DylanC** [comment]
@aboettger - I recommend to use the AppImage. I have heard the PPA has issues.

**Comment by loxK** [comment]
OpenShot (version 2.4.1-dev1) on 16.04 same issue.

Why has it been closed ?

**Comment by DylanC** [comment]
@loxK - The PPA has issues since Qt dropped webkitwidgets support in favour of webengine. Its out of our control.

**Comment by peanutbutterandcrackers** [comment]
I use PPA for my 16.04 machines (and this is Elementary OS 0.4.1 - based on 16.04.3 itself) and it works quite well. No problems whatsoever. Strange...

Maybe it works now? o.O Or, maybe the daily PPA works, perhaps? o.O
